### ISSUE TITLE
Casting Return Null

### ISSUE THREAD

**Issue by aboodh95** [daryllabar/DLaB.Xrm.XrmToolBoxTools#102]
Hi
I have one question 
In case this line 
`ets_contract contract = service.Retrieve(ets_contract.EntityLogicalName, contractID, new ColumnSet(true)) as ets_contract;`

the object contract will be good but in case not all columns were loaded 
Some times not always the contract object will be null 

do you have any idea 
did i make something wrong

**Comment by daryllabar** [comment]
When using a retrieve, the entity returned will never be null.    When using the all columns option, all attributes that have a value will be returned, but if it doesn't have a value, it will still be null.  Does that help?.  Not sure what your exact issue is since your English is a little rough.

**Comment by aboodh95** [comment]
i'm sorry about my English
my issue is the casting is not happening in case not all columns loaded the whole object will be null 
EX:
`     QueryExpression query = new QueryExpression("account");
                query.ColumnSet = new ColumnSet("name");
                var Accounts = service.RetrieveMultiple(query);
                foreach (var item in Accounts.Entities)
                {
                    Account account = item as Account;
                    //The account will be null
                }
`

**Comment by daryllabar** [comment]
You can't cast the entity, you need to call .ToEntity<Account>()

**Comment by aboodh95** [comment]
Thank you for this information
