### ISSUE TITLE
Attributes does not appear in Option Type Settings

### ISSUE THREAD

**Issue by nargudin** [daryllabar/DLaB.Xrm.XrmToolBoxTools#104]
I have about three fields that I have added to my entity. All the fields are option sets. Only one appears in the drop down in the Option Type Setting tab.

**Comment by daryllabar** [comment]
Any chance they are managed?

**Comment by nargudin** [comment]
Thanks for the reply Daryl. No they are not managed solution. I was expecting all three option sets to appear but only one did and that option set is global option set already. 

 

Nilo Argudin 
Mobile: 407 758 6390
 <mailto:nilo.argudin@gmail.com> nilo.argudin@gmail.com

**Comment by daryllabar** [comment]
If you want to convert a local to a global, you'll have to create the global option set first, then open up the tool.  If the int values are the same, it'll map over the values if you choose to migrate the data.

**Comment by nargudin** [comment]
Oh I thought it would take a Local Option Set and convert it to a Global Option Set along with the Values from the Local Option set. 

 

Nilo Argudin 
Mobile: 407 758 6390
 <mailto:nilo.argudin@gmail.com> nilo.argudin@gmail.com

**Comment by daryllabar** [comment]
You have to manually create the Global Option set first, then you can select your local options set attribute, choose the Global, and it will recreate it as a global, handling all views, forms, business rules, etc, as long with the data (assuming the int values can map). Make sense?

**Comment by daryllabar** [comment]
I think you've got it.  It only converts a local option set attribute to a global option set attribute, pointing to a pre-existing global option set.  

At some point in time I'd like to add the feature of what you're asking, create a new global option set, based on the local option set of the attribute, but since creating a new Global Option set is fairly straightforward out-of-the-box, it hasn't made it to high on my priority list.

**Comment by nargudin** [comment]
Thanks for clarification on this. If you are taking suggestion it would be nice to have a simpler way to have cascade, dependent or hierarchy  option sets. I have been hoping that MS would develop an easier way to do this. 

 

Nilo Argudin 
Mobile: 407 758 6390
 <mailto:nilo.argudin@gmail.com> nilo.argudin@gmail.com

**Comment by daryllabar** [comment]
That requires client changes as well, which is outside the current scope of this tool.
