### ISSUE TITLE
Error in format of Transliteration file

### ISSUE THREAD

**Issue by Ijimo** [daryllabar/DLaB.Xrm.XrmToolBoxTools#105]
Hello i have some problem with OptionSet generator.
_**Ensuring Context File is Accessible 
Writing file OptionSets.cs to C:\Users\igor.momot\AppData\Local\Temp\tmpD0EA.tmp 
System.Exception: Error in format of Transliteration file C:\Users\igor.momot\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\alphabets\1049.json
   ў DLaB.CrmSvcUtilExtensions.OptionSet.Transliteration.TransliterationService.LoadAlphabet(Int32 languageCode)
   ў DLaB.CrmSvcUtilExtensions.OptionSet.Transliteration.TransliterationService.Transliterate(Int32 languageCode, String label)
   ў DLaB.CrmSvcUtilExtensions.NamingService.GetPossiblyDuplicateNameForOption(OptionSetMetadataBase metadata, IServiceProvider services, OptionMetadata option)
   ў DLaB.CrmSvcUtilExtensions.NamingService.GetNameForOption(OptionSetMetadataBase optionSetMetadata, OptionMetadata optionMetadata, IServiceProvider services)
   ў DLaB.CrmSvcUtilExtensions.NamingService.GetPossiblyDuplicateNameForOption(OptionSetMetadataBase metadata, IServiceProvider services, OptionMetadata option)
   ў DLaB.CrmSvcUtilExtensions.NamingService.GetNameForOption(OptionSetMetadataBase optionSetMetadata, OptionMetadata optionMetadata, IServiceProvider services)
   ў DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService.GenerateOptionSet(OptionSetMetadataBase optionSetMetadata, IServiceProvider services)
   ў Microsoft.Crm.Services.Utility.CodeGenerationService.BuildOptionSets(OptionSetMetadataBase[] optionSetMetadata, ServiceProvider serviceProvider)
   ў Microsoft.Crm.Services.Utility.CodeGenerationService.BuildCodeDom(IOrganizationMetadata organizationMetadata, String outputNamespace, ServiceProvider serviceProvider)
   ў Microsoft.Crm.Services.Utility.CodeGenerationService.Microsoft.Crm.Services.Utility.ICodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
   ў DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   ў DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
Output file was not updated or not found!  **_

What could go wrong?

**Comment by daryllabar** [comment]
Have you updated the json file yourself?  If so, can you post it here?  If not, try uninstalling and installing

**Comment by Ijimo** [comment]
The Newtonsoft.Json file and 1049.json did not change. Reinstalled the program, the error is still the same.

**Comment by daryllabar** [comment]
Hmm... just noticed I have a dependency on Newtonsoft that isn't being used anymore, so I've removed that from the project...

I must have some sort of Current Culture bug.  What is your current Culture of your machine set to?

Here is the code that is doing the deserializing if you want to debug.
```
private static TransliterationAlphabet LoadAlphabet(int languageCode)
{
    var serializer = new DataContractJsonSerializer(typeof(AlphabetPoco));
    var path = System.IO.Path.Combine(Path, languageCode + ".json");
    AlphabetPoco alphabetJson;
    using (var stream = GenerateStreamFromString(File.ReadAllText(path)))
    {
        alphabetJson = (AlphabetPoco)serializer.ReadObject(stream);
    }

    if (alphabetJson.alphabet.Any(a =>
        a == null ||
        a.Length < 2 ||
        string.IsNullOrWhiteSpace(a[0]) ||
        a[1] == null))
    {
        throw new Exception($"Error in format of Transliteration file {path}");
    }

    var dictionary =
        alphabetJson.alphabet
        .ToDictionary(
            x => x[0][0],
            x => x[1]);

    var alphabet = new TransliterationAlphabet(languageCode, dictionary);

    Alphabets.Add(alphabet);

    return alphabet;
}
```

If you don't need Russian, you can also feel free  to delete the 1049.json file.

**Comment by Ijimo** [comment]
I just need the Russian language) Unfortunately I do not understand where it can be debugged

**Comment by Ijimo** [comment]
I have ru-RU culture on my PC and same culture on server.

**Comment by daryllabar** [comment]
Found it.  Delete line 40:
          [ " ", "_" ],
from the 1049,json

**Comment by Ijimo** [comment]
It seems to work.Let's see how the plugins will behave further.

**Comment by skfd** [comment]
I think `string.IsNullOrWhiteSpace(a[0])` is the culprit as this is a white space we're replacing, but code thinks it's error. Kind of an edge case for sure.

I put "replacing spaces with underscores" because I like snake case and is easier than capitalising words.

Planned to make a toggle in UI so users can choose between snake_case and PascalCase for their enums. Did not do that yet, because I drifted away from CRM coding.

@Ijimo hello Igor!
