### ISSUE TITLE
OptionSet Filtering

### ISSUE THREAD

**Issue by Mithradatha** [daryllabar/DLaB.Xrm.XrmToolBoxTools#107]
I need to be able to filter out the OptionSets that I don't want to generate. My Organization has a very large number of OptionSets, so manually removing each one in the dialog box is not practical. I would prefer not to have to write a script that removes each OptionSet file that I don't want to use. 

I have created a SQL script that automatically generates an "ignore list" that is compatible with <OptionSetsToSkip> in \AppData\Roaming\MscrmTools\XrmToolBox\Settings\DLaB.EarlyBoundGenerator.DefaultSettings.xml

It is a list that looks like: ```contact_accountrolecode|contact_address1_addresstypecode|contact_address1_freighttermscode```

Unfortunately, I don't know of a way to load the configuration file into the "OptionSets to Skip" DialogBox, so that it will save those settings when executing CrmSvcUtil.

Any suggestions would be appreciated.

**Comment by Mithradatha** [comment]
Steps to fix:
1. Copy ```DLaB.EarlyBoundGenerator.DefaultSettings.xml``` to a new location
2. Add the pipe-delimited string of OptionSets to ```<OptionSetsToSkip>```
3. Save the file
4. Rename the file
5. Point 'Settings Path' to the newly saved configuration file
6. Click 'OptionSets To Skip'

**Comment by daryllabar** [comment]
Looks like you figured it out.  If I can get my act together, I'm planning on using a solution to manage the entities/optionsets/actions to generate.
