### ISSUE TITLE
Enum method being generated for skipped OptionSet

### ISSUE THREAD

**Issue by fedejousset** [daryllabar/DLaB.Xrm.XrmToolBoxTools#110]
When the option "Generate OptionSet Enum Properties" is enabled and an OptionSet is skipped, the Enum method is still being generated for all the fields using the OptionSet which leads to an error because the Enum has not been created.

**Scenario**:
In a vanilla organization I created a global OptionSet called "new_contacttesttype" and a field in the contact entity called "new_testtype" (OptionSet field which is using the global OptionSet created earlier). The Early Bound Generator is configured to generate the Enum virtual methods and it also will skip our global OptionSet:

<img width="656" alt="early bound generator settings" src="https://user-images.githubusercontent.com/20836210/28021096-9dd114c8-657e-11e7-935b-21b4c5817438.png">

`<OptionSetsToSkip>organization_currencyformatcode|quote_statuscode|new_contacttesttype</OptionSetsToSkip>`

After creating the early bound classes, the Enum method is created but it references to an Enum which is not present in the OptionSet class (it was correctly skipped):
<img width="644" alt="entity error" src="https://user-images.githubusercontent.com/20836210/28021196-f88cd320-657e-11e7-895a-6ab3313f5d99.PNG">

My understanding is that in this scenario the virtual method should be skipped to avoid generating this error but it's not clear for me what should happen with the actual field.

**Comment by daryllabar** [comment]
Thanks for the very through report.  The Enum should not get generated, and the enum property should not get generated as well.  In the mean time, if you select UnMapped Properties, and add your attribute there, does that resolve the issue for you?

**Comment by fedejousset** [comment]
Hi Daryl, thanks for your quick answer. 
Yes, skipping the global OptionSet and adding the field to the Unmapped Properties did the trick for now. Thanks for the workaround!

**Comment by fedejousset** [comment]
Great, I'll test it as soon as possible. Thanks Daryl!
