### ISSUE TITLE
Exception when run

### ISSUE THREAD

**Issue by aslanovsergey** [daryllabar/DLaB.Xrm.XrmToolBoxTools#115]
![image](https://user-images.githubusercontent.com/22150933/28524835-d0f5d3e0-708a-11e7-9439-20b31768ca3b.png)

**Comment by aslanovsergey** [comment]
And then such exceptions for any create invocation
![image](https://user-images.githubusercontent.com/22150933/28524924-1fb08f3e-708b-11e7-9332-2e9c706c5fca.png)

**Comment by daryllabar** [comment]
Thanks for reporting.  What version, and was this a new install or an update?

**Comment by aslanovsergey** [comment]
It was new install. 1.2017.7.19

**Comment by daryllabar** [comment]
Can you try the 1.2017.7.23 version?

**Comment by aslanovsergey** [comment]
Huge thanks) now then it works
