### ISSUE TITLE
Enum generated multiple times

### ISSUE THREAD

**Issue by rajyraman** [daryllabar/DLaB.Xrm.XrmToolBoxTools#117]
When I generate the Optionsets through crmsvcutil some optionsets are generated twice. When I generated this for CRM online I got an error for officedocument_documenttype being duplicated.

![image](https://user-images.githubusercontent.com/5035266/28953195-cffcbc3c-7919-11e7-89bc-acf2693853bd.png)

**Comment by daryllabar** [comment]
That's kind of amazing.  

Can you give me the CrmSvcUtil.exe.config file and the cmd line used?

You can feel free to obsfucate the org, uid, and pwd.

**Comment by rajyraman** [comment]
**for entity**
`/codeCustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions"`

**for optionsets**
`"/codeCustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CreateOptionSetEnums,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions"`

I use it along with /connstr parameter. Nothing fancy. I pointed it against the MVP org that was setup.

**Comment by rajyraman** [comment]
Both DocumentTemplate and PersonalDocumentTemplate entities have an Optionset called documenttype. That seems to be the issue.

**Comment by rajyraman** [comment]
This is the appsettings I am going to try now to get around this issue.

![image](https://user-images.githubusercontent.com/5035266/28953861-82ae1426-791e-11e7-80ab-b55f4e261f85.png)

**Comment by daryllabar** [comment]
Aww. Gotta give me an image of the app settings?

**Comment by rajyraman** [comment]
`
  <appSettings>
    <add key="MaxCrmConnectionTimeOutMinutes" value="20" />
    <add key="ActionCommandLineText" />
    <add key="ActionsToSkip" />
    <add key="AddDebuggerNonUserCode" value="True" />
    <add key="AddNewFilesToProject" value="True" />
    <add key="CreateOneFilePerAction" value="False" />
    <add key="CreateOneFilePerEntity" value="False" />
    <add key="CreateOneFilePerOptionSet" value="False" />
    <add key="EntityAttributeSpecifiedNames" />
    <add key="EntityCommandLineText" value="" />
    <add key="EntitiesToSkip" value="PersonalDocumentTemplate|DocumentTemplate" />
    <add key="GenerateActionAttributeNameConsts" value="False" />
    <add key="GenerateAttributeNameConsts" value="False" />
    <add key="GenerateAnonymousTypeConstructor" value="True" />
    <add key="GenerateEntityRelationships" value="False" />
    <add key="GenerateEnumProperties" value="True" />
    <add key="InvalidCSharpNamePrefix" value="_" />
    <add key="MakeReadonlyFieldsEditable" value="False" />
    <add key="MakeResponseActionsEditable" value="False" />
    <add key="LocalOptionSetFormat" value="{0}_{1}" />
    <add key="OptionSetsToSkip" value="officedocument_documenttype"/>
    <add key="OptionSetCommandLineText" />
    <add key="PropertyEnumMappings" />
    <add key="RemoveRuntimeVersionComment" value="True" />
    <add key="UseDeprecatedOptionSetNaming" value="True" />
    <add key="UnmappedProperties" />
    <add key="UseTfsToCheckoutFiles" value="False" />
    <add key="UseXrmClient" value="False" />
  </appSettings>
`
Going to try this now.

**Comment by daryllabar** [comment]
Try changing the "UseDeprecatedOptionSetNaming" value to False

**Comment by rajyraman** [comment]
Getting a different error.

![image](https://user-images.githubusercontent.com/5035266/28954932-e51f6360-7925-11e7-89cd-3aae8101d9b0.png)

Below is my current setting which appears to be working

```xml
  <appSettings>
    <add key="MaxCrmConnectionTimeOutMinutes" value="20" />
    <add key="ActionCommandLineText" />
    <add key="ActionsToSkip" />
    <add key="AddDebuggerNonUserCode" value="True" />
    <add key="AddNewFilesToProject" value="True" />
    <add key="CreateOneFilePerAction" value="False" />
    <add key="CreateOneFilePerEntity" value="False" />
    <add key="CreateOneFilePerOptionSet" value="False" />
    <add key="EntityAttributeSpecifiedNames" />
    <add key="EntityCommandLineText" value="" />
    <add key="EntitiesToSkip" value="PersonalDocumentTemplate|DocumentTemplate|msdyn_requirementstatus" />
    <add key="GenerateActionAttributeNameConsts" value="False" />
    <add key="GenerateAttributeNameConsts" value="False" />
    <add key="GenerateAnonymousTypeConstructor" value="True" />
    <add key="GenerateEntityRelationships" value="False" />
    <add key="GenerateEnumProperties" value="True" />
    <add key="InvalidCSharpNamePrefix" value="_" />
    <add key="MakeReadonlyFieldsEditable" value="False" />
    <add key="MakeResponseActionsEditable" value="False" />
    <add key="LocalOptionSetFormat" value="{0}_{1}" />
    <add key="OptionSetsToSkip" value="officedocument_documenttype"/>
    <add key="OptionSetCommandLineText" />
    <add key="PropertyEnumMappings" />
    <add key="RemoveRuntimeVersionComment" value="True" />
    <add key="UseDeprecatedOptionSetNaming" value="False" />
    <add key="UnmappedProperties" />
    <add key="UseTfsToCheckoutFiles" value="False" />
    <add key="UseXrmClient" value="False" />
  </appSettings>
```

**Comment by daryllabar** [comment]
Did you delete everything and regenerate?

**Comment by rajyraman** [comment]
Yes.

**Comment by daryllabar** [comment]
Interesting... I'm not seeing that listed anywhere in my ...  Any chance you have a test account I could use?

**Comment by rajyraman** [comment]
Credentials sent to your hotmail. DM if you cannot access.

**Comment by daryllabar** [comment]
I believe this is actually due to "Entity and OptionSet Could Have the Same Exact Name" #1

**Comment by rajyraman** [comment]
I don't think it is that. My initial theory was 

_Both DocumentTemplate and PersonalDocumentTemplate entities have an Optionset called documenttype. That seems to be the issue._

**Comment by daryllabar** [comment]
You have two issues.  Your first issue is related to using the Deprecated OptionSet Naming Conventions.  I may just need to remove that as an option.  The second issue, is related to #1

**Comment by daryllabar** [comment]
Can you try this @rajyraman with Deprecated OptionSet Naming Conventions disabled?  I believe the default naming service will detect if a name has already been generated, and if so, it will postfix a "1" to it so it is unique.  Before, when I was generating option sets, I wasn't processing all of the names of the entities first before processing the names of the option sets, but when I was generating entity enum properties, the entity had already been processed, and so it created a new type with the new postfixed value for the attribute type.

Clear as mud?

[DLaB.CrmSvcUtilExtensions.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/1204774/DLaB.CrmSvcUtilExtensions.zip)

**Comment by rajyraman** [comment]
You are correct. Works now. 👍
