### ISSUE TITLE
Error on generating Entities

### ISSUE THREAD

**Issue by micheleietri** [daryllabar/DLaB.Xrm.XrmToolBoxTools#119]
When launching entity generation I got the following error

`"C:\Program Files (x86)\XrmToolbox\Storage\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"*******" /namespace:"Gastaldi.Crm.Integrazione.CrmService.ProxyClasses" /out:"C:\Users\michele.ietri\Desktop\ProxyClasses\Entities\XrmServiceContext.cs" /servicecontextname:"XrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"*******" /password:"*******"

CrmSvcUtil : CRM Service Utility [Version 8.2.1.8676]
© 2015 Microsoft Corporation. All rights reserved

[**** Ensuring Context File is Accessible ****]
[**** Writing file XrmServiceContext.cs to C:\Users\michele.ietri\AppData\Local\Temp\tmp3D89.tmp ****]
System.IO.FileLoadException: Could not load file or assembly 'CrmSvcUtil, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'CrmSvcUtil, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.WriteFile(String outputFile, String language, CodeNamespace codenamespace, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.Microsoft.Crm.Services.Utility.ICodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].`

I'm connecting to an online Dynamics365 instance, option sets and actions are correctly generated, and till Friday everything was working fine!

I tried to update, uninstall and reinstall the tool, but the issue persist.

Michele Ietri

**Comment by daryllabar** [comment]
Hmm... Somehow the App.Config for the CrmSvcUtil lost it's re-direct binding.
 
Copy and over the CrmSvcUtil.exe.config with this and re-run the tool for now:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="MaxCrmConnectionTimeOutMinutes" value="20"/>
  </appSettings>
  <system.diagnostics>
    <trace autoflush="true"/>
    <sources>
      <source name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" switchName="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="console" type="System.Diagnostics.ConsoleTraceListener"/>
          <add name="fileListener"/>
        </listeners>
      </source>
      <source name="Microsoft.Xrm.Tooling.CrmConnectControl" switchName="Microsoft.Xrm.Tooling.CrmConnectControl" switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="console" type="System.Diagnostics.ConsoleTraceListener"/>
          <add name="fileListener"/>
        </listeners>
      </source>
      <source name="CrmSvcUtil" switchName="CrmSvcUtil" switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="console" type="System.Diagnostics.ConsoleTraceListener"/>
          <add name="fileListener"/>
        </listeners>
      </source>
    </sources>
    <switches>

      <!--Possible values for switches: Off, Error, Warning, Information, Verbose
						Verbose:      includes Error, Warning, Info, Trace levels
						Information:  includes Error, Warning, Info levels
						Warning:      includes Error, Warning levels
						Error:        includes Error level-->

      <add name="Microsoft.Xrm.Tooling.CrmConnectControl" value="Error"/>
      <add name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" value="Off"/>
      <add name="CrmSvcUtil" value="Error"/>
    </switches>

    <sharedListeners>
      <add name="fileListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="CrmSvcUtil.log"/>
    </sharedListeners>

  </system.diagnostics>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Crm.Sdk" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Xrm.Sdk" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Xrm.Sdk.Workflow" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Crm.Sdk.Proxy" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Xrm.Sdk.Deployment" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Crm.Workflow" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Crm" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
	    <dependentAssembly>
        <assemblyIdentity name="CrmSvcUtil" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="4.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.18.0.0" newVersion="2.18.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2"/>
  </startup>
</configuration>

```

**Comment by daryllabar** [comment]
Please download the 1.2017.8.6 and let me know if it fails.

**Comment by aboodh95** [comment]
i'm getting this error 

![image](https://user-images.githubusercontent.com/12459798/29027703-de64712c-7b92-11e7-84d3-be4b552af740.png)

**Comment by daryllabar** [comment]
Oh I hate it when i make typos in my ILMerge script...
Try 1.2017.8.7 @aboodh95 and thanks fore reporting the issue!

**Comment by aboodh95** [comment]
It's working now 

Thank you

**Comment by micheleietri** [comment]
Yep, it seems to be working even for me now! Thank you!

2017-08-07 16:13 GMT+02:00 Abood Hamwi <notifications@github.com>:
