### ISSUE TITLE
Error On using

### ISSUE THREAD

**Issue by aboodh95** [daryllabar/DLaB.Xrm.XrmToolBoxTools#120]
Hi

I'm getting this error while i'm trying to bound entities

`CRM Authentication Type Detected: OnlineFederation
Executing "C:\Users\User\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://org.api.crm4.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"Dynamics_365_Dll" /out:"C:\Users\User\AppData\Roaming\MscrmTools\XrmToolBox\Settings\CrmSvcUtil Ref\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"" /password:"************" 
CrmSvcUtil : CRM Service Utility [Version 8.2.1.8676]
? 2015 Microsoft Corporation. All rights reserved

 Ensuring Context File is Accessible 
 Writing file CrmServiceContext.cs to C:\Users\User\AppData\Local\Temp\tmpBEF0.tmp 
System.IO.FileLoadException: Could not load file or assembly 'CrmSvcUtil, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'CrmSvcUtil, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.WriteFile(String outputFile, String language, CodeNamespace codenamespace, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.Microsoft.Crm.Services.Utility.ICodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)

=== Pre-bind state information ===
LOG: DisplayName = CrmSvcUtil, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Users/User/AppData/Roaming/MscrmTools/XrmToolBox/Plugins/CrmSvcUtil Ref/
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.Xrm.Client.CodeGeneration, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\User\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: CrmSvcUtil, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Attempting download of new URL file:///C:/Users/User/AppData/Roaming/MscrmTools/XrmToolBox/Plugins/CrmSvcUtil Ref/CrmSvcUtil.DLL.
LOG: Attempting download of new URL file:///C:/Users/User/AppData/Roaming/MscrmTools/XrmToolBox/Plugins/CrmSvcUtil Ref/CrmSvcUtil/CrmSvcUtil.DLL.
LOG: Attempting download of new URL file:///C:/Users/User/AppData/Roaming/MscrmTools/XrmToolBox/Plugins/CrmSvcUtil Ref/CrmSvcUtil.EXE.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

Output file was not updated or not found!  C:\Users\User\AppData\Roaming\MscrmTools\XrmToolBox\Settings\CrmSvcUtil Ref\CrmServiceContext.cs
`

**Comment by daryllabar** [comment]
This the same as #119 Closing this issue, to use that one instead.
