### ISSUE TITLE
Multi-line Text Issue

### ISSUE THREAD

**Issue by JSpin2088** [daryllabar/DLaB.Xrm.XrmToolBoxTools#122]
I've identified the problem with the multi-line text data type. Currently, it is treating single line and multi-line the same. 

In the CreateText method you use the StringAttributeMetadata which is correct

But in the CreateMemo method you are also using StringAttributemetadata which is not correct. The end result is changing the source field into a single line of text even if you chose mutli-line.

I've made a change locally, but essentially for Memo its to change and use the MemoAttributeMetadata class.
`public static AttributeMetadata CreateMeme(int? maxLength = null, ImeMode? imeMode = ImeMode.Auto)
{
     return new MemoAttributeMetadata
     {
           MaxLength = maxLength ?? 2000,
           ImeMode = imeMode
     };
}`

**Comment by daryllabar** [comment]
I don't believe I have a create Memo method...

**Comment by JSpin2088** [comment]
That's the problem 😄

**Comment by daryllabar** [comment]
Can you send me a pull request?

**Comment by JSpin2088** [comment]
I probably won't get to it for a while as the need has been fulfilled 😞 
Lucky for you I just gave it to you above. Just slap that in the AttribuiteManagerPlugin.cs, then update your logic in the GetNewAttributeType() method in your switch statement to call CreateMemo in the "Multiple Lines of Text" branch.

**Comment by daryllabar** [comment]
V1.2017.8.8 built.  Let me know if this doesn't work.
