### ISSUE TITLE
Multilanguage support for optionsets

### ISSUE THREAD

**Issue by strwase** [daryllabar/DLaB.Xrm.XrmToolBoxTools#13]
Not as much an issue as a question, 
I have a multilingual environment and I was wondering if it is possible to generate Enums for the translated options as well?

**Comment by daryllabar** [comment]
So rather than creating the English versions of the Option Sets, specify another language?

**Comment by daryllabar** [comment]
I think by default it uses whatever the localized label is for the user making the call.  Have you tried controlling it that way?  If not, I could potentially add a way to specify the language by Language Code.  Would that work?

**Comment by daryllabar** [comment]
@strwase do you have a work around?

**Comment by strwase** [comment]
No, I'm still stuck I'm afraid. 

Noticed I can't use the enums to achieve what I wanted, because the attribute values get trimmed for use in an ENUM (spaces and brackets removed for example) 
Then I tried to generate a class from the stringmap entity, but that doesn't seem to be possible either. 

I need the attribute values as is, because I need to pass them to a multilingual website to be used in numerous webforms as options in drop downs

**Comment by daryllabar** [comment]
Ah, @strwase  you're attempting to use the Option Sets to get the actual Text Values of the Option Sets?

There is an SDK call that you'll need to use to do that.
