### ISSUE TITLE
Cannot save Entities to skip

### ISSUE THREAD

**Issue by lucengelhardt** [daryllabar/DLaB.Xrm.XrmToolBoxTools#130]
When I have selected entities to skip, all entities are generated anyway. The selection is not applied when generating. When opening the dialog again (using the button 'Entities to Skip' All entities are selected (again!). I don't see a save-button in the dialog. If it should be there, then is outside the visible area of the dialog.
![dialog](https://user-images.githubusercontent.com/4045024/31380754-8ed8cec6-adb2-11e7-97c9-e576ceeae5db.PNG)

**Comment by daryllabar** [comment]
hmm... What is your resolution? Mine looks fine:

![image](https://user-images.githubusercontent.com/9728423/31386263-ce81f358-ad8b-11e7-826a-75238d852e89.png)

**Comment by lucengelhardt** [comment]
Screen Resolution is 1920x1080, Using Windows 8.1
That should be enough. It looks like a rendering issue. The select-boxes are drawn all the way down to the bottom of the dialog. Whatever resolution I choose......

**Comment by daryllabar** [comment]
Do you have text zoon turned on?  As a work around you can add the entities to the XrmTookBox settings XML file

**Comment by lucengelhardt** [comment]
I don't have Text-zoom turned on. 
I'm willing to aad the, just to the XMl-file.
What should the XML-element be to add the entities to.
I don't see any element like <EntitiesToSkip> .....  (<OptionSetsToSkip> is there though....)
How should the content of the element look like?

**Comment by daryllabar** [comment]
Ok, using my monitor, I didn't have any issues, but using my laptop, I did.  I Found the actual issue and resolved it.  Get latest 2017.10.11.  Thanks for reporting the bug!

**Comment by daryllabar** [comment]
My science teacher in HS was Walt Elhardt... Any relation?
