### ISSUE TITLE
System.ArgumentNullException: Organization cannot be null or empty.

### ISSUE THREAD

**Issue by yuvalrs** [daryllabar/DLaB.Xrm.XrmToolBoxTools#132]
I am using IFD Deployment.

Output:
Executing "C:\Users\Yuval\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /namespace:"NGMessage.Plugins" /out:"C:\Users\Yuval\AppData\Roaming\MscrmTools\XrmToolBox\Settings\CrmSvcUtil Ref\Entities.cs" /servicecontextname:"nextgencon365" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /connectionstring:"Url=https://**********.com;Domain=***;UserName=****** ;Password=********" 
CrmSvcUtil : CRM Service Utility [Version 8.2.1.8676]
c 2015 Microsoft Corporation. All rights reserved

CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.ArgumentNullException: Organization cannot be null or empty.
Parameter name: Organization Name
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.ConnectToCrmWebService(String crmConnectionString)
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.CreateOrganizationServiceEndpoint()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: Microsoft.Xrm.Tooling.Connector
Method	: ConnectToCrmWebService
Date	: 10:18:17
Time	: 17-Oct-17
Error	: Organization cannot be null or empty.
Parameter name: Organization Name
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.ConnectToCrmWebService(String crmConnectionString)
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.CreateOrganizationServiceEndpoint()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
======================================================================================================================

Output file was not updated or not found!  C:\Users\Yuval\AppData\Roaming\MscrmTools\XrmToolBox\Settings\CrmSvcUtil Ref\Entities.cs

 Question:
------------
Where this 'Organization' parameter should be defined?
I would expect the 'Organization' parameter to be copied directly from the connection data.
Please advise.

**Comment by daryllabar** [comment]
It should be getting pulled from your connection string.  I'm assuming you're on the latest version and the output error that you have posted has been obfuscated?  /connectionstring:"Url=https://*.com;Domain=;UserName= ;Password=********"

**Comment by yuvalrs** [comment]
I am on the latest version (1.2017.10.10.
That's correct - the output error that you have posted has been obfuscated.
The connected instance version is a localized 1612 (8.2.1.176)

**Comment by daryllabar** [comment]
There are really two options here.  I don't have an IFD to test against.  You can either give me a credentials to login and test with, and I'll be happy to troubleshoot, or you can compare what the command line is that is being used, to what is defined for the [crmsvcutil](https://msdn.microsoft.com/en-us/library/gg327844.aspx?f=255&MSPPError=-2147217396), and tell me what it is, and what it should be.

**Comment by yuvalrs** [comment]
Thanks.

 

I will try the crmsvcutil <https://msdn.microsoft.com/en-us/library/gg327844.aspx?f=255&MSPPError=-2147217396>  directly and provide a well-functioning command line output .

**Comment by yuvalrs** [comment]
This is the correct connection format for IFD:
Url=https://devcrm.vzdev.ch/devcrm;Domain=vzdev;UserName=user@vzdev.ch;Password=pass;AuthType=IFD

Note the organization name is appended to the Url:  https://devcrm.vzdev.ch/devcrm

Appending the organization name (/devcrm) to the Url should probably fix the problem.

**Comment by daryllabar** [comment]
Can you test this version of the EBG?  [DLaB.EarlyBoundGenerator.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/1418316/DLaB.EarlyBoundGenerator.zip)

Should just be able to open your plugins directory and replace the DLaB.EarlyBoundGenerator.dll

**Comment by yuvalrs** [comment]
I tried the new dll - the problem is not fixed yet.

This is the command line output created by the module:

"C:\Users\Yuval\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /namespace:"NGMessage.Plugins" /out:"c:\_Work\NGMessage_v3.1\Packages\NGMessage\Plugins\Entities.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /connectionstring:"Url=https://crmdev.hostserver.com/;Domain=wbx;UserName=user@name.com;Password=pass1word" 

Note: The problem is with the /connectionstring  parameter.

The following command line should work:
"C:\Users\Yuval\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /namespace:"NGMessage.Plugins" /out:"c:\_Work\NGMessage_v3.1\Packages\NGMessage\Plugins\Entities.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /connectionstring:"Url=https://organization.hostserver.com/organization
 Domain=wbx;UserName=user@name.com;Password=pass1word" 

Note the following change in the connectionstring Url:
CURRENT: (WRONG WITH IFD) :          Url=https://organization.hostserver.com/
CORRECT for IFD:                                 Url=https://organization.hostserver.com/organization

Appending the "/organization" should fix the problem 
I have added it manually in the Early Bound Generator module and it works.

Note that the organization name appears twice in the URL.  Url=https://**organization**.hostserver.com/**organization**

Replace the above values with values grabbed from the connection string:
organization  => organization name
hostserver.com = > host server url

**Comment by daryllabar** [comment]
Please look at the XML file that contains your connection strings for the XrmToolBox.  I updated the code to generate the URL to use the WebApplicationUrl.  Does that not have the orgname.domain/orgname format?  If not, is there another setting that does?

**Comment by yuvalrs** [comment]
I tried to edit the connection to the following format:
https://organization.host_server.com/organizations.

The connection XML has the following:
 <WebApplicationUrl>https://organization.host_server.com/</WebApplicationUrl>

 <OriginalUrl>https://organization.host_server.com/organization</OriginalUrl>
  <Organization>organization</Organization>
  <OrganizationUrlName>organization</OrganizationUrlName>

**Comment by daryllabar** [comment]
Does the WebApplicationUrl have the orgname.domain/orgname format? If not, is there another setting that does?

**Comment by yuvalrs** [comment]
OriginalUrl] https://organization.host_server.com/organization [/OriginalUrl]

**Comment by daryllabar** [comment]
Take 2.  Try this one.

[DLaB.EarlyBoundGenerator.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/1427026/DLaB.EarlyBoundGenerator.zip)

**Comment by yuvalrs** [comment]
v2 is still not good.

**This is the actual  connection string in the command line output:**
**/connectionstring:**"Url=https://org_name.host_server.com;Domain=wbx;UserName=user@abc.com;Password=pass1word" 

**This is the expected connection string:**
/connectionstring:"Url=https://org_name.host_server.com**/org_name**;Domain=wbx;UserName=user@abc.com;Password=pass1word"

**Comment by yuvalrs** [comment]
Has anything updated since v2?
The last test was performed by merely copying the v2 dll file to the plugins folder.

Now I noticed the module appeared in the plugin store dialog as updated, therefore also performed install. I tried using the Early Bound Generator again. This time it worked correctly (the connection string composed as expected).

**Comment by daryllabar** [comment]
hmm... so what version of the EBG did it work for you for?  Each version I gave you was a different version...  If you just replaced the dll without restarting the XTB, then it wasn't a valid test.

**Comment by yuvalrs** [comment]
It works with the latest one (v2)
