### ISSUE TITLE
Local to Global Option Set

### ISSUE THREAD

**Issue by WindingGen** [daryllabar/DLaB.Xrm.XrmToolBoxTools#137]
I have a local option set that exists (Countries). This is a long option set and I do not want to recreate it as a global option set manually.

Does this tool allow me to create/update the attribute from a local to global option set without already having a global option set created?
@daryllabar

**Comment by daryllabar** [comment]
The global option set definition must be created first.  It isn't too hard to edit the solution file to copy the values over: https://youtu.be/sVCehUU7_n0
The one the global OptionSets is defined, you can use the tool to "change" the attribute to use the global than the local
