### ISSUE TITLE
Entities / Optionsets created with Early Bound Generator corrupts connection with CrmServiceClient

### ISSUE THREAD

**Issue by NicolasKlaas** [daryllabar/DLaB.Xrm.XrmToolBoxTools#138]
Lately I posted several issues about being unable to connect to my Dynamics environment using CrmServiceClient. I found several things to watch out for (connectionstring with Unique ID of company isntead of company name, using the right SecurityProtocolType and so on), however none of these solutions seem to work. 

So my last try was just to build the project from the ground up. With my new project the connection to my CRM using the same CrmServiceClient and settings suddenly seemed to work.
However, after using the XrmToolBox Early Bound Generator to create my early-bound entities and optionsets (and adding the .cs classes to my project), the connection suddenly failed again. 

Is this issue known or am I simply importing the early-bound entities the wrong way? (installed the latest version of the XrmToolBox --> 1.2018.1.20).

**Comment by daryllabar** [comment]
I'm not sure how or why adding the Early bound entities would prevent you from connecting to CRM.  If your using online 9.0 you'll need to recompile to .net 4.6.2.

If you make a sample app without any EarlyBound entities, and attempt to connect does it work?  If it does, I'd add your entities and retry.

**Comment by NicolasKlaas** [comment]
Project is created in .net 4.7 (got CRM  9.0.0.3172). In my sample the connect works without the EarlyBound entities, after adding them it fails however.

**Comment by daryllabar** [comment]
So if you just reference the .cs files, you can't even do a WhoAmI request?  Or are you attempting to do a CRUD operation?

**Comment by NicolasKlaas** [comment]
Tested both CRUD and a WhoAmI request, both fail simply because the CrmServiceClient object is empty (error returns: `Unable to Login to Dynamics CRMOrganizationServiceProxy` is null)

**Comment by daryllabar** [comment]
And if you remove the earlybound entities from your project, it works just fine?  Hmm... Have you turned on tracing?

```
Microsoft.Xrm.Tooling.Connector.TraceControlSettings.TraceLevel = System.Diagnostics.SourceLevels.All;
Microsoft.Xrm.Tooling.Connector.TraceControlSettings.AddTraceListener(new TextWriterTraceListener("log.txt"));
```

**Comment by daryllabar** [comment]
Did you ever figure out the problem/solution?

**Comment by daryllabar** [comment]
Haven't heard anything in 2 weeks.  I assume you resolved whatever your issue was...
