### ISSUE TITLE
Nuget installation: Unable to resolve dependency 'XrmToolBox'

### ISSUE THREAD

**Issue by Divjyot1** [daryllabar/DLaB.Xrm.XrmToolBoxTools#143]
Dependency https://www.nuget.org/packages/XrmToolBox/ doesn't exist more.

I think this is the new dependency URL https://www.nuget.org/packages/XrmToolBoxPackage/

Thanks

**Comment by daryllabar** [comment]
This isn't a developer dependency, this is a dependency that is used by the XTB to determine what nuget packages are actual plugins that belong in the plugin store.
