### ISSUE TITLE
EarlyBoundGenerator generates classes for excluded actions

### ISSUE THREAD

**Issue by polshgiant** [daryllabar/DLaB.Xrm.XrmToolBoxTools#144]
In my config I exlcuded all actions and several were still generated.  I checked the settings file thinking that the GUI just has a bug where it doesn't record the exclusions properly, but that is not the case; the settings file *does* have exclusions listed for the actions that were still generated.  

Theses are the exclusions in the settings file to the actions that were erroneously created:
Resource Scheduling - Fps Action|Resource Scheduling - Geocode Address|Resource Scheduling - Retrieve Distance Matrix|Resource Scheduling - Retrieve Resource Availability|Load Fact Table (Estimate)|New Invoice (Contract)

They all have a few things in common:
- They're all actions from msdyn_ solutions (note, though, that there are lots of other msdyn_ actions which correctly get excluded from generation)
- They all have non-alphanumeric characters in their display names (note, though, that there are plenty of other actions with hyphens which correctly get excluded from generation)

**Comment by daryllabar** [comment]
Does the logical request name that gets generated in the action match the name in the config?

**Comment by polshgiant** [comment]
Doesn't look like it:
![image](https://user-images.githubusercontent.com/1887185/36901559-3ad28d2a-1ded-11e8-80e5-231dbe53e149.png)
![image](https://user-images.githubusercontent.com/1887185/36901637-716a6c04-1ded-11e8-914c-264ceca9594b.png)

**Comment by daryllabar** [comment]
It should be storing the actual logical name, not the display name.  If you edit the config to be msdyn_LoadFactTableEstimate, does that work?
