### ISSUE TITLE
Cannot connect to D365 v9.0.1.459

### ISSUE THREAD

**Issue by clintolin** [daryllabar/DLaB.Xrm.XrmToolBoxTools#145]
I am using XrmToolBox v1.2018.1.20. 

My dev environment just updated to D365 V9.0.1.459 and when trying to generate classes with Early Bound Generator, it connects, displays organizations, I select one but it just continuously prompts for login. Using other tools such as FetchXML Builder connects and executes just fine. 

![capture](https://user-images.githubusercontent.com/7000083/37115251-854bfa72-2242-11e8-9cfd-fbd5c92a0bc6.PNG)

The log shows "Attempting to login using interactive mode" even though I have logged in to the Dev environment using my saved connection settings.  

Then it shows:

![capture1](https://user-images.githubusercontent.com/7000083/37115263-902ec17c-2242-11e8-9285-0ecf01673817.PNG)

Then it just repeats until finally I push Cancel and it shows "User aborted Login" (of course). 

I can connect to Test, D365 V8.2.2.339 and it works just fine.

The log info is here: 

CRM Authentication Type Detected: OnlineFederation
Executing "C:\Users\cli2022949\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://xxxxx-dev.api.crm.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"Xrm" /out:"C:\Users\clixxxxx\AppData\Roaming\MscrmTools\XrmToolBox\Settings\CrmSvcUtil Ref\Entities.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"CLIxxxxx@xxxxxxx.edu" /password:"**********" 
CrmSvcUtil : CRM Service Utility [Version 8.2.1.8676]
c 2015 Microsoft Corporation. All rights reserved

Unable to Login to Dynamics CRM
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Exception: Connection to CRM is not established. Aborting process.
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: CrmSvcUtil
Method	: LoadMetadata
Date	: 12:35:13 PM
Time	: 3/7/2018
Error	: Connection to CRM is not established. Aborting process.
Stack Trace	: at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)

**Comment by daryllabar** [comment]
What version of the EarlyBoundGenerator are you running?  I'm able to successfully connect and build entities on my v9 Environment.

**Comment by clintolin** [comment]
My bad Daryl, I forgot that I had to update EarlyBoundGenerator separately from XrmToolBox. I was just assuming it was current because Toolbox was current. My bad. I just updated and it works perfectly. Sorry to disturb you. :-)

**Comment by daryllabar** [comment]
No Problem @clintolin.  Just remember that the EarlyBoundGenerator is just a GUI that shells out to the CrmSrvcUtil, so it is one of the few plugins that will make connections outside of of the XrmToolBox, and will it times have to be on the correct version in order to connect.
