### ISSUE TITLE
strong password in Command line sometimes not detected correctly

### ISSUE THREAD

**Issue by dirkr1** [daryllabar/DLaB.Xrm.XrmToolBoxTools#148]
When the password contains special characters which are an end symbol for a command line argument, the password is then cut off by windows. Yesterday I locked me out 4 times because of using the wrong password in this way.
As workaround, the order of the command line arguments to crmsvcutil could be changed. The password should be included before the username in the command line - then the login will at least not be locked by using the wrong password.

As fix the password could be included in quotation marks (additional to changing the command line argument order).

**Comment by daryllabar** [comment]
I'd need to add escape characters in case the password contains quotation marks as well.  Do you know what those are in command line off the top of your head?

**Comment by daryllabar** [comment]
Also, what character is being used that causes this error currently?

**Comment by dirkr1** [comment]
I had a password with ^and / included. I had used a password generator to get a new password.

**Comment by daryllabar** [comment]
I think I may be trying this too hard... Can you test your password in this snippet: http://rextester.com/NESCWO89028
and let me know if you can get it to generate the right connection-string command-line parameter?  Basically if you can create a snipet that correctly handles your password, I can drop it in the EBG Logic.  Remember you'll need to test the results with the /connectionstring: parameter of the crmsrvcutil.  You may have to escape double quotes for the command line using "^"

**Comment by slahn** [comment]
Hi,
I explained how to escape the password in #103:

```
//To handle special characters, enclose in single quotes. If password contains single quotes, they must be doubled.
//https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.connectionstring.aspx
var password = $"'{earlyBoundGeneratorConfig.Password.Replace("'", "''")}'";
```
Would be lovely if this was included so I didn't have to maintain my own fork :)

**Comment by daryllabar** [comment]
Actually, I think the issue is the "^" that's an escape letter on the command line,  Try replacing the dll in your XrmToolBox with this: https://drive.google.com/file/d/1FQZQ_JSfpddw4a8WMcgsuKnvs2N60DNL/view?usp=sharing

**Comment by daryllabar** [comment]
@slahn I'm not seeing that line of code in the source.  Context?

**Comment by slahn** [comment]
Sorry, this was a good while back, when I commented on the other issue.
I rebased against master and made a pull request now - #151 .

**Comment by daryllabar** [comment]
I've implemented @slahn's changes.  Let me know if I need to do anything.
