### ISSUE TITLE
Could not load file or assembly 'DLaB.Xrm, Version=1.0.0.0

### ISSUE THREAD

**Issue by steveculshaw** [daryllabar/DLaB.Xrm.XrmToolBoxTools#15]
Just downloaded latest "Full" from ... https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/releases/tag/v2016.2.6.1
Unblocked the zip and extracted to folder
Ran XrmToolBox, created a new connection to our dev instance of CRM Online
**Opened the Early Bound Generator, and clicked the Entities to Skip ...**

After a bit of time, get error dialog ...

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'DLaB.Xrm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=fbff471681eb6c24' or one of its dependencies. The system cannot find the file specified.
File name: 'DLaB.Xrm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=fbff471681eb6c24'
   at DLaB.XrmToolboxCommon.Extensions.<>c.<ToObjectCollectionArray>b__2_0(EntityMetadata e)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at DLaB.EarlyBoundGenerator.SpecifyEntitiesDialog.LoadEntities(IEnumerable`1 entities)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

I added in a copy of the MsCrmTools.MetadataDocumentGenerator plugin and it successfully brought back a list of the CRM entities

Cheers,
SteveC.

**Comment by daryllabar** [comment]
Did you download the source zip, or the Compiled Plugin zip?  That dll is listed in the Zip file, so make sure you unblock it before unzipping it.

If you downloaded the Source, that dll is on NuGet.

**Comment by steveculshaw** [comment]
Daryl, I unblocked the compiled zip "DLaB.Xrm.XrmToolBoxTools-Full.zip"

Just tried the command line generated by the plugin, which failed

BUT if I changed the CRM URL from the friendly name, to the "orgXXXX" name, as in ... url:"https://orgXXXXXXX.crm4.dynamics.com/XRMServices/2011/Organization.svc" 
the early bound classes were generated!
(Shame it was for every entity though :-( )

**Comment by daryllabar** [comment]
You can specify what entities to skip. in the UI.  It will update the CrmSvcUtil.exe.config, and then it should only create the entities that you want.

**Comment by steveculshaw** [comment]
Daryl,

yeap, I tried that and got the error above

**Comment by daryllabar** [comment]
Ah...  I get the bug now. I was unclear on the steps to recreate it.  I'll fix that if not tonight, tomorrow, and create a pre-release version

**Comment by steveculshaw** [comment]
Many thanks

**Comment by daryllabar** [comment]
If you want something right now, you can use an older version of the Early Bound Generator to create the list of entities you want to skip, and then add that to the Xml file for the newer version.

**Comment by daryllabar** [comment]
Can you give [this version a try](https://drive.google.com/file/d/0B0By9PBv_3cDUFE3TWVncUlMbUU/view?usp=sharing) to see if it resolves your issue before I make a release?

**Comment by daryllabar** [comment]
Can you try [this version](https://drive.google.com/file/d/0B0By9PBv_3cDZlg1LVVhTlR3Rm8/view?usp=sharing)

**Comment by steveculshaw** [comment]
Will do Daryl

On customers sites today, so will have to be tomorrow (UK time)


Cheers,

SteveC.

**Comment by daryllabar** [comment]
Fixed with 2016.2.18.1
