### ISSUE TITLE
Allow EarlyBoundGenerator to update crmsvcutil.exe.config using a configurable path

### ISSUE THREAD

**Issue by altmank** [daryllabar/DLaB.Xrm.XrmToolBoxTools#152]
Hello,

I'd like to keep a version of crmsvcutil.exe with a specific config in our source control and have the EarlyBoundGenerator update that config. Is there a configuration option to allow for this?

**Comment by daryllabar** [comment]
What I normally do is check in the DefaultSettings in Source Control, and setup the Entities, Option Sets, and Actions as relative paths to the settings.xml.  Any new developer would connect to their dev instance, then update the settings path to be the version in source control, and everything else should just work.

If that doesn't work, for you, the settings.xml does have a CrmSvcUtilRelativePath settings so you can change where it is looking for the CrmSvcUtil.  

If you need more help, let me know more details what you're attempting to do.  If you're good, please close the issue.

**Comment by altmank** [comment]
Thanks for your help.
