### ISSUE TITLE
Generated Model.cs cannot find [Entity]State 

### ISSUE THREAD

**Issue by Agure** [daryllabar/DLaB.Xrm.XrmToolBoxTools#156]
I have faced with the same issue as described at: Generated Account.cs Entity cannot find AccountState (StateCodeEnum) #48

I'm using the latest XrmToolbox and I have all updates for plugins. 
I have CRM 2016 OnPrem. 

Tool skips StateCode for each entity. 

Please help to resolve.

**Comment by Agure** [comment]
I've found the reason: Namespace and Service Context Name should be different.
It works for now.

**Comment by daryllabar** [comment]
So it sounds like I need to put a check in to prevent specifying the namespace and xrmContext from being the same value?

**Comment by Agure** [comment]
Hello Daryl,

It would be great!
