### ISSUE TITLE
Could not load file or assembly "Microsoft.Xrm.tooling.Ui.Style"

### ISSUE THREAD

**Issue by umerjaved** [daryllabar/DLaB.Xrm.XrmToolBoxTools#158]
Hi,
I am getting error when generating early bound classes for selected entities. I am connecting to latest version of Dynamics 365 online.  Any idea how this can be resolved? Thanks
![image](https://user-images.githubusercontent.com/16427070/40647140-0b57ca8a-6323-11e8-9500-55ed7796d628.png)

**Comment by daryllabar** [comment]
I had this bug in a previous version of the EBG.  What version are you running?  It's failing to connect via the command line, and attempting to open the ui for manually entering in credentials, but the crmsvcutil is missing some of the SDK ui dlls.

**Comment by umerjaved** [comment]
So the version is v1.2018.1.20. 

Hmm even though i established the connection with the online organisation first before using this tool. Any idea how i can fix the issue?
Thanks
