### ISSUE TITLE
Possible warning about breaking workflows and multi language support

### ISSUE THREAD

**Issue by ChrisAdamsUK** [daryllabar/DLaB.Xrm.XrmToolBoxTools#161]
Hi Guys,

Great plugin, 

It does however break workflows which use the attribute. It would be nice if it gave a warning if it found workflow dependencies, unless it could also fix them :-)

Also iit would be nice if as well as the display name it could allow entry of display names in all languages installed.  My organisation has three languages :-)

Regards
Chris

**Comment by daryllabar** [comment]
So first point on the workflow dependencies.  It is supposed to handle that.  Can you tell me what the dependency was, and how it broke?  

And for your second.  You'd like a way to manage the display name of all of the languages for an attribute?  Currently does it just do English, or your selected language?

**Comment by ChrisAdamsUK** [comment]
Hi Daryl

Thanks for your quick reply 😊

I was previously thinking of creating a similar plugin if one didn’t exist but then found yours that does the job well 😊

I was just having a play around with it on our dev environment.

I had a whole number attribute and a workflow on the entity with a condition step if the attribute equalled 2. I used your plugin to change the attribute type to optionset.

After doing this the condition had lost it’s value parameter, it didn’t even display in the workflow editor (though the workflow was still active).

To be honest I didn’t try and execute the workflow. I’m not sure how you would go about mapping old values to new values, which is why I suggested just a warning 😊


Regarding the languages, this would only be a nice to have as the CRM attribute editor doesn’t even do it (you have to export and import the translations).

Our org is in English, French and Arabic. The editor displays only the display name (in the default language for the org). It would be a nice touch if it could display text boxes for the other languages and also the description.

I will start using this plugin in the future as it’s always a pain when you accidentally create an attribute with the incorrect name or type and need to change it.

I’m sure you could easily do it yourself but I’ve just done a language retrieve in a toolbox plugin so here is the code to make it quicker if you want to do it 😊.
I’ve also attached the resource file I use for mapping the languages 😊

/// <summary>
        /// List of installed languages on the CRM.
        /// </summary>
        private Dictionary<int, string> installedLanguages;


        /// <summary>
        /// Get The languages in the CRM organisation.
        /// </summary>
        private void GetLanguages()
        {
            this.WorkAsync(new WorkAsyncInfo
            {
                Message = "Retrieving languages...",
                Work = (w, e) =>
                {
                    if (installedLanguages == null)
                    {
                        RetrieveAvailableLanguagesRequest request = new RetrieveAvailableLanguagesRequest();
                        RetrieveAvailableLanguagesResponse response = (RetrieveAvailableLanguagesResponse)Service.Execute(request);
                        e.Result = response;
                    }
                },
                PostWorkCallBack = e =>
                {
                    if (e.Result != null)
                    {
                        Dictionary<int, string> languages = JsonConvert.DeserializeObject<Dictionary<int, string>>(Properties.Resources.Countries);
                        installedLanguages = new Dictionary<int, string>();
                        foreach (var language in ((RetrieveAvailableLanguagesResponse)e.Result).LocaleIds)
                        {
                            if (languages.ContainsKey(language))
                            {
                                installedLanguages.Add(language, languages[language]);
                            }
                        }
                    }
                },
                AsyncArgument = null,
                IsCancelable = true,
                MessageWidth = 340,
                MessageHeight = 150
            });
        }


Regards
Chris

**Comment by daryllabar** [comment]
Ah, so it is just doing a straight replace, and you've updated the entity type from a number to an option set, which is an issue.
