### ISSUE TITLE
'Remove Runtime Header Comment' does not work

### ISSUE THREAD

**Issue by khorozhansky** [daryllabar/DLaB.Xrm.XrmToolBoxTools#166]
The system generates header comments even if the 'Remove Runtime Header Comment' checkbox is checked.

**Comment by khorozhansky** [comment]
Yes, that's what I meant, on different dev machines this header might be different and even in different languages)

**Comment by daryllabar** [comment]
Similar to #296

**Comment by daryllabar** [comment]
Next version of the EBGV2 will contain this:
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9728423/f369b4e9-ba09-4a61-a62f-236994cd5cf7)
