### ISSUE TITLE
Where to find .dll for XrmToolBox?

### ISSUE THREAD

**Issue by alen1979** [daryllabar/DLaB.Xrm.XrmToolBoxTools#17]
Hi Daryl

Where can I find the lastet .exe / dll files for the the CRM Early Bound generator ? On Github or Codeplex? I understand the version on Codeplex is outdated.

Many thanks
Alen

**Comment by daryllabar** [comment]
Git Hub: https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/releases
