### ISSUE TITLE
"Created via this command line" still appears after turning off option

### ISSUE THREAD

**Issue by JonathanWacks** [daryllabar/DLaB.Xrm.XrmToolBoxTools#170]
After turning off "Include Command Line In Output", I still get the following line in the comments before the generated class:

// Created via this command line: 

This appears just before the namespace, like this:

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: 
//------------------------------------------------------------------------------

namespace CrmEarlyBound

**Comment by daryllabar** [comment]
I'm assuming the expected behavior would be for "Created via this command line:" to not show up?

**Comment by JonathanWacks** [comment]
Yes - if you're opting not include the command line, I'd prefer not to see that 'intro' line either.

**Comment by daryllabar** [comment]
@JonathanWacks Can you try and download the DLaB.CrmSvcUtilExtensions.dll and replace the dll in the crmsvcutil folder?  https://drive.google.com/file/d/0B0By9PBv_3cDb1QtTU5SblZVaG8/view?usp=sharing
