### ISSUE TITLE
Extension for "Make readonly fields editable"

### ISSUE THREAD

**Issue by ChrissyChan** [daryllabar/DLaB.Xrm.XrmToolBoxTools#174]
Hello,

we would love to see an extension for the generated readonly fields in entities. At the moment it is not possible to generate setters for fields like "ActivityTypeCode" of activitypointer and "FullName" of systemuser.

**Comment by daryllabar** [comment]
I'm assuming this is so you can more easily write LINQ statements?

**Comment by ChrissyChan** [comment]
Yes, that's the main reason. However, we also need to set the values for example to mock our context for unit-tests e.g. FullName = "TestUser". That's why we would be grateful if it works for all readonly fields.

**Comment by daryllabar** [comment]
Good Point.  I'll see what I can do.  For now, you can still update them via the entity["fullname"] = "TestUser".

**Comment by ChrissyChan** [comment]
Thank you very much. We can build a workaround extension via "IsValidForCreate" property in AttributeMetadata for us. However, we can't access the needed class "CodeWriterFilterService" for Entity because it is internal and only accessable via same assembly. Is it somehow possible to write an extension for ICodeWriterFilterService.GenerateAttribute by myself?

**Comment by daryllabar** [comment]
Yes, you can create you're own ICodeWriterFilterService, You'll most likely need to inherit from my version so you can call the base functionsas well.  You'll also need to manually update Settings Xml to include your filter and place the dll in the same folder as the CrmSrvcUtil that you're using.

``` XML
<Argument>
      <SettingType>Entities</SettingType>
      <Name>codewriterfilter</Name>
      <Value>DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions</Value>
</Argument>
```

**Comment by ChrissyChan** [comment]
Thank you. I tried to inherit from your class "CodeWriterFilterService" from "DLaB.CrmSvcUtilExtension.Entity". However, the class is inaccessable due to it's protection level.

**Comment by nickbrandl** [comment]
I'm having issues working with calculated fields on LINQ. As those fields are readonly (even when I select the option "Make Readonly Fields Editable" from the tool) I cannot select which fields I need to retrieve, so I have to retrieve all.

**Comment by daryllabar** [comment]
For you @nickbrandl you can use the AnonymousType Object Constructor: https://stackoverflow.com/a/27624362/227436

**Comment by daryllabar** [comment]
[DLaB.EarlyBoundGenerator.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/2876392/DLaB.EarlyBoundGenerator.zip)

@ChrissyChan would you be willing to test this build?  I've added a MakeAllFieldsEditable option.  I haven't tested it at all, so if it breaks right out of the box, it's probably me.  Just let me know.  It should default to false by default, so you'll need to update it.

**Comment by ChrissyChan** [comment]
@daryllabar I tested it and it works! I added the key-value "MakeAllFieldsEditable" to "True" and all the generated fields have a setter. Thank you very much!
