### ISSUE TITLE
Entities Whitelist not working

### ISSUE THREAD

**Issue by mannybellas** [daryllabar/DLaB.Xrm.XrmToolBoxTools#178]
In version 1.2019.2.12, "Entities Whitelist" does not work.  It generates ALL entities.

the xml is attached (inside the zip)
[DLaB.EarlyBoundGenerator.Odyssey.xml.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/2908855/DLaB.EarlyBoundGenerator.Odyssey.xml.zip)

**Comment by daryllabar** [comment]
I wonder if this is related to #177.  Can you verify for me what version of the `DLaB.CrmSvcUtilExtensions.dll` is in the `Plugins\CrmSvcUtil Ref` folder?

**Comment by mannybellas** [comment]
Hi Daryl,  the version is 1.2018.10.15

**Comment by daryllabar** [comment]
It is the same issue.  For a work around, you can manually copy the correct version from the nuget package as defined in #177

**Comment by mannybellas** [comment]
Thanks, yes that worked.  A clean installation of the plugin also works.  I believe the error occurred having originally just upgraded the plugin via xrmtoolbox.
