### ISSUE TITLE
Output file not generated

### ISSUE THREAD

**Issue by MBeecher** [daryllabar/DLaB.Xrm.XrmToolBoxTools#179]
While trying to generate Entities or OptionSets, I'm getting the following output information and files of 0k:

CRM Authentication Type Detected: OnlineFederation
Executing for OptionSets
Executing "C:\Users\mbeecher\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtilRef\crmsvcutil.exe" /url:"https://wsbtest.api.crm.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"Wsob.Xrm" /out:"C:\Users\mbeecher\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"wsbcrm-migrate@uwprod.onmicrosoft.com" /password:"****************" 
Output file was not updated or not found!  C:\Users\mbeecher\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\OptionSets.cs
Creation Complete!

I've also tried running form the command line (since several posts have suggested that):
C:\Users\mbeecher\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtilRef>crmsvcutil.exe /url:"https://wsbtest.api.crm.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"Wsob.Xrm" /out:"C:\Users\mbeecher\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"wsbcrm-migrate@uwprod.onmicrosoft.com" /password:"*************"
CrmSvcUtil : CRM Service Utility [Version 9.0.0.9369]
c 2017 Microsoft Corporation. All rights reserved

Exiting program with exception: Could not load provider of type 'DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions'
Enable tracing and view the trace files for more information.

---
Looking in the C:\Users\mbeecher\AppData\Roaming\MscrmTools\XrmToolBox\Plugins folder, I only see a DLaB.EarlyBoundGenerator.dll so I'm not sure how the codeCustomization, codeGenerationService and codeWriterFilter parameters find the DLaB.CrmSvcUtilExtensions.dll file (if I'm understanding how those parameters work).

Trying to connect to Dynamics 9 online, using EBG Version 1.2019.2.12 in XrmToolBox v.1.2019.2.32

Thanks in advance! I assume this is just something I haven't configured correctly.

**Comment by daniele-torlai** [comment]
I can confirm the exactly same issue with the exact same versions of XrmToolbox and EBG.
![image](https://user-images.githubusercontent.com/48206919/54222800-6a71d780-44f6-11e9-8715-4a2b54ed16b5.png)

**Comment by daryllabar** [comment]
Can you try deleting the CrmSvcUtil Ref folder in the plugins folder of the XrmToolBox and reinstall the plugin?

**Comment by daryllabar** [comment]
Also try the workaround in #177

**Comment by daniele-torlai** [comment]
The first issue i had was the total absence of the CrmSvcUtil Ref folder under \AppData\Roaming\MscrmTools\XrmToolBox\Plugins path.

I created it manually putting the files extracted from the NuGet package downloaded at [this link](https://www.nuget.org/packages/Microsoft.CrmSdk.CoreTools), as explained in #177.

Are those files correct or there's something missing?

Thanks in advance.

**Comment by MBeecher** [comment]
I was (and after plugin reinstall) also missing the "CrmSvcUtil Ref" folder, so I manually created it and threw in the crmScvUtil I grabbed from Microsoft.CrmSdk.CoreTools (9.0.2.12).

Which NuGet download were you recommending in 177 ?

**Comment by daryllabar** [comment]
The EarlyBoundGenerator nuGet has its own CrmSvcUtil.

Looks like there is a bug with the XrmToolBox not extracting out that folder anymore...  I'll see what I can come up with.  It's a really annoying error since it silently errors...

**Comment by daniele-torlai** [comment]
This is the correct package [link](https://www.nuget.org/packages/DLaB.Xrm.EarlyBoundGenerator/) and copying the CrmSvcUtil Ref folder you can find inside to the right AppData\Roaming\.... location solves the issue.

**Comment by MBeecher** [comment]
Yup... sorry I couldn't figure out the suggestion from 177... that work around is working for me as well.

Thanks so much, and let me know if I can provide any other info to help you debug whatever's going on (though, maybe it's an XrmToolBox issue).

Cheers!

**Comment by 0xced** [comment]
I had the same issue when using the `DLaB.Xrm.EarlyBoundGenerator.Api` package. Here is how I solved it with some MSBuild tricks to copy the `DLaB.CrmSvcUtilExtensions.dll` into the right directory at build time.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <DLaBXrmEarlyBoundGeneratorVersion>1.2022.5.3</DLaBXrmEarlyBoundGeneratorVersion>
  </PropertyGroup>

  <ItemGroup>
    <!--
      Can't use <PackageReference Include="DLaB.Xrm.EarlyBoundGenerator" Version="1.2022.5.3" /> because it fails with this error:
      [NU1202] Package DLaB.Xrm.EarlyBoundGenerator 1.2022.5.3 is not compatible with net48 (.NETFramework,Version=v4.8). Package DLaB.Xrm.EarlyBoundGenerator 1.2022.5.3 does not support any target frameworks.
      Since this package is needed only to copy the missing DLaB.CrmSvcUtilExtensions.dll file, PackageDownload is used instead of PackageReference.
    -->
    <PackageReference Include="DLaB.Xrm.EarlyBoundGenerator.Api" Version="$(DLaBXrmEarlyBoundGeneratorVersion)" />
    <PackageDownload Include="DLaB.Xrm.EarlyBoundGenerator" Version="[$(DLaBXrmEarlyBoundGeneratorVersion)]" />
    <!--
      Copy the DLaB.CrmSvcUtilExtensions.dll into the DLaB.EarlyBoundGenerator directory
      If the build fails in Rider with [MSB3030] Could not copy the file "$(NuGetPackageRoot)\DLaB.Xrm.EarlyBoundGenerator\1.2022.5.3\lib\net462\plugins\DLaB.EarlyBoundGenerator\DLaB.CrmSvcUtilExtensions.dll" because it was not found.
      Tools -> NuGet -> NuGet Restore
    -->
    <None Include="$([System.IO.Path]::Combine($(NuGetPackageRoot),'DLaB.Xrm.EarlyBoundGenerator',$(DLaBXrmEarlyBoundGeneratorVersion),'lib','net462','plugins','DLaB.EarlyBoundGenerator','DLaB.CrmSvcUtilExtensions.dll'))">
      <LinkBase>DLaB.EarlyBoundGenerator</LinkBase>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```
