### ISSUE TITLE
Is it possible to modify the Sort Order Of Options Sets, instead of alphabetical, to use the order that is currently in crm??

### ISSUE THREAD

**Issue by mleitaoCenero** [daryllabar/DLaB.Xrm.XrmToolBoxTools#183]

**Comment by mleitaoCenero** [comment]
Is it possible to modify the Sort Order of Option Sets, instead of the default alphabetical, instead use the order that is currently in crm?

**Comment by daryllabar** [comment]
Decided you didn't want this?

**Comment by mleitaoCenero** [comment]
I did want to ask but when I submitted my request the ticket closed automatically? Not sure why. But yes I do want this, if you have an answer or if you could reopen.
Thanks
Michael

**Comment by daryllabar** [comment]
I previously explicitly put in the change for a sort order by name of the OptionSet.  Any reason that you are wanting to sort by the numerical value?

**Comment by mleitaoCenero** [comment]
The reason, I would like it is because the I have some option sets that are being used as a stage in some places, and the request was to sort the options in stage order

**Comment by daryllabar** [comment]
You just need to do a metadata request and retrieve the order from there.  How is sorting them in the C# file going to help ?

**Comment by mleitaoCenero** [comment]
Sorting in the C# helps me because I'm exporting the Options Sets and then using EnumDropDownList in an mvc app.

**Comment by daryllabar** [comment]
Can you define exporting?  Does your MVC app not connect to CRM?  If so, it should be doing a metadata request in the app itself, not relying on some hard coded configuration.  If not, I could potentially see if being useful to add an attribute to each enum value with the order, and the display value of the enum.  But ideally, your MVC app should be making a call to CRM to get the metadata for the optionset so if someone changes the order in CRM, you don't have to recompile and redeploy.

**Comment by mleitaoCenero** [comment]
I will try to work it out by making a metadata request as you have suggeested. Thanks a lot for the quick responses
