### ISSUE TITLE
cannot connect to MFA instance on the latest version of D365 v9 with april 2019 updates initialised

### ISSUE THREAD

**Issue by bennyboy23** [daryllabar/DLaB.Xrm.XrmToolBoxTools#185]
When attempting to create earlybound classes, the service cannot connect with a MFA instance and continues to attempt to display the CRM login control.
I presume that the svcutil uses the older crm assemblies for logging in?

**Comment by daryllabar** [comment]
They are fairly up to date.  Unfortunately if you generate everything, the login control will pop up 3 times, once for Entities, once for Option Sets, and once for Actions.  Could it be that it is popping up these three times and you are thinking that it is an infinite loop?

**Comment by bennyboy23** [comment]
Hi Daryl,
Thanks for the swift response! I only clicked "create entities" and it gives me an error for the login request.
Source	: Not Provided
Method	: Not Provided
Date	: 18/03/2019
Time	: 10:10:25
Error	: You don't have permission to access any of the organizations in the Microsoft Dynamics CRM Online region that you specified. If you're not sure which region your organization resides in, choose "Don't know" for the CRM region and try again. Otherwise check with your CRM administrator.
Stack Trace	: Not Provided
![image](https://user-images.githubusercontent.com/6200604/54528655-7be33580-4975-11e9-9d29-894afaef81c0.png)

It doesn't prompt me for any MFA prompts.

**Comment by daryllabar** [comment]
Any chance you are using a Delegated admin account?  Can you use the Plug-in Registration tool to login to the org?  If the login control pops up, it means my hack to create the connecting string failed and it is doing the standard interactive login control with the CrmSvcUtil.  By default this is located in the XTB's plugin folder, and then in a sub folder for that, if you want to check the version.

**Comment by bennyboy23** [comment]
I am using my work account with a system administrator role in d365. I can use the latest Plug-in Registration tool from nuget and login to dynamics 365. I am able to use the latest version of svcutil with /iteractivelogin and generate the full fat earlybound file.
Would it work if I simply update the local svcutil files for your plugin with the ones from nuget?

**Comment by daryllabar** [comment]
Yep.. Although I just updated the tool to use the latest.  Feel free to get latest in the XTB Plugin Store.

**Comment by bennyboy23** [comment]
You're an absolute star Daryl! I'll give it a test tomorrow when at work and then close if its resolved.
Thanks

**Comment by daryllabar** [comment]
@bennyboy23 it takes two to tangle.  I wouldn't have known about the issue if you wouldn't have taken the time to submit an issue!

**Comment by Jappinen** [comment]
We are facing the same issue even with this latest version 1.2019.3.17, MFA enabled and region is EMEA. Changing the region and/or including username+password under the Advanced section doesn't seem to change anything. I've included a log of the failed login attempts.

The version that we are currently using that works is 1.2019.2.12.
[earlyboundlog.txt](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/2982056/earlyboundlog.txt)

**Comment by daryllabar** [comment]
So the 1.2019.2.12 version works?  Can you attempt to use the CrmSvcUtil without any of my /DLaB services options in the Command line, and verify if you can connect?  Ideally, you'd also try the latest version of the SDK from NuGet as well.  Just trying to figure out if I've done something wrong, of if there is a bug in the SDK for the CrmSvcUtil.

Also:
In the Sources Section of the config for the crmsvcutil:

Add the following Source-

``` XML
<source name="Microsoft.IdentityModel.Clients.ActiveDirectory" switchName="Microsoft.IdentityModel.Clients.ActiveDirectory" switchType="System.Diagnostics.SourceSwitch">
  <listeners>
    <add name="console" type="System.Diagnostics.DefaultTraceListener" />
    <remove name="Default" />
    <add name="ADALListener" />
  </listeners>
</source>
```
 

In the Switches section Add the following switch:

``` XML
<add name="Microsoft.IdentityModel.Clients.ActiveDirectory" value="Verbose" />
```
 

And in the listeners section:

``` XML
<add name="ADALListener"
    type="Microsoft.Xrm.Tooling.Connector.DynamicsFileLogTraceListener, Microsoft.Xrm.Tooling.Connector"
    BaseFileName="ADAL"
    Location="LocalUserApplicationDirectory" MaxFileSize="52428800"/>
 ```

This will capture ADAL logs and let us see where the breakdown is occurring,

The issue may appear there.

**Comment by bennyboy23** [comment]
Hi Daryl,
It is now correctly asking me for my MFA part but I am still unable to connect.
`Source	: Not Provided
Method	: Not Provided
Date	: 20-Mar-19
Time	: 10:12:37 AM
Error	: You don't have permission to access any of the organizations in the Microsoft Dynamics CRM Online region that you specified. If you're not sure which region your organization resides in, choose "Don't know" for the CRM region and try again. Otherwise check with your CRM administrator.
Stack Trace	: Not Provided
======================================================================================================================

Source	: Not Provided
Method	: Not Provided
Date	: 20-Mar-19
Time	: 10:13:07 AM
Error	: You don't have permission to access any of the organizations in the Microsoft Dynamics CRM Online region that you specified. If you're not sure which region your organization resides in, choose "Don't know" for the CRM region and try again. Otherwise check with your CRM administrator.
Stack Trace	: Not Provided
======================================================================================================================
`

**Comment by daryllabar** [comment]
Can you post the CrmSvcUtil.exe.config?

**Comment by Jappinen** [comment]
The ADAL log didn't reveal much of anything. However, replacing the XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\Newtonsoft.Json.dll with the version Microsoft uses in their CoreTools package (6.0.8.18111), the MFA login works.

**Comment by daryllabar** [comment]
I've updated a new version with the correct version of the Newtonsoft.Json file.  Can you update and try again @bennyboy23?

**Comment by daryllabar** [comment]
I'll assume that this has resolved the problem.  If the latest version doesn't work, please reopen.
