### ISSUE TITLE
Add option Language in order to select C# or VB file

### ISSUE THREAD

**Issue by marcesepu** [daryllabar/DLaB.Xrm.XrmToolBoxTools#187]
Could be posible add the option Language in order to generate Early Bound File for Visual Basic??

Option: 
language | l | The language to generate the code in. This can be either “CS” or “VB”. The default value is “CS”.

Regards

**Comment by daryllabar** [comment]
So... this is a lot hard than it seems.  On one hand it involves just switching the CodeDom to output to VB, that's simple.  The hard part, is that there are a lot of C# only features that I take advantage of, and inject into the CodeDom, so basically switching to VB would turn off a lot of other features and require a significant amount of work on my part.  I'd happily accept a pull request with a working feature of it though, but my guess, is that it will be way easier for you to just put all of your Entities into a separate C# project, and then reference it form your .net projects.  You can mix and match C# and VB.net in the same solution.
