### ISSUE TITLE
UX or human error. Cant create new solution from solution accelerator

### ISSUE THREAD

**Issue by Burmeister** [daryllabar/DLaB.Xrm.XrmToolBoxTools#191]
Cool tool!
When i select Add to existing solution - No. i expect to be able to select a folder where my new project will be created. It could be that i am doing this the wrong way but when i select a location i cant because the file doesnt exist.
![image](https://user-images.githubusercontent.com/12302053/57618544-087c2f80-7584-11e9-9e6b-cf32113137f6.png)
I was told by @rappen to share my experiences which i love to.

**Comment by Burmeister** [comment]
I solved this by pasting the path instead of navigating to it.

**Comment by daryllabar** [comment]
Yeah, I'm just using the OOB Open File dialog, which doesn't really play well when trying to select a file that doesn't exist.  Glad to hear you figured it out.  Would love to hear any feedback you have, and anything that was confusing that I could change.  Feel free to hit me up on Twitter or Gitter or whatever.

**Comment by rappen** [comment]
Perhaps use a `FolderBrowserDialog` instead?

![image](https://user-images.githubusercontent.com/2572253/57676598-28176480-7625-11e9-99ca-1018c50c7ff3.png)

https://github.com/rappen/LateboundConstantsGenerator/blob/master/LateboundConstantGenerator/LCG.cs#L151

**Comment by daryllabar** [comment]
I hate it in that you can't select paste in a part of the path, which I find super annoying at times.

**Comment by rappen** [comment]
Understand, but you can if you have a field for it too, like in my pic 😊

**Comment by daryllabar** [comment]
It also doesn't have your shortcuts and stuff... but yes, I probably need to switch to it...
