### ISSUE TITLE
I Want To dropdown is editable

### ISSUE THREAD

**Issue by rappen** [daryllabar/DLaB.Xrm.XrmToolBoxTools#194]
I think the dropdowntype needs to be changed, because the tool does not do what I want it to do all the time.

![image](https://user-images.githubusercontent.com/2572253/58476593-837f4180-8151-11e9-9b15-52e5d9a52ea8.png)

**Comment by daryllabar** [comment]
Stop shooting yourself in the foot!  ;)

I'm not going to make a new build just for this, but it's checked in.

**Comment by rappen** [comment]
Good enough for me! :)
