### ISSUE TITLE
Selecting name for New Solution is tricky

### ISSUE THREAD

**Issue by rappen** [daryllabar/DLaB.Xrm.XrmToolBoxTools#195]
You have to manually type the solution file name.
https://www.screencast.com/t/T1fuky6o2js

Setting the `FileMustExist` property (or something like that) on the FileOpenDialog to `False` should solve that.

**Comment by rappen** [comment]
Related to #191, forgot about that one but now proposed a better solution :)

**Comment by daryllabar** [comment]
Actually went a slightly different approach, but seems to work pretty well.

**Comment by rappen** [comment]
Was it something you did now, or did you just close it now after five years without me pushing on it? 😉

**Comment by daryllabar** [comment]
I updated it recently to do SDK style projects and as a part of that, I changed this.  Hopefully you approve.  Still haven't fixed your namespace issue though ;(
