### ISSUE TITLE
Old packages installed

### ISSUE THREAD

**Issue by rappen** [daryllabar/DLaB.Xrm.XrmToolBoxTools#197]
During solution setup, I selected SDK 9.0.2.12, but the projects reference 9.0.2.4.
Also the DLaB.Xrm.Source are installed with 2.3.0.2 (plugin) and 2.3.0.3 (workflow) although latest is 3.0.0.
Similar issue for DLaB.Common.Source and DLaB.Xrm.Workflow.Source.

**Comment by daryllabar** [comment]
I believe this has been resolved.
