### ISSUE TITLE
Error generating Entities

### ISSUE THREAD

**Issue by Tjelum** [daryllabar/DLaB.Xrm.XrmToolBoxTools#198]
Running into an issue identical to [#118](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues/118)

Using XrmToolbox Version: 1.2019.6.33
Using Early Bound Generator Version: 1.2019.5.17

I was attempting to generate OptionSet.cs and Entities.cs using the Early Bound Generator in XrmToolbox and both failed with the following error message:

CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.ServiceModel.Dispatcher.NetDispatcherFaultException: The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://schemas.microsoft.com/xrm/2011/Contracts/Services:ExecuteResult. The InnerException message was 'Error in line 16972 position 6028043. Element 'http://schemas.microsoft.com/xrm/2011/Metadata:AttributeMetadata' contains data from a type that maps to the name 'http://schemas.microsoft.com/xrm/9.0/Metadata:FileAttributeMetadata'. The deserializer has no knowledge of any type that maps to this name. Consider changing the implementation of the ResolveName method on your DataContractResolver to return a non-null value for name 'FileAttributeMetadata' and namespace 'http://schemas.microsoft.com/xrm/9.0/Metadata'.'. Please see InnerException for more details. ---> System.Runtime.Serialization.SerializationException: Error in line 16972 position 6028043. Element 'http://schemas.microsoft.com/xrm/2011/Metadata:AttributeMetadata' contains data from a type that maps to the name 'http://schemas.microsoft.com/xrm/9.0/Metadata:FileAttributeMetadata'. The deserializer has no knowledge of any type that maps to this name. Consider changing the implementation of the ResolveName method on your DataContractResolver to return a non-null value for name 'FileAttributeMetadata' and namespace 'http://schemas.microsoft.com/xrm/9.0/Metadata'.

This led me to update to the latest version of CrmSvcUtil (version 9.0.3.4). The files from this NuGet package were copied to:

C:\Users[user_name]\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator

After doing this I was able to generate the OptionSet.cs without error but was still unable to generate the Entities.cs with the following error message:

Ensuring Context File is Accessible
Writing file Entities.cs to C:\Users[user_name]\AppData\Local\Temp\tmp4257.tmp
System.IO.FileLoadException: Could not load file or assembly 'CrmSvcUtil, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'CrmSvcUtil, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
at DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
at Microsoft.Crm.Services.Utility.CodeGenerationService.WriteFile(String outputFile, String language, CodeNamespace codenamespace, ServiceProvider serviceProvider)
at Microsoft.Crm.Services.Utility.CodeGenerationService.Microsoft.Crm.Services.Utility.ICodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)

**Comment by daryllabar** [comment]
Have you tried deleting the Plugins\DLaB.EarlyBoundGenerator folder and the plugins\DLaB.EarlyBoundGenerator.dll and reinstalling the plugin to see if it resolved your issue?  What version of CRM are you connecting to?

**Comment by jtoniolo** [comment]
After removing and reinstalling it works. I will let Tom (Tjelum) know. Thanks.
