### ISSUE TITLE
Error when trying to create OptionSets.cs

### ISSUE THREAD

**Issue by alen1979** [daryllabar/DLaB.Xrm.XrmToolBoxTools#20]
Hi Daryl

I installed your plugin in the XRM Toolbox. When I try to generate the OptionSet.cs I get an error message.

**Output file was not updated or not found!  C:\XrmToolBox\Plugins\CrmSvcUtil Ref\OptionSets.cs**

See full output below:

When I tried to run your plugin the first time there was a warning regarding my .NET framework. I had to update it. I installed version 4.6. Is this supported at all?

Many thanks
Alen

CRM Authentication Type Detected: ActiveDirectory
Executing "C:\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /namespace:"SGAM2.AgreementRequest" /out:"C:\XrmToolBox\Plugins\CrmSvcUtil Ref\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CreateOptionSetEnums,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" 
CrmSvcUtil : CRM Service Utility [Version 8.0.0.7134]
¸ 2015 Microsoft Corporation. All rights reserved

Options:
 /nologo
  Suppresses the banner.

 /language:<language>
  The language to use for the generated proxy code.  This can be either 'CS' or 'VB'.  The default language is 'CS'.  Short form is '/l:'.

 /url:<url>
  A url or path to the SDK endpoint to contact for metadata.

 /out:<filename>
  The filename for the generated proxy code.  Short form is '/o:'.

 /namespace:<namespace>
  The namespace for the generated proxy code.  The default namespace is the global namespace.  Short form is '/n:'.

 /interactivelogin:
  Presents a login dialog to loginto the service with, if passed all other connect info is ignored.  Short form is '/il:'.

 /connectionstring:
  Connection String to use when connecting to CRM. If provided, all other connect info is ignored.  Short form is '/connstr:'.

 /username:<username>
  Username to use when connecting to the server for authentication.  Short form is '/u:'.

 /password:<password>
  Password to use when connecting to the server for authentication.  Short form is '/p:'.

 /domain:<domain>
  Domain to authenticate against when connecting to the server.  Short form is '/d:'.

 /serviceContextName:<service context name>
  The name for the generated service context. If a value is passed in, it will be used for the Service Context.  If not, no Service Context will be generated

 /help
  Show this usage message.  Short form is '/?'.

 /generateActions
  Generate wrapper classes for custom actions  Short form is '/a'.

 /deviceid:<deviceid>
  Device ID to use when connecting to the online server for authentication.  Short form is '/di:'.

 /devicepassword:<devicepassword>
  Device Password to use when connecting to the online server for authentication.  Short form is '/dp:'.

Example:
crmsvcutil.exe /url:http://localhost/Organization1/XRMServices/2011/Organization.svc /out:GeneratedCode.cs

Output file was not updated or not found!  C:\XrmToolBox\Plugins\CrmSvcUtil Ref\OptionSets.cs

**Comment by daryllabar** [comment]
It didn't generate a connection string.   Are you using the latest pre release?

**Comment by daryllabar** [comment]
Let me know if this is still an issue.
