### ISSUE TITLE
Early Bound Generator : Entities prefix black list

### ISSUE THREAD

**Issue by MscrmTools** [daryllabar/DLaB.Xrm.XrmToolBoxTools#200]
I would like to be able to specify a list of prefix I don't want in generated entities.

For example, I would like to avoid generating all entities starting with msdyn_ or li_

That could be an additional setting.

**Comment by daryllabar** [comment]
Does this not do it for yah?

![image](https://user-images.githubusercontent.com/9728423/62305884-c9f16500-b44e-11e9-8750-81457bfc22a4.png)

**Comment by MscrmTools** [comment]
Crap! Did not see it
