### ISSUE TITLE
Add option to clobber folder if "Generate One File Per Action/Entity/Option Set" used

### ISSUE THREAD

**Issue by filcole** [daryllabar/DLaB.Xrm.XrmToolBoxTools#202]
When using any of the "Generate One File Per Action/Entity/OptionSet" options if an action/entity/optionset is removed from the configuration so it no longer generates it still persists in the output folder.

An additional configuration flag that deletes the folder would be good, this will ensure that stale early bound classes are not present at the end of the generation.

**Comment by daryllabar** [comment]
So show the option if "generate a file per class" is selected.  And if it is, delete all files in the folder?  I can see that being useful.  Not sure I want to delete the entire folder itself, in case someone wants to nest extension files in a sub folder.

**Comment by filcole** [comment]
True, perhaps the whole folder doesn't need to be deleted, instead removing any existing .cs files would do the trick.  Does this even need to be a configuration option, could it be the default behaviour if "generate a file per class" is selected?

**Comment by daryllabar** [comment]
I don't like the thought of automatically deleting files.

**Comment by daryllabar** [comment]
This is my first stab.  I've done 0 testing on it, but you can feel free to try it.  just look for "Delete Files From Output Folders".  I'd do it myself but have a presentation in a few hours that I don't want to mess up ;)

[DLaB.EarlyBoundGenerator.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/3612950/DLaB.EarlyBoundGenerator.zip)

**Comment by daryllabar** [comment]
Sorry @filcole did that version work for you?  Haven't had a chance to test it.
