### ISSUE TITLE
Early Bound Generator: Generated entities with more constructors

### ISSUE THREAD

**Issue by maeg02** [daryllabar/DLaB.Xrm.XrmToolBoxTools#204]
using alt keys is great, and having the ability to create base class Entity with the constructs that are available there would speed up the implementation
would it be possible to add some constructors to the tool to do something like this:

`
[System.Diagnostics.DebuggerNonUserCode()]
public <generatedentity>(System.Guid id) :
	base(EntityLogicalName, id)
{
}

[System.Diagnostics.DebuggerNonUserCode()]
public <generatedentity>(KeyAttributeCollection keyAttributes):
	base(EntityLogicalName, keyAttributes)
{
}

[System.Diagnostics.DebuggerNonUserCode()]
public <generatedentity>(string keyName, object keyValue) :
	base(EntityLogicalName, keyName, keyValue)
{
}
`

Then it’s easy  to leverage upsert calls to CRM.
May I submit a PR to do just this?

**Comment by daryllabar** [comment]
Totally!  As long as none of them break existing constructor calls.  I'm 95% sure it won't.

So public (string keyName, object keyValue) doesn't require a cast with public (string logicalName, Guid id) and I don't think it will since I don't think you can have a key value that is a Guid, and the compiler will continue to favor the Guid constructor over the object overload.

**Comment by maeg02** [comment]
the list is pretty much straight copy from Microsoft.Xrm.Sdk.Entity, (dropping known string entityName) so if it works for Microsoft it should work.

as I have understood: 
public <generatedentity>(string keyName, object keyValue) 
will not be able to override new Entity(string entityName, Guid id)
because constructors cannot be used in inheritance.

so 
public <generatedentity>(string keyName, object keyValue) 
refers to the Alt-keyName and Alt-keyValue
Rights?

Anyway I will make a suggestion for you so we have some actual code do discuss :)
Then if its possible I will make some tests...

**Comment by maeg02** [comment]
Lol, I'm just so lost at times. Today I thought, let's take a swing at this, and then I noticed that you do not generate anything here, its all in the CrmSvcUtil, perhaps its better to search for help over there instead. Meanwhile, do you know a way to make a partial class that has additional constructors that uses base class constructors ? That was my second option but I cannot figure it out...
