### ISSUE TITLE
How can I configure EarlyBoundGenerator to use older version of the SDK?

### ISSUE THREAD

**Issue by schnitty** [daryllabar/DLaB.Xrm.XrmToolBoxTools#208]
The current version uses v9 of the SDK for code generation.  I have a client who is on an older version Version 1612 (8.2.8.15) on premise.  I want to make sure tha the code generated is compatible.
Is it possible to configure the tool to use a different version of crmsvcutil?  I've tried a few different ways of doing but invariably get an exception as the code gen expects version 9.

Does it matter?  Will the classes that are generated still work perfectly fine with 8.2.8.15?

Thanks for your help.

**Comment by daryllabar** [comment]
You can choose the path to your own crmsvcutil if you'd like, but there is no dependency defined generated code to a CRM version.  Microsoft does a lot of work to make sure their tools are backwards compatible, and we all get to take advantage of that.  

So to answer your question, no, it doesn't matter.  The classes that are generated will still work perfectly fine with 8.2.8.15 (Or V6.X or V5.X)
