### ISSUE TITLE
Option sets not contains all enums

### ISSUE THREAD

**Issue by rafalp-dev** [daryllabar/DLaB.Xrm.XrmToolBoxTools#209]
Hi,

When I create Option Sets, output file not contains e.g. AccountState or ServiceAppointmentState. Why?
My Option Sets Blacklist is empty.
My Early Bound Generator version is 1.2019.10.27.

**Comment by daryllabar** [comment]
I can't remember off the top of my head.  For some reason either the State or the status is generated in the same class as the entity.  Have you checked if it is generated in the entity class?

**Comment by rafalp-dev** [comment]
Thanks for yours answer.
I checked, these enums are generated in the entity class. 
So, I understand the only way get enums is copy them each time from entity class?

**Comment by daryllabar** [comment]
Umm... What's the problem with them being generated in the entity class, besides our OCD desires?

**Comment by rafalp-dev** [comment]
In my project, I don't use entity class. I use only Option Sets generated to one file.
I resolved my problem by copied only required enums from entities file to another file, which will not be overwritten during generating Opion Sets.
