### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by mathiasbl** [daryllabar/DLaB.Xrm.XrmToolBoxTools#210]
Hello,

I was looking into running your Early Bound Generator as a CLI command. You provide an example with PowerShell but you lose all features inside the EarlyBoundGeneratorConfig. 
It would be nice to have a CLI around the 'Logic' Class so we can still keep using the config file and all it's features.

https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/blob/acfcc974ba2cf898fd55148c4b39a8bd449d66f8/DLaB.EarlyBoundGenerator.Logic/Logic.cs#L15

**Comment by daryllabar** [comment]
I'm confused.  It is designed so you use the UI to create your config.  After that you can just run the command line if you'd like, utilizing the config created by the UI.  Not sure why you'd want a command line to create the config.

**Comment by mathiasbl** [comment]
Sorry, maybe I wasn't clear enough.

I don't want to create the config file. 
In the Logic class there's 'logic' to put your custom config settings into the app.config of the CrmSvcUtil. There's no CLI around this fuctionality. 

I can run CrmSvcUtil and pass your extensions but there's no way to pass your custom config file. This fuctionality is in your 'Logic class'.

I want to run a CLI for example:
earlyboundgenerator.exe /pathtoconfigfile:'C:\xxxx\DLaB.EarlyBoundGenerator.DefaultSettings.xml' /interactivemode
which then runs the CrmSvcUtil with the necessary arguments and extensions.

**Comment by daryllabar** [comment]
I still feel like you're doing it wrong.  The EBG UI exists solely to configure the config file and generate the command line to the CrmSvcUtil.  If you'd to create your own methodology for populating the config file, you can use the [EarlyBoundGenerator API](https://www.nuget.org/packages/DLaB.Xrm.EarlyBoundGenerator.Api/) nuget files to do that. 

So either you want to update the Config file (which can either be done by hand, use the EBG UI to do this, or if you want to create your own custom program to generate the config, use the API package), or generate the entities (which can be done via the UI, or once it's done once via the UI, it gives the command line to perform the action, so just use that.)

I'm not seeing where your use case fits in.

**Comment by daryllabar** [comment]
I believe this is already solved, although it could stand to be documented better.
