### ISSUE TITLE
DateTime Convert from Time Zone Independent back to User Local

### ISSUE THREAD

**Issue by stepnknight** [daryllabar/DLaB.Xrm.XrmToolBoxTools#211]
Hello,

Great tool!  Wondering if it's possible to add the ability to convert a Date/Time field from Time Zone Independent to User Local?

**Comment by daryllabar** [comment]
Not in the tool, but you could manually go through and create the field yourself, use the tool to migrate all of the forms/views/etc.  Of course I do take pull requests, so if you have someone that is willing to edit the app, I'd be happy!
