### ISSUE TITLE
Record counter not working

### ISSUE THREAD

**Issue by juricav** [daryllabar/DLaB.Xrm.XrmToolBoxTools#212]
Hi, there's a minor bug with a record count when there are more than 50 000 records.
It shows 50 000 regardless but continues copying.
[screenshot](https://imgur.com/SaNtlKn)

Version 1.2019.3.22

**Comment by daryllabar** [comment]
Wow.  You waited for it to copy over nearly a 100k records?  Next time I'd suggest using another tool to copy the data to get it done in a sane amount of time.
