### ISSUE TITLE
[EarlyBoundGenerator] Change <EntityWhiteList> from pipe-separated to separate elements.

### ISSUE THREAD

**Issue by filcole** [daryllabar/DLaB.Xrm.XrmToolBoxTools#213]
In the earlyboundgenerator config XML, it's difficult to compare/diff a long list of pipe separated entity names.  It would be easier to diff if each entity was on a separate line, maybe in a child XML element. e.g.

```xml
<EntityWhilteList>account|contact|incident</EntityWhiteList>
```

have

```xml
<EntityWhilteList>
  <Entity>account</Entity>
  <Entity>contact</Entity>
  <Entity>incident</Entity>
</EntityWhiteList>
```

**Comment by daryllabar** [comment]
This is a good point that is an annoyance.  I'm wondering if I could just newline the Pipes to it would be forward compatible?  Don't know when I will get around to it, but I'm in favor of this idea being resolved.
