### ISSUE TITLE
Settings file not being picked up

### ISSUE THREAD

**Issue by sniarn** [daryllabar/DLaB.Xrm.XrmToolBoxTools#215]
According to the Wiki, the settings file should be placed alongside crmsvcutil.exe in order to be picked up. This does not seem to work. I tried naming the file both `DLaB.EarlyBoundGenerator.DefaultSettings.xml` as well as `DLaB.EarlyBoundGenerator.Settings.xml`. I'm running this from a PowerShell script:

```powershell
$currentDir=Get-Location
Set-Location $PSScriptRoot
$url=$Server + '/' + $Organisation + '/XRMServices/2011/Organization.svc'
$crmSvcUtil = Join-Path -Path $currentDir -ChildPath "..\..\packages\DLaB.Xrm.EarlyBoundGenerator.Api.1.2019.8.22\content\bin\DLaB.EarlyBoundGenerator\CrmSvcUtil.exe"
$params='/url:' + $url +
        ' /domain:' + $Domain +
        ' /username:' + $Username +
        ' /password:' + $Password +
        ' /out:OptionSets.cs' +
        ' /namespace:' + $Namespace +
        ' /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions"' +
        ' /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions"' +
        ' /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions"' +
        ' /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions"' +
        ' /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions"' +
        ' /nologo'
Invoke-Expression "& '$crmSvcUtil' $params"
```
Is this a bug or am I not placing the settings file in the correct folder?

**Comment by sniarn** [comment]
The Wiki is not clear on how this is supposed to work. My goal is:

1. Generate a settings file using the UI.
2. Commit the settings file to Git.
3. Run a PowerShell script whenever I change the data model in CRM. This script calls crmsvcutil (which I have obtained by installing the DLaB.Xrm.EarlyBoundGenerator.Api NuGet package) and generates the files according to the settings file.

I managed to get it working by copying the `crmsvcutil.exe.config` file from the folder `C:\Users\mlk\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator` and placing the file in the folder where my NuGet package is located. This I can automate, but seems cumbersome. Am I misunderstanding how this is supposed to work?

**Comment by daryllabar** [comment]
The settings file is just used to populate the UI of the GUI.   Then the tool generates the CrmSvcUtil.exe.config , and then shells out the command line call for creating the entities, the option sets, and the actions.

My assumption for the use of the tool for those that wanted it to be a part of their build process was to use the XTB GUI once to generate the settings file and the .config, then check the settings file into source control so you could run the XTB GUI again whenever you wanted to tweak the config.  Also check in the folder containing the CrmSvcUtil and all of its files.  Then the build pipeline would download that folder, and run all three command line calls to generate the Earlybound files.

Does that make sense?

The API NuGet project is just in case you have your own tool that you want to generate the early bound types from, like Scott Durow's Sparkle framework.  So you could populate the POCO objects however you'd like, for generating the settings file.

**Comment by sniarn** [comment]
>  Also check in the folder containing the CrmSvcUtil and all of its files.

I see. I normally shy away from committing binaries to a repo. But that might just be what I end up doing because it seems like the easiest solution for me right now. Thanks for replying so fast.

**Comment by daryllabar** [comment]
@sniarn If you'd rather download the exe to run from Nuget Rather than put it in your source control, feel free, you'll just need to make sure you copy the checked in CrmSvcUtil.exe.config to the Nuget Extract location before running the command line.

Before I close this, suggestions on making the wiki clearer?

**Comment by sniarn** [comment]
I suggest a section in the Wiki about how to use `crmsvcutil.exe` with just the `App.config` file. I suspect that some (such as myself) will want to manually edit that file and forgo the UI entirely.

**Comment by daryllabar** [comment]
@sniarn Hows this? https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/Integrating-The-Early-Bound-Generator-Into-Your-Build-Pipeline

**Comment by sniarn** [comment]
Much better. Thanks.
