### ISSUE TITLE
[EarlyBoundGenerator] Add option to remove EntityTypeCode constant

### ISSUE THREAD

**Issue by filcole** [daryllabar/DLaB.Xrm.XrmToolBoxTools#216]
MS state that a good ALM process should be able to recreate a solution from source control.  When importing an unmanaged solution into a clean environment the platform created entities are assigned a non-determinate EntityTypeCode.  When next running the Early Bound Generator on this environment many diffs are created because the EntityTypeCode of all custom entities has changed (compared to the original environment).

I suggest that EntityTypeCode cannot be relied upon, and should be removed by the early bound generator to:
* Remove the noisy diffs from the Early Bound Generated Code
* Remove accidental coding against a non-determinate constant in the entity classes.

Perhaps the safest to make this a configurable option incase existing users are using EntityTypeCode.  This may be a crazy idea and there are valid uses for EntityTypeCode.

**Comment by daryllabar** [comment]
Entity Type codes are pretty much worthless and should never be used as far as I know, so I agree with everything here. 

Only negative is that MS generates them by default.

I still think it makes sense to remove the type code by default.  Pull requests welcomed.

**Comment by filcole** [comment]
Removal of entity type code implemented without config in #218

**Comment by daryllabar** [comment]
2.24 has been pushed with this change.

**Comment by daryllabar** [comment]
@filcole do you have a twitter account, and are we friends on Linked In?

**Comment by filcole** [comment]
Hi Daryl, I'm here https://twitter.com/EffEyeEll and we're friends already on LinkedIn. :)
