### ISSUE TITLE
[EarlyBoundGenerator] When used interactively via XrmToolBox save config immediately after a run

### ISSUE THREAD

**Issue by filcole** [daryllabar/DLaB.Xrm.XrmToolBoxTools#217]
Many (many :) ) times we've forgotten to close the Early Bound Generator tab and therefore not had the correct early bound config included along with the early bound code. 

Could the config.xml be saved immediately after the generator, or perhaps the user presented with a popup along the lines of "Generation complete. Save configuration?" [Save Config|Don't Save]

**Comment by daryllabar** [comment]
I've never really liked the save feature of the settings.  I just wanted it to work without having to think about it, but that isn't always the case.

I see auto saving on generation of the entities being a better option.  Will probably implement that.

**Comment by filcole** [comment]
Hi @daryllabar,  I think this is working OK now, so closing this issue.  Please re-open if you think otherwise.  Best Regards, Phil
