### ISSUE TITLE
How can I change version of SDK?

### ISSUE THREAD

**Issue by xavik0f2** [daryllabar/DLaB.Xrm.XrmToolBoxTools#220]
I have several instances in v8.2 version and when I used the latest version of EarlyBoundGenerator I get error when try to use generated classes ("CrmService is not ready")

How can I choose an specific version of SDK (e.g. CrmSvcUtil of 8.2)??

Thanks in advance!

**Comment by daryllabar** [comment]
I'm almost 95% sure that the generation of the Earlybound classes is not version dependent.   You're not generating entities against an online instance, and then trying to use them in an 8.2 instance are you?  That could cause an issue where multi select option sets get generated.

**Comment by xavik0f2** [comment]
I only have on premises instances. For now We always generate the classes with the official CrmSvcUtil and there was no problems. Since time ago we started to use Early bound generator and there was no problem to generate the classes. But when I use this clases in a console project I got the error "CrmService is not ready" (If I use the classes in a plugin or in a code activity there is no problem)..

For this reason I would like to have a version of EarlyBound in which I assure that classes are generated with v8.2 SDK. Sorry for my english!

**Comment by daryllabar** [comment]
I think you're trying to fix the wrong problem.  Generating the classes, just generates the .cs class without any specificity to the version of the platform, so I really don't think there is an issue with how the newer CrmSvcUtil.  In fact, I would suggest tweaking your program to remove the Early Bound classes and see if you are still getting the error, before changing the version of the CrmSvcUtil.

But if you'd like to change the CrmSvcUtil used, the path to it is in the UI of the EarlyBoundGenerator.  Download your own CrmSvcUtil from nuget and replace the crmsvcutil in the folder with your older version.  Just make sure to leave the DLaB libraries.  Other option is to manually download an older version of the EBG before it switched off whatever version of the SDK you want to use.
