### ISSUE TITLE
Null Reference exception when attempting to generate

### ISSUE THREAD

**Issue by mwilsonray** [daryllabar/DLaB.Xrm.XrmToolBoxTools#221]
Running version 1.2020.2.24 on XrmToolBox 1.2020.2.37 against an on-premise D365 9.0.12.4 organization. Get null ref exception when any Generate button is clicked. See screen shot:
![image](https://user-images.githubusercontent.com/14338121/76116320-682e4600-5faf-11ea-8e57-a19afe3130b8.png)

**Comment by daryllabar** [comment]
Hmm... this is the GetUserDomain method:
```
private string GetUserDomain()
{
    if (string.IsNullOrWhiteSpace(ConnectionDetail.UserDomain))
    {
        return ConnectionDetail.UseOnline
            ? ConnectionDetail.UserDomain
            : ConnectionDetail.UserName.Split('\\').FirstOrDefault(); // Domain\UserName
    }
    else
    {
        return ConnectionDetail.UserDomain;
    }
}
```
So for a null ref in this method, it would have to have a null UserName.  Do you save your credentials when creating the connection, or do you enter them each time?

**Comment by mwilsonray** [comment]
It's used Active Directory, so no credentials are entered.

**Comment by daryllabar** [comment]
[DLaB.EarlyBoundGenerator.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/4306520/DLaB.EarlyBoundGenerator.zip)
Can you replace your EarlyBoundGenerator.dll in the plugins folder of the XTB and see if this version resolves your issue?  If so, I'll publish it out for everyone.

**Comment by mwilsonray** [comment]
> Can you replace your EarlyBoundGenerator.dll in the plugins folder of the XTB and see if this version resolves your issue? If so, I'll publish it out for everyone.
That works - the CrmSvcUtil did get an exception that first time it was invoked, but it appears your code catches it and re-invokes with the interactive login flag. I've attached the output in case you need it.
[DLaB.EarlyBoundGenerator_output.txt](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/4306768/DLaB.EarlyBoundGenerator_output.txt)

**Comment by daryllabar** [comment]
OK @mwilsonray so that got around your null ref issue, but you still had to use the interactive login.  You're running against an OnPremise server, and your Windows credentials have rights to the Server?  You aren't running the XTB as a different user are you?

**Comment by mwilsonray** [comment]
No, I'm running as the same user that I'm logged into the computer with and that user is a System Admin on the server. The error is not optimal, but the automatic reinvoking with the interactive switch works.

**Comment by daryllabar** [comment]
@mwilsonray  if you can do some trial and error with the connection string, and tell me what the connection string should be, I can update the EBG to generate that string for you.

**Comment by marufdolani** [comment]
I was getting null refs (ConnectionDetail.OrganizationUrlName was null)  with the latest cds environment while generating and saving settings. i fixed this by replacing
`var orgName = ConnectionDetail.OrganizationUrlName;`
with
`   int startIndex = ConnectionDetail.WebApplicationUrl.LastIndexOf('/') + 1;
    int length = ConnectionDetail.WebApplicationUrl.IndexOf('.') - startIndex;
    var orgName = (ConnectionDetail.OrganizationUrlName == null) ? ConnectionDetail.WebApplicationUrl.Substring(startIndex, length) : ConnectionDetail.OrganizationUrlName;`

After this fix, i was getting authentication errors which was fixed by updatin the referenced CrmSvcUtil with the latest version.
HTH

**Comment by marufdolani** [comment]
@daryllabar  I will test the new fix. Assuming latest CrmSvcUtil bindings has been pushed through as well. Assembly Manifest was referencing older versions causing auth errors earlier.

**Comment by daryllabar** [comment]
I think I have it setup correct.

**Comment by daryllabar** [comment]
I think this is a dup of #223 and should now be fixed.
