### ISSUE TITLE
Can't generate Entities, Option sets and Actions, ADFS MFA Broken

### ISSUE THREAD

**Issue by daniele-torlai** [daryllabar/DLaB.Xrm.XrmToolBoxTools#223]
Hi,
when i try to start Entities, Option sets and Actions generation the crmsvcutil.exe can't connect to our CRM instance using the same creadential i usually use.
Our connection type is SDK Login Control and prompts us the login panel (we have a MFA authentication on that specific user).

The error message we receive is

> You don't have permission to access any of the organizations in the Microsoft Common Data Service region that you specified. If you're not sure which region your organization resides in, choose "Don't know" for the CDS region and try again. Otherwise check with your CDS administrator.

Obviousely we have the permissions (that is our administrative user).

You can find the entire log attached to this issue.

Thank you in advance for your help.
[Trace-Log.txt](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/4375686/Trace-Log.txt)

**Comment by daniele-torlai** [comment]
Sorry i almost forgot: the version i'm using is the last one (1.2020.3.20).
No issues at all with the past ones.

Best regards.

**Comment by daryllabar** [comment]
The only changes I made this month deal with null ref issues, and updating the SDK controls.  Can you verify that if you switch back to the previous version, that it starts working (https://www.nuget.org/packages/DLaB.Xrm.EarlyBoundGenerator/1.2020.2.24)

**Comment by daniele-torlai** [comment]
Thank you for the quick answer.

I installed the older version you provided and now i'm able again to create Entities, Opt. Set and Action files.

**Comment by daryllabar** [comment]
Can you double check the version of the CrmSvcUtil that the is being used by the EBG that is working?


Thanks!


Daryl LaBar

________________________________

**Comment by daniele-torlai** [comment]
Sure!
Here the comparison.

![image](https://user-images.githubusercontent.com/48206919/77438214-d5324000-6de5-11ea-8e30-d6f5ba4527d9.png)

I also noticed tha also with this version in the trace log i get the very same error i mentioned in the first message, the difference here is that the CrmSvcUtils still goes on creating the files correctly.
[Trace-Log_older version.txt](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/4375874/Trace-Log_older.version.txt)

**Comment by daryllabar** [comment]
In the working version, you're hitting https://adcgroupspa.api.crm4.dynamics.com, but in the non-working, you're hitting https://adcgroupspa-sandbox.api.crm4.dynamics.com/XRMServices/2011/Organization.svc

Can you try hitting the same server just to eliminate any other discrepencies?

**Comment by daniele-torlai** [comment]
I already tried both environments  with the non-working version without success (same error) before opening the issue here.
The two are our CRM environments (SANDBOX and PROD), so we use the same authentication type and the same user/credentials (no variations or discrepancies at all).

**Comment by daryllabar** [comment]
Can you turn on verbose tracing in the CrmSvcUtil:


``` XML
    <switches>
      <!--Possible values for switches: Off, Error, Warning, Information, Verbose
						Verbose:      includes Error, Warning, Info, Trace levels
						Information:  includes Error, Warning, Info levels
						Warning:      includes Error, Warning levels
						Error:        includes Error level-->

      <add name="Microsoft.Xrm.Tooling.CrmConnectControl" value="Verbose"/>
      <add name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" value="Verbose"/>
      <add name="CrmSvcUtil" value="Verbose"/>
      <add name="Microsoft.IdentityModel.Clients.ActiveDirectory" value="Verbose" />
    </switches>
```

Run again and then look in the CrmSvcUtil.log and the ADAL_CrmSvcUtil.log.

If you need more detailed instructions as to the config file I'm talking about, let me know.

**Comment by daniele-torlai** [comment]
Hi,
thank you for the instructions.

I set the verbose tracing as you showed me, and i was only able to generate the CrmSvcUtil.log (or at least that is the only log file in the folder, i don't know if i have to search for the "ADAL" one elsewhere).

Here' the log file
[CrmSvcUtil.log](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/4385910/CrmSvcUtil.log)

Just an integration to what i described in the previous posts: i connect through an MFA user (here's why i have to use SDK Control connection type). Before the last update all worked good.

Just to exlude any other kind of issue i also tested with a non-MFA user on another environment: no issues. I think something broke with MFA response evaluation with the last update: i manage to receive the MFA request and to send the response from Authenticaror app, after that the error.

**Comment by daniele-torlai** [comment]
Here's the verbose log for the older working version
[CrmSvcUtil-older.log](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/4386047/CrmSvcUtil-older.log)

The difference is that, after the MFA evaluation part (you can find quickly searching for "MFA" word), it founds 5 orgs instead of No Orgs (newer version).

Hope it can help.

**Comment by daryllabar** [comment]
I've forwarded what you've sent onto Microsoft.  We'll see what the next steps are.  I did notice that things are becoming more CDS-y
![image](https://user-images.githubusercontent.com/9728423/77644179-0706ec00-6f37-11ea-9199-de1ebf69f3a6.png)

**Comment by SigrunO** [comment]
I'm having the same issue ...

**Comment by daryllabar** [comment]
@daniele-torlai / @SigrunO  I've been told by MS that the newest version of ADAL was having issues with the Microsoft.Xrm.Client dll being referenced by my libraries, so I've removed the references, updated to the latest version of the SDK and have a package for either of you to try.  If it resolves your issue, I'll push it out.

[DLaB.Xrm.EarlyBoundGenerator.1.2020.3.29.nupkg.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/4404595/DLaB.Xrm.EarlyBoundGenerator.1.2020.3.29.nupkg.zip)

Make sure you delete any of the previous files in the CrmSvcUtil directory before extracting the zip file.

**Comment by daniele-torlai** [comment]
@daryllabar unfortunately i'm experiencing the same issue even with the new package you provided.
Here's the log file, i've already turned "Verbose" loggin on.
[CrmSvcUtil.log](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/4404785/CrmSvcUtil.log)

**Comment by daryllabar** [comment]
OK, I think I may have figured it out, I was not referencing the correct version of Newtonsoft and for some reason i had my own Config file, rather than pulling in Microsoft's.  Try again with this zip, and make sure you unblock the zip after downloading it, but before installing.

[DLaB.Xrm.EarlyBoundGenerator.1.2020.3.29.nupkg.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/4405134/DLaB.Xrm.EarlyBoundGenerator.1.2020.3.29.nupkg.zip)

**Comment by daryllabar** [comment]
P.S.  If you have a twitter/Linked in account (and I ever get this fixed for you) can you share it with me so I can tag you and publicly thank you for reporting and trouble shooting?

**Comment by daniele-torlai** [comment]
Yes! I confirm that the issue is finally gone for good!
Thank you very much for the help.

I have a LinedIn account, feel free to add me; i will do the same as soon i'll receive the connection notification.
https://www.linkedin.com/in/danieletorlai/

**Comment by SigrunO** [comment]
thanks!
