### ISSUE TITLE
The code does not compile after generation in last version

### ISSUE THREAD

**Issue by ylegare** [daryllabar/DLaB.Xrm.XrmToolBoxTools#225]
I use your tool since some weeks. But after the last update, i got this error:
'PropertyInfo' does not contain a definition for 'Command' and no accessible extension method 'Command' accepting a first argument of type 'PropertyInfo' could be found (are you missing a using directive or an assembly reference?)

To reproduce, just try to generate "account" entity and use it.

Thanks

**Comment by daryllabar** [comment]
I guess it does work?
