### ISSUE TITLE
Issue with converting to global option set

### ISSUE THREAD

**Issue by Redboots2** [daryllabar/DLaB.Xrm.XrmToolBoxTools#230]
Hi

I had three fields to convert to a global option set. 2 worked perfectly but one had an issue.

No Temporary Attribute was found.  Treating New as not yet created.
Validating Current CRM State Before Performing Steps:
Beginning Step: Create Temp
Creating Attribute new_securityrequirement.new_linkedtravelarrangementsprotectionsummary_t_
Error Creating Attribute new_securityrequirement.new_linkedtravelarrangementsprotectionsummary_t_
System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Generic SQL error. (Fault Detail is equal to Exception details: 
ErrorCode: 0x80044150
Message: Generic SQL error.

I then was unable to access the form in CRM - received the same error as previous issue #167 so i had to remove the specified field within the error from the form. And it now opens again but i'm not to sure how to resolve both issues. 

Hope you can help.

Thanks

Ruth

**Comment by daryllabar** [comment]
Sometimes the metadata in CDS lags behind the actual settings.  Can you try again?  Looks like it failed on the first step to create the temporary attribute.

**Comment by Redboots2** [comment]
Hi

Tried it again but it still failed with a generic error at that same create step.

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Generic SQL error. (Fault Detail is equal to Exception details: 
ErrorCode: 0x80044150
Message: Generic SQL error.

do you have any other suggestions?

Thanks
Ruth

**Comment by daryllabar** [comment]
So it's failing at the Create Temporary Attribute Step?  Can you verify that the Temporary Attribute doesn't already exist?

**Comment by Redboots2** [comment]
Hi

Yes it definitely doesn't already exist. it would be a field right?

Thanks

Ruth

**Comment by Redboots2** [comment]
Its also not due to maxed out number of fields still have plenty...it's peculiar. 

Thanks
Ruth

**Comment by daryllabar** [comment]
Hmm...  Can you manually create the temp attribute?

**Comment by Redboots2** [comment]
Sure. What field type is it?

**Comment by daryllabar** [comment]
It's going to be whatever you want the final version of the Attribute to be.  So in this case I think it's a Global Option Set.  Give it the same name as the temporary one that's being created.  Then skip the creation step and see if the tool will go any farther.

**Comment by Redboots2** [comment]
ah - i just clocked, the name is too long so it cannot create it. just trying to think how i can get around this hmmm

**Comment by Redboots2** [comment]
i have just changed the new name and it has worked. hurrah!! thanks so much!
