### ISSUE TITLE
EBG : Allow output folder for entities with dot in the folder name

### ISSUE THREAD

**Issue by MscrmTools** [daryllabar/DLaB.Xrm.XrmToolBoxTools#234]
Hi Daryl,

I cannot generate entities when the output folder contains dot

![image](https://user-images.githubusercontent.com/10774317/80002820-703f3800-84c0-11ea-92da-c880b3e71b05.png)

---
- Deployment: Online
- DB Version: 9.1.0.15943
- XTB Version: 1.2020.2.37
- Tool Version: 1.2020.4.17

**Comment by daryllabar** [comment]
Just add a "\" to your path and it works

![image](https://user-images.githubusercontent.com/9728423/80283034-d3101980-86e2-11ea-957f-d54069ddd4ca.png)

With that said, I should not remove the slash from the name when switching back and forth me thinks...

**Comment by daryllabar** [comment]
I've not removed the slash, so that way it should just work.  Also added a note in the error to include the slash maybe?

**Comment by MscrmTools** [comment]
Thank you!
