### ISSUE TITLE
If output path contains a space, a new folder with %20 in lieu of the space is created

### ISSUE THREAD

**Issue by sundvl** [daryllabar/DLaB.Xrm.XrmToolBoxTools#241]

**Comment by daryllabar** [comment]
Is this for the Early Bound Generator?  If so, I'm unable to replicate this.

**Comment by sundvl** [comment]
Yes, it is.  If you use the ellipses to select the outbound folder, a %20 is inserted into the configuration.

[cid:34be31a0-e71a-4da4-96dc-db3e3664a38c]
The tool then creates a folder including the %20 in the name

[cid:7d077d26-824d-4905-bf8b-6d9dd822d109]

________________________________

**Comment by daryllabar** [comment]
Latest version should resolve this issue.  Thanks for reporting it!
