### ISSUE TITLE
Ability to flag/exclude fields marked as obsolete

### ISSUE THREAD

**Issue by filcole** [daryllabar/DLaB.Xrm.XrmToolBoxTools#242]
Sometimes fields are in the process of being deprecated but have not yet been fully removed from the solution/environment.  The fields are of the same publisher so can't be excluded via existing options in the EBG.

Perhaps an option in the EBG to indicate fields that contain a certain text in the "Display Name" of the field, e.g. "(OBS)" and then an follow-up option to determine whether to exclude (from generated classes) or warn (if that field use used).

Perhaps two additional configuration options:

-     Identify obsolete fields via:   "(OBS)"      <- Contents of display name
-     Process obsolete fields: Warn | Exclude      <- if Warn, then compiler warning is thrown if field is used (is this possible?). if Exclude then the early bound generator does not export these fields.

**Comment by daryllabar** [comment]
I'm not seeing using the description as a good way to specify how the Early Bound Generation should be performed.  This also feels like an extreme edge case that I don't see benefiting a very large portion of the community.  How many attributes do you have that this is happening with?  

Options I would suggest

1. Assuming this is only in a few instances, add a partial class for the entity(s), and duplicate the property in the partial class with an Obsolete attribute with true as an argument if you want a compiler error.  You'd then need to delete the property in the generated entity class file, and either manually redelete it every time you regenerate, or remove that entity from generation. 
2. Write some tool to look through your generated code and add the Obsolete attribute based on your description key word of (OBS).  You could either remember to run it manually, or make a custom provider class for the CrmSvcUtil that inherits from my class and is configured to be used by the EBG.
