### ISSUE TITLE
How to remove System.CodeDom.Compiler.GeneratedCodeAttribute

### ISSUE THREAD

**Issue by aboodh95** [daryllabar/DLaB.Xrm.XrmToolBoxTools#250]
Hi,
Each time I'm running the Early bound, all files are being changed and the changed value is  System.CodeDom.Compiler.GeneratedCodeAttribute in the header, I already set "Remove Runtime Version Comment" to True (I don't know if it's the same), the problem it's becoming hard to track the changes from git perspective as all entities classes will be modified
---
- Deployment: Online
- DB Version: 9.1.0.18647
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.6.40
- Tool Version: 1.2020.6.22

**Comment by daryllabar** [comment]
That attribute should only change when I update the SDK crmsvcutil used to generate the entities.  In the past when I've seen that change happen, undo my check out, search and replace all those values with the new version value, and check in the change.  Then redo the generation.

But I see no reason why this couldn't be added as an option.

**Comment by daryllabar** [comment]
This has been done as the the EBG V2:
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9728423/68b63dd0-84a4-4352-9000-f0fe7fa6e0a8)
