### ISSUE TITLE
VB.Net Support for the EarlyBoundGenerator

### ISSUE THREAD

**Issue by atfolz** [daryllabar/DLaB.Xrm.XrmToolBoxTools#257]
**Tool**
EarlyBoundGenerator

**Is your feature request related to a problem? Please describe.**
We have a plugin assembly that used the generated file from CrmSvcUtil, when we hit the max types, Microsoft suggested we contact you about support on handling this with the EarlyBoundGenerator.

**Describe the solution you'd like**
We'd like VB.Net support for the EarlyBoundGenerator.

**Describe alternatives you've considered**
Lternatives would include changing our code for the assembly to C#, which would be a lot of time we don't really get to have. The other alternative is a potential update Microsoft is planning, but they suggested we contact you for a potentially quicker solution.

**Additional context**
The response from Microsoft:
"As a point we did look into your code and our code and it is indeed the limitation on types that your hitting.   

Thus your going to need to keep doing the manual edit for a time on your files. 
You can reach out to author of the addin for XrmToolbox to see if they would be willing to update their code to generate VB for you for that module…   as that will likely be quicker then waiting for us to ship the updates that we have in flight for CrmSvcUtil."

**Comment by daryllabar** [comment]
The CrmSvcUtil [supposedly does support generation for VB](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/generate-early-bound-classes#parameters) but I have made changes to the generation DOM that take advantage of C# syntax not available in VB.Net and therefore updating the language flag to VB will most likely not work for you. 
 I have no plans on supporting a VB version of generation.  But here are your options:

1.  Fork this project and add the feature.  Not sure how much this would take, but my guess is that it would just involve the few places I make changes to the Code DOM.  If you have the actual DLaB.CrmSvcUtilExtensions project updated send me a PR, and I will be happy to update the UI for you.
2.  Find some C# to VB.Net converter to convert the project post generation.  You can probably call it all from a batch/PS script and still be fairly automated.
3.  Put the C# code in a separate C# project, and ILMerge it into you VB.Net plugins.
