### ISSUE TITLE
Add relationship names as constants into proxy class.

### ISSUE THREAD

**Issue by maxkoshevoi** [daryllabar/DLaB.Xrm.XrmToolBoxTools#258]
**Tool**
What tool/version is it that you're making a feature request for? i.e.
EarlyBoundGenerator

**Is your feature request related to a problem? Please describe.**
I need to associate / disassociate teams from systemuser. In order to do this I need a relationship name, so I need to create a separate constant for it somewhere. 

**Describe the solution you'd like**
It would be useful if relationship names would be present in proxy class generated by this tool (the same way as attribute names)

**Describe alternatives you've considered**
Creating a constant with relationship name in some other file that I need to maintain.

**Additional context**

**Comment by daryllabar** [comment]
If you generate the Attribute Names, and Generate the Relationships, it generates the names for N:1 relationships.

![image](https://user-images.githubusercontent.com/9728423/92034964-05d6b800-ed3c-11ea-89b2-aeecb9bc6fa8.png)

For N:N relationships, you should be selecting that relationship and generating the Early Bound class for the relationship.  Does that not work for you?  Or am I misunderstanding something?

**Comment by maxkoshevoi** [comment]
Yes, 1:N is there, but it would be great if it also contain N:N.
By the way, `teammembership` (relationship) entity also doesn't contain team - user relationship name.

![image](https://user-images.githubusercontent.com/6609929/92036648-3c7ef380-ed79-11ea-87f9-a66752a8b787.png)

What entity do I need to generate proxy for to get `teammembership_association` relationship?

**Comment by maxkoshevoi** [comment]
**Unrelated**

Could you also help me with this, please.
This works (associates one security role to the user):
![image](https://user-images.githubusercontent.com/6609929/92036903-9da6c700-ed79-11ea-88ad-08bc5c558387.png)

While this doesn't do anything:
![image](https://user-images.githubusercontent.com/6609929/92037103-f2e2d880-ed79-11ea-96b6-1b115f5035a0.png)

Am I doing something incorrectly?

**Comment by daryllabar** [comment]
> Yes, 1:N is there, but it would be great if it also contain N:N.
> By the way, `teammembership` (relationship) entity also doesn't contain team - user relationship name.
> 
> ![image](https://user-images.githubusercontent.com/6609929/92036648-3c7ef380-ed79-11ea-87f9-a66752a8b787.png)
> 
> What entity do I need to generate proxy for to get `teammembership_association` relationship?

If you want to add a member to a team, just create a new TeamMembership record:

```
service.Create(new TeamMembership{
    TeamId = team.Id,
    SystemUserId = user.Id
});
```
No association calls required.

**Comment by daryllabar** [comment]
Interesting on your Unrelated.  TBH, I don't know why one works vs. the other.  I'm just using the code generated by the CrmSvcUtil, so you may want to post on StackOverflow or the MS Community Forums.  Kind of weird that it doesn't since there is nothing in the property generation that is different.

``` C#
/// <summary>
/// N:N systemuserroles_association
/// </summary>
[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("systemuserroles_association")]
public System.Collections.Generic.IEnumerable<CrmEarlyBound.Role> systemuserroles_association
{
	[System.Diagnostics.DebuggerNonUserCode()]
	get
	{
		return this.GetRelatedEntities<CrmEarlyBound.Role>("systemuserroles_association", null);
	}
	[System.Diagnostics.DebuggerNonUserCode()]
	set
	{
		this.OnPropertyChanging("systemuserroles_association");
		this.SetRelatedEntities<CrmEarlyBound.Role>("systemuserroles_association", null, value);
		this.OnPropertyChanged("systemuserroles_association");
	}
}

/// <summary>
/// N:N teammembership_association
/// </summary>
[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("teammembership_association")]
public System.Collections.Generic.IEnumerable<CrmEarlyBound.Team> teammembership_association
{
	[System.Diagnostics.DebuggerNonUserCode()]
	get
	{
		return this.GetRelatedEntities<CrmEarlyBound.Team>("teammembership_association", null);
	}
	[System.Diagnostics.DebuggerNonUserCode()]
	set
	{
		this.OnPropertyChanging("teammembership_association");
		this.SetRelatedEntities<CrmEarlyBound.Team>("teammembership_association", null, value);
		this.OnPropertyChanged("teammembership_association");
	}
}

```

**Comment by maxkoshevoi** [comment]
Can I get a relationship name (`teammembership_association`) as a constant in some proxy though?

**Comment by daryllabar** [comment]
Possibly.  I'd have to see what is generating the attributes for the relationships.  Maybe it is just skipping N:N relationships.  Is there any reason you don't just create the entities using the N:N Entity?

**Comment by maxkoshevoi** [comment]
No particular reason, but help me understand. Do all N:N relationships have an entity that I can create to associate two entities? Why do we even need relationship name (especially that differs from relationship entity name), and  more importantly, why organization service have `Associate` method?

I just assumed that using  `Associate` method is a preferred way of associating entities in N:N relationships and try to use it.

Here is my current solution: https://stackoverflow.com/questions/23539536/how-to-check-if-a-relationship-already-exists/63714959#63714959

**Comment by daryllabar** [comment]
Great questions.  I unfortunately don't have very good answers.  My guess is originally CRM didn't allow N:N entities to be created as an entity, so they required the use of associate/disassociate.  But at some point they added the ability.  All I know is dealing with relationship names is a pain, and N:N entities seem to work easier and read cleaner.

**Comment by matejskubic** [comment]
Is it possible to generate relationship names without generating relationships?
Or add an option `GenerateAttributeNameConsts` with new option like `GenerateRelationNameConsts`?

**Comment by daryllabar** [comment]
Yeah, it could be done.  Not sure when I'd have time though.  Even if someone had a PR for the actual code generation, and I handled creating the options, that would allow this to work faster.

**Comment by daryllabar** [comment]
![image](https://user-images.githubusercontent.com/9728423/121988265-fb842880-cd67-11eb-9acf-86415040d667.png)
