### ISSUE TITLE
Option Set Value Naming

### ISSUE THREAD

**Issue by SigrunO** [daryllabar/DLaB.Xrm.XrmToolBoxTools#259]
**Tool**
EarlyBoundGenerator

**Is your feature request related to a problem? Please describe.**
I'm working together in a team where different tools are used for early bound generation. The proxy classes are compatible with one exception: the names for the option set values follow different naming conventions.

My question basically is: is there a way to control what naming convention is used? 
a) Concerning the names used for the option set values
I currently see that for the values the EarlyBoundGenerator uses the label name and replaces blanks with underscore. 
The other tool we use removes blanks and if the word after the blank begins with a lower case letter, this letter is replaced by upper case, making the name camel case.

b) Concerning the Names of the option sets
the EarlyBoundGenerator uses the attribute schema name
the other tool uses the attibute logical name

**Describe the solution you'd like**
it would be great if there were a way to configure both a) and b)

**Comment by daryllabar** [comment]
I'm a little confused as to what you're saying the EBG is creating.  So for A, the naming of the values, the EBG removes all invalid C# characters, leaving the Capitalization as is:
![image](https://user-images.githubusercontent.com/9728423/94563913-5b1bc180-0235-11eb-9075-cc796b525523.png)

Notice the "-"'s are removed, but not the "i" in "non-interactive" is not capitalized but the "W" in "Read-Write" is.  It sounds like you're just wanting a method to force the capitalization?  Would it be after every invalid C# character, or just blank spaces?

For B: Any chance the "Use Deprecated Option Set Naming" set to true helps?

Might help to have some specific examples of what is getting generated, and what you're wanting.

**Comment by SigrunO** [comment]
**Examples:**

_Display name of the value:_
Ethernet 10M - 10 Mbit/s
Bereit für Transaction

_Generated_:
[System.Runtime.Serialization.EnumMemberAttribute()]
Ethernet_100M__10___10_Mbit_s = 9

[System.Runtime.Serialization.EnumMemberAttribute()]
Bereit_fuer_Transaction = 726850000,

_Expecting_
[System.Runtime.Serialization.EnumMemberAttribute()]
Ethernet100M_10_10Mbit_s = 9

[System.Runtime.Serialization.EnumMemberAttribute()]
BereitFuerTransaction = 726850000

**Note**
The organization we are working with only has German als Language installed (I hate it), may that be the reason?

**Comment by daryllabar** [comment]
I'll be honest... the double underscores suck!  Having the underscores come through is surprising... not sure if that is language related... it could be.  

The first option confuses me.  Why would "Ethernet 10M -10 MBit/s come through as "Ethernet100M_10_10Mbit_s", and not "Ethernet10M_10Mbit_s" or even"Ethernet10M10Mbits"?

**Comment by daryllabar** [comment]
@SigrunO, still waiting on an answer.

**Comment by SigrunO** [comment]
Sorry for the very late answer... I missed the notification email.
I agree the first option seems wrong. I had a typo in the display name when I wrote it in the post.

**Comment by daryllabar** [comment]
This would require a complete re-write of how name generation works.  I'm open to pull requests, but I'm not looking to implement this.  You could implement your own INamingService, or you could try one of the other early bound generators in the XTB to see if they meet your needs.  I use whatever Microsoft generates, then I add the transliterate logic, and remove invalid C# characters as well as handling duplicates.

**Comment by SigrunO** [comment]
Thanks for your response. I'll see what I can do.
