### ISSUE TITLE
Command Line Output in OptionSets file is incorrect

### ISSUE THREAD

**Issue by SigrunO** [daryllabar/DLaB.Xrm.XrmToolBoxTools#26]
The command line output to the generated file when generation options sets is not the command line needed to regenerate the option sets. Instead the command line to regenerate the entities is put into the file.

**Comment by daryllabar** [comment]
Good catch!

**Comment by daryllabar** [comment]
This will be fixed with the next release

**Comment by SigrunO** [comment]
sorry, accidently open the issue again....
