### ISSUE TITLE
Local to Global OptionSet migration data with mixed values

### ISSUE THREAD

**Issue by Luard** [daryllabar/DLaB.Xrm.XrmToolBoxTools#261]
**Tool and Version**
What tool/version is it that you're reporting a bug for? i.e.
AttributeManager V 1.2019.3.22

**Describe the bug**
When converting local optionset to global optionset using a mapping file, if values are mixed between them on mapping file, the final value is not correct.

Example:
Local optionSet:
| Text | Value |
| ------------- | ------------- |
| A  | 1 |
| B | 2 |
| C | 3 |

Global optionSet
| Text | Value |
| ------------- | ------------- |
| A  | 0 |
| B | 2 |
| C | 1 |

Mapping file:
```
1, 0
2, 2
3, 1
```

Final optionSet values after `Convert Attribute Type` and `Migrate Data` done:
On records:
| Record old value | Record new value | Record expected value | Result |
| ------------- | ------------- | ------------- | ------------- |
| A (1) | A (0) | A (0) | OK |
| B (2) | B (2) | B (2) | OK |
| C (3) | A (0) |  C (1) | Error |

Last value is wrong, `C (1)` value was expected on new record value.

**To Reproduce**
1. Create local optionSet with the following values:

| Text | Value |
| ------------- | ------------- |
| A | 1 |
| B | 2 |
| C | 3 |

2. Create global optionSet list with values:

| Text | Value |
| ------------- | ------------- |
| A | 0 |
| B | 2 |
| C | 1 |

3. Create some records with the optionSet field set in order to have data to test.
4. Change attribute type with migration using the following mapping *.csv and with the checks `Convert Attribute Type` and `Migrate Data`:
```
1, 0
2, 2
3, 1
```
5. Check that records with `C` values have been mapped to `A` instead of `C`

**Expected behavior**
Mapping should be done properly.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/21971499/94913637-e43b2e80-04a9-11eb-90b0-efb8c3ec257f.png)

**Comment by Luard** [comment]
After some tests, as a workaround it can be done by spliting steps. Using the same example mentioned before:

1. The following steps with the migration file:
Mapping file:
```
1, 0
2, 2
3, 1
```
Steps:
![imagen](https://user-images.githubusercontent.com/21971499/94932041-d052f500-04c8-11eb-89db-78c0d0711ff1.png)

2. And the rest of the steps with a different miggration file like:
Mapping file:
```
0, 0
2, 2
1, 1
```
Steps:
![imagen](https://user-images.githubusercontent.com/21971499/94932222-11e3a000-04c9-11eb-8d75-1f1cca601a04.png)


I will also check if WFs and views work properly.

**Comment by daryllabar** [comment]
AH!!!! I'm doing the Mapping twice, once on the Migrate to Temporary, and once again on the migrate to new.  I shouldn't be doing it on the migrate to new.  Good catch!

**Comment by daryllabar** [comment]
Latest version should fix this.  Do you have a twitter/Linkedin profile I can share with a public thank you for your support?
