### ISSUE TITLE
Attribute Manager - Changing a data type Global Option Set to a different Global Option Set

### ISSUE THREAD

**Issue by retthom** [daryllabar/DLaB.Xrm.XrmToolBoxTools#262]
I used the attribute manager tool to change a Global Option Set to a different Global Option Set.  The tool is making the changes correctly.

My problem that I am having is when moving my solution that contains the changes to a different instance.  If the field already exist in the instance the changes are not making the changes.

Get the following error message:

This error can occur if you had previously created a field (attribute) of a certain data type and later try to import a solution that contains the same field name but with a different data type.

Example: You create a field called CustomField1 with the Data Type set as Two Options (Boolean). If you try to import a solution with the same field name but a different Data Type such as Option Set (Picklist), you will encounter this error.

---
- Deployment: Online
- DB Version: 9.1.0.16251
- XTB Version: 1.2020.4.38
- Tool Version: 1.2019.3.22

**Comment by daryllabar** [comment]
You have to run the tool in each and every environment.  CDS doesn't support updating a field on solution import
