### ISSUE TITLE
New field for Custom Entity not being output to Entities.cs

### ISSUE THREAD

**Issue by LeeJP1983** [daryllabar/DLaB.Xrm.XrmToolBoxTools#266]
**Tool and Version**
What tool/version is it that you're reporting a bug for? i.e.
EarlyBoundGenerator V 1.2020.10.2

**Describe the bug**
In Dynamics 365 I add a new Whole Number field to a custom entity. I then open the Early Bound Generator and Create Entities. When loading the file in a text editor the new field is not present.

**To Reproduce**
1. Add new Whole Number field to Custom Entity
2. Click Create Entities in Early Bound Generator, using defaults
3. Open generated cs file
4. Look for new field

**Expected behavior**
I expect that when a new field is created for a custom entity that the new field would be present under that entity in the entities.cs file.

Executing "C:\Users\jerimiah\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://stage.api.crm.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"Xrm" /out:"C:\Users\jerimiah\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\Entities.cs" /servicecontextname:"XrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /interactivelogin:true 
CrmSvcUtil : CRM Service Utility [Version 9.1.0.45]
c 2020 Microsoft Corporation. All rights reserved

 Ensuring Context File is Accessible 
 Writing file Entities.cs to C:\Users\jerimiah\AppData\Local\Temp\tmp7E6A.tmp 
Code written to C:\Users\jerimiah\AppData\Local\Temp\tmp7E6A.tmp.
 Updating File C:\Users\jerimiah\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\Entities.cs 
 Cleaning up Temporary File C:\Users\jerimiah\AppData\Local\Temp\tmp7E6A.tmp 
 C:\Users\jerimiah\AppData\Local\Temp\tmp7E6A.tmp Moved To: C:\Users\jerimiah\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\Entities.cs 
Creation Complete!

**Comment by daryllabar** [comment]
That shouldn't happen.  Have you published your new field yet?  If so, try reinstalling the EBG

**Comment by LeeJP1983** [comment]
Yes, I've published it multiple times. I even published all customizations just to be sure. I have tried uninstalling and reinstalling but no difference.

**Comment by daryllabar** [comment]
Any chance you're pointing at a different environment, or your outputting to individual files now, rather than the big file, or your outputting to a different directory?

**Comment by LeeJP1983** [comment]
I've double checked the environment, and I am pointing to the right one. I even tried in a second environment and I am having the same issue.

I've tried outputting a single file and multiple files and I don't see the new field in either output.

I followed the directory that the output of EBG gives in the output window.

**Comment by LeeJP1983** [comment]
There must have been some strange setting cached from months ago. Once I reset the DefaultSettings.xml, the field now shows up. Strange though. I wonder what setting could have caused that.

**Comment by daryllabar** [comment]
You didn't turn on the debug feature that caches the metadata did you?

**Comment by LeeJP1983** [comment]
As far as I can tell, no I did not.  All three of the options under Debug are set to False.
