### ISSUE TITLE
Attribute Manager not pulling in all attributes(columns) of custom entity(table)

### ISSUE THREAD

**Issue by jcpieper** [daryllabar/DLaB.Xrm.XrmToolBoxTools#275]
When retrieved, custom entity only has the boilerplate attributes available to modify. Other custom entity created does not have this issue. Cannot figure out why.

**Comment by daryllabar** [comment]
It will only pull in unmanaged attributes.  Is that what you're seeing?

**Comment by jcpieper** [comment]
Yes, that's it! Does that mean I need to move the entity out of the solution we use?
