### ISSUE TITLE
Export just last updated entities

### ISSUE THREAD

**Issue by amir65gh** [daryllabar/DLaB.Xrm.XrmToolBoxTools#278]
Hi all,
I exported entities and successfully could work on it. 
But the problem, for updating libraries, We should export all entities again and try to find updated entities(because of team work). 
Is it possible to export just updated libraries updated from the specific date (F.E. 2010/01/15)
Thanks

**Comment by amir65gh** [comment]
We created our solution with generated entities. So, our team works and changing the entities, So, we need to updated just modified entities to push to git.

**Comment by daryllabar** [comment]
Git should be doing this for you automatically.  It should just be looking at the file content, and only showing files that have been updated as needing to be sync'd
