### ISSUE TITLE
Ability to include File data type in the entity classes

### ISSUE THREAD

**Issue by gvc55** [daryllabar/DLaB.Xrm.XrmToolBoxTools#279]
**Tool** EarlyBoundGenerator

**Is your feature request related to a problem? Please describe.**
Just a request for adding the ability to generate Early bound methods for File data types. Not a problem but wonder if this will make life a bit easier for some developers. 

**Describe the solution you'd like**
The Annotation (Note) table in Dataverse handles the addition of attachments to any record. However, if all you need is one file to a record in any entity, for processing or just for record keeping, then the File type will suffice.  However, this File type does not appear to be handled (or recognized) by the EarlyBound Generator. Is this feature in any future plan or you cannot get there from here at this point? Just curious if I should wait for a later version or just continue with the Annotation table approach.

**Comment by daryllabar** [comment]
I haven't attempted to test a file data type attribute before...  I'd be happy to add it if I'm able to figure out how.  First, can I request that you attempt to run the CrmSvcUtil without any of the EarlyBoundGenerator dlls/command line args (they'd contain DLaB. in them) and verify if MS is generating these attributes?  If MS isn't generating them, then I have to start from scratch.  If they are generating them, then I have to figure out why I'm removing them.

**Comment by gvc55** [comment]
Thanks for your reply. I am new to this whole Early Bound Generator area so
I have no idea what your are asking me to do. However, I will be happy to
try and test if you can guide me in what needs to be done. I was going to
try using the Late Bound approach and see how far I can get but sounds,
from your reply, that maybe Microsoft already included it in their tool,
maybe?

**Comment by daryllabar** [comment]
OK.  I'd recommend using the Earlybound still.  Does the attribute get generated at all?  If so what is the type of the property?

**Comment by gvc55** [comment]
From what I can tell, the field/column is being ignore completely, like it
does not exist, but it does. So that's why I wonder what's the deal.

**Comment by gvc55** [comment]
Hello Daryl! As a follow up, I couldn't figure out what you were asking me
to do so I continued to figure out how to access the File data type From a
late bound perspective and it does work fine. As a matter of fact, I
expanded the early bound class for the table added properties to access the
field and it seems to work just fine. Once again, I'll be happy to try
using the MS tools, which I haven't used yet, of you can direct me on how's
to do it.

Thanks again.

**Comment by gvc55** [comment]
Daryl,

 

When using the Earlybound Generation tool, the attribute is nowhere to be found. So I am forced to use the latebound for this data type. I have it working so I am happy, but will be even happier if the Earlybound would recognize it. ☹

**Comment by daryllabar** [comment]
Looks like the only thing you can get out of this is the file name, and a GUID that I'm unable to find of any use.  Are you seeing something different?
