### ISSUE TITLE
Unable to add a reference to the DLaB.Xrm.EarlyBoundGenerator NuGet package in an SDK-style project

### ISSUE THREAD

**Issue by joshcampbell191** [daryllabar/DLaB.Xrm.XrmToolBoxTools#282]
**Tool and Version**
What tool/version is it that you're reporting a bug for? i.e.
EarlyBoundGenerator v1.2021.4.19

**Describe the bug**
When attempting to install the NuGet package as a reference to my project, it fails to install with the following exception:

Package DLaB.Xrm.EarlyBoundGenerator 1.2021.4.19 does not support any target frameworks.

**To Reproduce**
1. Create a new .NET framework console application using the [SDK-style](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview) project file.

sample.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
</Project>
```
2. Add a reference to the `DLaB.Xrm.EarlyBoundGenerator` NuGet package.

**Expected behavior**
The project reference should install without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/1784236/116637508-1f171f00-a932-11eb-8c72-a4f13ed8bfe2.png)

**Additional context**
Adding the reference to a .NET framework 4.7.1 project using the old style csproj works.

**Comment by daryllabar** [comment]
You shouldn't be installing the Nuget package.  It's for the XrmToolBox.  Did you mean the API nugget package?

**Comment by joshcampbell191** [comment]
That'll do it! Thanks a lot!

**Comment by daryllabar** [comment]
Since I'm assuming your new to the Dataverse space, feel free to check out the podcast on Earlybound vs late bound https://xrmtoolcast.libsyn.com/daryl-and-jonas-argue-early-bound-vs-late-bound
