### ISSUE TITLE
InvalidCSharpNamePrefix flag for Option Sets not working

### ISSUE THREAD

**Issue by Ed209Dev** [daryllabar/DLaB.Xrm.XrmToolBoxTools#287]
**Tool and Version**
EarlyBoundGenerator V 1.2020.4.24

**Describe the bug**
OptionSets that result in invalid C# names aren't being converted into valid Enum Names ie the underscore character isn't being inserted even though the 'Invalid CSharp Prefix Name' is set to "_":

![image](https://user-images.githubusercontent.com/84033993/117853301-26b6bc00-b280-11eb-9e25-b05a3e0b5405.png)

I've checked the config value in the wrapper (DLaB.EarlyBoundGenerator.DefaultSettings) and it seems to be correct:

![image](https://user-images.githubusercontent.com/84033993/117855442-667ea300-b282-11eb-9e8f-9b329b5e84cf.png)

I've also checked the config value in crmsvcutil.exe.config and that also seems to be correct:

![image](https://user-images.githubusercontent.com/84033993/117855721-a8a7e480-b282-11eb-8b22-2f393622c294.png)

**To Reproduce**
1. Config settings as default except "Add Option Set Metadata Attribute" set to False
2. Click "Create OptionSets" button

**Expected behavior**
Example - The name begins with a numeric so an underscore should be inserted ie legacy extract produced _230Net30

Current extract:
![image](https://user-images.githubusercontent.com/84033993/117855967-f3296100-b282-11eb-8402-3f152ebca425.png)

**Comment by Ed209Dev** [comment]
After doing some more investigation it seems this may be an issue with the CrmSvcUtil executable rather than XrmToolBox as the same problem manifests when running CrmSvcUtil directly (v9.1.0.80) from the command prompt.

I've also tried running an earlier version of CrmSvcUtil (v9.0.0.9154 from 2017) and get the same result - ie underscores not added.

If the executable is no longer capable of adding prefixes then maybe the "Invalid C# Name Prefix" setting should be removed from the Early Bound Generator gui? Will leave the issue open for others to discuss...

**Comment by daryllabar** [comment]
Oh it's been an issue with the CrmSvcUtil since day one, that's why I added that feature...  I should be able to handle it.

**Comment by Ed209Dev** [comment]
Ok thanks. You would have thought Microsoft would have either fixed the problem or removed the setting! Just leaving it not working is a bit lame...

**Comment by daryllabar** [comment]
Update your version of the Early Bound Generator.  Latest is 1.2021.4.19.  I can't recreated this in the latest version.
