### ISSUE TITLE
EarlyBoundGenerator not installing

### ISSUE THREAD

**Issue by scottgolightly** [daryllabar/DLaB.Xrm.XrmToolBoxTools#289]
**Tool and Version**
EarlyBoundGenerator V 1.2020.4.24

**Describe the bug**
I attempt to install the EarlyBoundGenerator from the toolbox dialog in XRMToolbox. I immediately get a message saying "Installation Done!" but the progress in the lower right corner of that dialog still shows that it is still installing. After the installation completes EarlyBoundGenerator still shows as not installed.
![image](https://user-images.githubusercontent.com/4343718/119691431-cee38d80-be07-11eb-9a7e-7ac3224ae1ce.png)

**To Reproduce**
1. Go to the tools library in XRMToolbox
2. Search for 'early'
3. Click on the checkbox to the right of EarlyBoundGenerator
4. Click the install button
5. See the "Installation Done!" message
6. Search again and see that EarlyBoundGenerator is not installed

**Expected behavior**
I expect EarlyBoundGenerator to install.

**Screenshots**
![image](https://user-images.githubusercontent.com/4343718/119691801-1c5ffa80-be08-11eb-84ba-61e94a9f67a1.png)

**Additional context**
I have tried this with a version of XRMToolbox that I installed via Chocolatey. When that didn't work I uninstalled that version and downloaded a new copy of XRMToolbox and installed it into a new folder. I also set the overridepath variable to place the plugins, connections, and other files into the same folder in case that was the cause of the issue. That configuration does not work either.

**Comment by daryllabar** [comment]
Also, I don't see the Early Bound Generator selected in the grid.  Any chance you forgot to do that, and the ToolBox said the install was done, rather than there was nothing to install?

**Comment by scottgolightly** [comment]
I was able to install other tools and the checkbox gets cleared when the success message appears.


There was an update to XRMToolbox today that had this as one of the fix items:

Bug fixes

Install of tools using subfolder content (Ribbon Workbench, Early Bound Generator, etc.) was corrupted and tools were not usable

I updated XRMToolbox and it still was unable to install into the plugin folder. I tried several different things including running XRMToolbox as an administrator. I eventually broke out process monitor and saw where the file was being downloaded from NuGet. I went to that file, made a copy, replaced the .DAT extension with .ZIP and then copied the files from the plugin folder in the zip into the plugin folder of XRMToolbox.
After restarting XRMToolbox it showed EarlyBoundGenerator as a tool and it is working for me. I can try a clean install or other steps if you would like to continue troubleshooting this issue but the manual install seems to be working for me.

**Comment by daryllabar** [comment]
Looks like there is some cleanup that was required.  https://twitter.com/XrmToolBox/status/1398146568751046658?s=19

For now I'm going to close this.  If it happens again, I think you'd be better served creating an issue in the XTB itself.
