### ISSUE TITLE
Convert String to Option Set Mapping file

### ISSUE THREAD

**Issue by MezMarianne** [daryllabar/DLaB.Xrm.XrmToolBoxTools#292]
Hi Daryl
I would like to Migrate Data and Convert Attribute Type from a string field to a global option set. When I do this, a Mapping File bar and button turns up. Do you have any guide to how the .cvs mapping file should be formatted?
Your YouTube video on this conversion omits the migrate data step.
Looking forward to saving lots of time.
Kind regards Marianne

**Comment by daryllabar** [comment]
It's a strict string to value conversion so if you have a text field with values:
- FL
- IN

And Option Set
- FL  with a value of 1
- IN with a value of 2

then your file should look like:
```
FL, 1
IN, 2
```

I'll warn you I implemented that feature in like 20 minutes, so I'd make sure that you've tested it in a non-prod environment before running it in prod.

**Comment by MezMarianne** [comment]
It works!

Beginning Step: Migrate Data To Temp
Retrieving Entity Count for account
Copying data from md_autodeploy to md_autodeploy_t_
Copying 1 / 18
Data Migration Complete. Total 18 records processed in 9 seconds.
Completed Step: Migrate Data To Temp
