### ISSUE TITLE
Attribute Manager: Local Option Set not Available

### ISSUE THREAD

**Issue by donalmc** [daryllabar/DLaB.Xrm.XrmToolBoxTools#301]
**Tool and Version**
What tool/version is it that you're reporting a bug for? i.e.
EarlyBoundGenerator V 1.2020.4.24
-- or --
AttributeManager V 1.2019.3.22

**Attribute Manager 1.2020.10.2**

**Describe the bug**

I want to use Attribute Manager to convert a local choice to a global choice, but the local choice is not available in the attribute list.
Thanks

**Comment by SpinnerWebs** [comment]
I'm not sure if I'm facing the same issue, but it seems similar. I successfully ran the tool in my Dev environment, then exported the solution via Pipelines to my Test environment (hoping in due course to do the same in Prod). I would have expected to have to run the tool again to migrate the data, but when I open the tool, none of the custom attributes are available to select. Am I missing something?

**Comment by daryllabar** [comment]
> I'm not sure if I'm facing the same issue, but it seems similar. I successfully ran the tool in my Dev environment, then exported the solution via Pipelines to my Test environment (hoping in due course to do the same in Prod). I would have expected to have to run the tool again to migrate the data, but when I open the tool, none of the custom attributes are available to select. Am I missing something?

Are you using Managed solutions in the Test Environment?  If so, did you just run the first step and create the new fields and add them to the solution, and then deploy?

**Comment by SpinnerWebs** [comment]
> > I'm not sure if I'm facing the same issue, but it seems similar. I successfully ran the tool in my Dev environment, then exported the solution via Pipelines to my Test environment (hoping in due course to do the same in Prod). I would have expected to have to run the tool again to migrate the data, but when I open the tool, none of the custom attributes are available to select. Am I missing something?
> 
> Are you using Managed solutions in the Test Environment? If so, did you just run the first step and create the new fields and add them to the solution, and then deploy?

Yes, in that the solution is unmanaged in the Dev environment, but becomes managed in Test because it's being deployed by Pipelines.

I ran all steps of the tool against the unmanaged solution in the Dev environment. I then deployed the solution to Test, but haven't been able to run the tool against the managed solution in Test.

**Comment by daryllabar** [comment]
@SpinnerWebs the tool can't make changes to the managed columns, so you'd have to run the tool in dev, and at each step, export out a solution, and then import each solution one at a time.  Now if you also want to migrate the data, you should be able to run the migration steps within the tool at each step, after you have imported the prior version of the solution. 

With that being said, I have never attempted this, and I'm wondering if I filter the columns to only show unmanned columns in the tool.  If that's the case I'll need to figure out how I want to allow that in the tool, and build a new version.

**Comment by SpinnerWebs** [comment]
> With that being said, I have never attempted this, and I'm wondering if I filter the columns to only show unmanned columns in the tool. If that's the case I'll need to figure out how I want to allow that in the tool, and build a new version.

@daryllabar This sounds promising. In my case, I don't think I need the tool to make any changes to the managed columns. Once the solution has been exported once from Dev, both old and new columns show up in Test (I'm using different names for old and new columns). All that would be needed, as far as I can see, is a way to to migrate the data between columns, and perhaps removing the filtering in the tool as you describe would be enough to permit this.

**Comment by SpinnerWebs** [comment]
@daryllabar Looking through the repo, it seems that there is indeed [filtering done in AttributeManagerPlugin.cs](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/blob/master/DLaB.AttributeManager/AttributeManagerPlugin.cs#L163) to only show unmanaged columns:

`var attributes = Metadata.Attributes.Where(a => 
                            !a.IsManaged.GetValueOrDefault() && 
                            a.AttributeOf == null && 
                            a.IsCustomizable.Value &&
                            !a.IsPrimaryId.GetValueOrDefault() &&
                            !IsBaseCurrency(a)).
                        Select(a => new ObjectCollectionItem<AttributeMetadata>((a.DisplayName.GetLocalOrDefaultText("N/A")) + " (" + a.LogicalName + ")", a)).
                        OrderBy(r => r.DisplayName).
                        Cast<object>().
                        ToArray();`

Presumably removal of the !a.IsManaged.GetValueOrDefault() filter would cause all columns to show up.

Aside from the above, there seems to be [only one place where IsManaged is checked](https://github.com/search?q=repo%3Adaryllabar%2FDLaB.Xrm.XrmToolBoxTools+path%3A%2F%5EDLaB%5C.AttributeManager%5C%2F%2F+IsManaged&type=code) - in the logic to delete mappings.
