### ISSUE TITLE
Missing Column Types

### ISSUE THREAD

**Issue by bennyboy23** [daryllabar/DLaB.Xrm.XrmToolBoxTools#302]
I am attempting to migrate a choice column into a choices column, but this option is not available to select in the list of attributes. Can the list of attribute types be updated to include this new ones?

Thanks,

---
- Deployment: Online
- DB Version: 9.2.21093.142
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.9.52
- Tool Version: 1.2020.10.2

**Comment by daryllabar** [comment]
It should be!  As a work around you could manually create the temporary field, then use the tool to migrate the attribute, and delete the existing attribute, and then manually create the correct attribute, and then use the tool to migrate the attribute.

**Comment by daryllabar** [comment]
Dup of #327
