### ISSUE TITLE
Missing System.Text.Json.dll in DLaB.Xrm.EarlyBoundGenerator.Api 

### ISSUE THREAD

**Issue by khoait** [daryllabar/DLaB.Xrm.XrmToolBoxTools#305]
**Tool and Version**
What tool/version is it that you're reporting a bug for? i.e.
DLaB.Xrm.EarlyBoundGenerator.Api v1.2021.12.12

**Describe the bug**
I tried to run CrmSvcUtil.exe from the downloaded DLaB.Xrm.EarlyBoundGenerator.Api v1.2021.12.12 nuget package, and got this exception: 
`System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
`
The tool in Early Bound Generator plugin in Xrmtoolbox works perfectly, so I tried to compare the difference between the two folders and saw some files in the plugin folder that are not in the nuget folder. Then I tried to copy each file from the plugin folder to nuget folder and try again until I found the file System.Text.Json.dll.

When I copy only one file "System.Text.Json.dll", it works normally.

**To Reproduce**
1. Download DLaB.Xrm.EarlyBoundGenerator.Api nuget package
2. Copy CrmSvcUtil.exe.config from Xrmtoolbox to the package folder.
3. Run command line to execute CrmSvcUtil.exe

**Expected behavior**
The tool should write generated files successfully without the exception.

**Screenshots**
<img width="842" alt="image" src="https://user-images.githubusercontent.com/8686497/146914462-36b06bfc-4132-4af8-b11e-0a98382b61f7.png">

**Comment by mariusso** [comment]
I am also experiencing this. Tried downgrading to 1.2021.10.6 and still get the same error. Did not go through the DLL's like you did, thank you for that @khoait . Hopefully it gets resolved soon.

**Comment by daryllabar** [comment]
Thanks for raising the issue!  I have added the missing dll to the nuget package
