### ISSUE TITLE
Performance improvements for LINQ related queries due to better stack usage for constructors with anonymous types

### ISSUE THREAD

**Issue by yulvision** [daryllabar/DLaB.Xrm.XrmToolBoxTools#306]
**Tool**
EarlyBoundGenerator, 1.2021.10.6

**Is your feature request related to a problem? Please describe.**
I have a lot of plugins to support where custom entities used with a lot of LINQ. 
Custom Entities.cs file generated is full of constructions like this:

/// Constructor for populating via LINQ queries given a LINQ anonymous type
/// <param name="anonymousType">LINQ anonymous type.</param>
[System.Diagnostics.DebuggerNonUserCode()]
public sfx_customentity(object anonymousType) : 
		this()
{
            **foreach (var p in anonymousType.GetType().GetProperties())**
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
                
             << skipped >>        
            }
}

**Describe the solution you'd like**
Performance improvements for LINQ related queries due to better stack usage will be 

[System.Diagnostics.DebuggerNonUserCode()]
public sfx_customentity(object anonymousType) : 
		this()
{
	   **var _Properties = anonymousType.GetType().GetProperties();
	   for (int i=0, N=_Properties.Length; i<N; ++i)
            {
		var p = _Properties[i];**
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
                
             << skipped >>        
            }
}

**Describe alternatives you've considered**
I would be happy with the settings flag to generate in current way (foreach) set to default, but one can change it to plain for loop instead.

**Additional context**
none

**Comment by daryllabar** [comment]
I don't see that change having any performance improvement..  educate me?

**Comment by daryllabar** [comment]
And if indeed one way is faster, I don't see any reason to keep the slower implementation.

**Comment by yulvision** [comment]
Daryl, actually, after more thoughts, I would agree with you, please ignore the case.
