### ISSUE TITLE
Can't define an output directory for generated entities

### ISSUE THREAD

**Issue by kirillkanyukov** [daryllabar/DLaB.Xrm.XrmToolBoxTools#308]
**Tool and Version**
EarlyBoundGenerator V 1.2021.12.12

**Describe the bug**
If "Create One File Per Entity" flag is checked, clicking on "Entity Relative Output Path" should open a dialog window which allow us to select a **directory** to store generated files, but instead of this we are allowed only to choose CS **file**.
If we aren't changing a default value of "Entity Relative Output Path", generated files are always located in "C:\" root folder instead of directory where settings file is located.

**To Reproduce**
1. Set "Create One File Per Entity" to "True"
2. Click on "..." at "Entity Relative Output Path" setting
3. See that "Choose file" dialog is opened instead of "Choose Directory"
4. Close dialog window
5. Click "Generate entities"
6. See that files are created in C:\ folder

**Expected behavior**
1. If "Create One File Per Entity" flag is checked, clicking on "Entity Relative Output Path" should open a dialog window which allow us to select a **directory** to store generated files
2. Generated files are located in the same folder (or subfolder) where settings file is located

**Screenshots**
![image](https://user-images.githubusercontent.com/1688331/148808166-12415094-54c0-4ede-83b1-4e0b231c8f1a.png)

**Additional context**
Description of "Entity Relative Output Path" is:
![image](https://user-images.githubusercontent.com/1688331/148808286-06baa7a0-4411-4eec-8b3c-8fa57efe6348.png)
But should it be vice versa? If "Create One File Per Entity" flag is checked we should choose directory for many files, if unchecked, we should define a name for single file

**Comment by mariusso** [comment]
You are correct, it is vice versa. The description for "Entity Relative Output Path" is bugged. I can't provide a test at the moment, becuase I have another issue at the moment where actions are not being generated.

**Comment by mqpsantiago** [comment]
Is there a way to make this work? I am also experiencing the same issues.

**Comment by daryllabar** [comment]
@mqpsantiago you can hand edit the EarlyBound Config file directly in your "XTB storage folder\Settings\DLaB.EarlyBoundGenerator_<environment>.xml" configuration file.

**Comment by daryllabar** [comment]
You could also hand edit the output path directly in the UI, without using the "..."  You can also create a C# file in the folder that you want to use, and select that.
