### ISSUE TITLE
Extra namespace for OptionSets

### ISSUE THREAD

**Issue by vasya-serega** [daryllabar/DLaB.Xrm.XrmToolBoxTools#309]
**Request:**
Add separate option to set different namespace for OptionSets

It'd be nice to have a possibility to set two different namespace for Entities and OptionSets

---
- Deployment: Online
- DB Version: 9.2.21114.136
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.12.53
- Tool Version: 1.2021.12.12

**Comment by daryllabar** [comment]
Any reason why?  This would be slightly annoying to implement since the Entities would have to know the namespace of the Option Sets.

**Comment by vasya-serega** [comment]
It makes project structure more clear for viewing when separate files are stored into separate folders. And files insides these folders have its own namespaces.

**Comment by daryllabar** [comment]
There is no requirement for sperate folders to be in separate namespaces.

**Comment by daryllabar** [comment]
I don't think the effort justifies the change.  Feel free to add to your reasoning, or submit a PR.
