### ISSUE TITLE
Optionset Prefix for Invalid Names not working

### ISSUE THREAD

**Issue by JumpConsultancy** [daryllabar/DLaB.Xrm.XrmToolBoxTools#31]
When I generate an optionset.cs file the prefix that I added for an invalid name is not being applied to the enum value

**Comment by daryllabar** [comment]
Can I get your DLaB.EarlyBoundGenerator.Settings.xml file, and your CrmSvcUtil.exe.config file?

**Comment by daryllabar** [comment]
I just tested this, and it's working for me.

**Comment by daryllabar** [comment]
Unable to Reproduce
