### ISSUE TITLE
Add option to mark all attributes as nullable (C# 8.0)

### ISSUE THREAD

**Issue by randombyte-developer** [daryllabar/DLaB.Xrm.XrmToolBoxTools#311]
**Tool**
EarlyBoundGenerator

**Is your feature request related to a problem? Please describe.**
I am using C# 8.0 which has nullable reference types [link to docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types). Right now, only primitive types are marked as nullable. I don't get the null-safety from the generated classes because an `EntityReference` can be null, although it is not marked as nullable.

**Describe the solution you'd like**
It would be cool if there was an option to mark all attributes as nullable, e.g. `EntityReference` becomes `EntityReference?`.

**Describe alternatives you've considered**
Running a script after generating the classes. That script would just add `?` for all attributes.

**Comment by randombyte-developer** [comment]
Related discussion: https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Early-bound-Entity-with-nullable-attributes/m-p/1508971#M6025

**Comment by daryllabar** [comment]
I love this idea and will look to implement when I have time.

**Comment by daryllabar** [comment]
It took two years...

**Comment by randombyte-developer** [comment]
@daryllabar Very appreciated, thanks. Now I have a reason to move to V2 :)
