### ISSUE TITLE
`Action.cs` is added to the .csroject file, even if it was deleted by `CustomCodeGenerationService.WriteInternal`

### ISSUE THREAD

**Issue by vandenberghev** [daryllabar/DLaB.Xrm.XrmToolBoxTools#313]
EarlyBoundGenerator v1.2022.2.4

The `Action.cs` keeps getting added to the `.csproj` file, even if it does not exist.
It's explictly deleted in `CustomCodeGenerationService` because `CreateOneFilePerCodeUnit && string.IsNullOrEmpty(CommandLineText)`.

![image](https://user-images.githubusercontent.com/26387795/161564011-976fe9dc-cbfd-47f6-9f67-96311920a070.png)

![image](https://user-images.githubusercontent.com/26387795/161564754-8962b34a-6df2-4485-9306-2b97efdfec9c.png)

This makes the build fail because `Actions.cs` was obviously not found.

```
Begin Reading Metadata from MetadataProviderService
Completed Reading Metadata from MetadataProviderService - 00:01:11.1903904
Begin Writing Code File
 Ensuring Context File is Accessible 
 Writing file Actions.cs to C:\Users\MY_USER\AppData\Local\Temp\tmpFD47.tmp 
	Processing 227 OptionSets
	Wrote 0 OptionSets - 00:00:00.0006590
	Processing 1011 Entities
	Wrote 0 Entities - 00:00:00.0026671
	Processing 877 Messages
	Wrote 513 Messages - 00:00:00.0370037
	Code written to C:\Users\MY_USER\AppData\Local\Temp\tmpFD47.tmp.
 Deleting *.cs Files From C:\MY_DIR\Models\Actions\Actions.cs By Code Unit 
 Finished Deleting *.cs Files From C:\MY_DIR\Models\Actions\Actions.cs By Code Unit 
 Splitting File C:\MY_DIR\Models\Actions\Actions.cs By Code Unit 
C:\MY_DIR\Models\Actions\Actions.cs added to project.
 Cleaning up Temporary File C:\Users\MY_USER\AppData\Local\Temp\tmpFD47.tmp 
 C:\Users\MY_USER\AppData\Local\Temp\tmpFD47.tmp Moved To: C:\MY_DIR\Models\Actions\Actions.cs 
Completed Writing Code File - 00:00:00.0759628
**Output file was not updated or not found!  C:\MY_DIR\Models\Actions\Actions.cs**
Creation Complete!
```

**Comment by daryllabar** [comment]
So the logic to add the actions.cs file to the project, is not taking into account that it was deleted.  Is that it?

**Comment by vandenberghev** [comment]
@daryllabar I check your fix, I think the `!` should be dropped in `!FilesNotToAdd.Contains(path)`?

![image](https://user-images.githubusercontent.com/26387795/161576505-b15c76e0-07dc-44fe-ac6a-e76cf203b0ef.png)
