### ISSUE TITLE
Error in audio device

### ISSUE THREAD

**Issue by sveco** [daryllabar/DLaB.Xrm.XrmToolBoxTools#32]
Our dev machine has no audio devices (it is virtual anyway). Please remove speech synthesis reference: wile nice, this is rather irrelevant for generating code.

System.Speech.Internal.Synthesis.AudioException: Audio device error encountered. - Error Code: 0x2
   at System.Speech.Internal.Synthesis.VoiceSynthesis.Speak(Prompt prompt)

**Comment by daryllabar** [comment]
Agreed.  I'll add a flag to enable this, and set it to disabled by default.
