### ISSUE TITLE
Order settings a bit better

### ISSUE THREAD

**Issue by rappen** [daryllabar/DLaB.Xrm.XrmToolBoxTools#321]
Call the names of the Groups in the settings like this:

```
1. Global
2. Entities
3. Option Sets
4. Actions
8. Meta
9. Debug
```

Now everything starts with Actions. Why why? And then Debug??
The tool you use sort by name... A bit nicer?

---
- Deployment: Online
- DB Version: 9.2.22044.142
- Connection Controls Version: 1.2022.5.50
- XrmToolBox Version: 1.2022.4.55
- Tool Version: 1.2022.5.3

**Comment by rappen** [comment]
Can you collapse them? I haven't seen that...
I know the order is alphabetical, that's why I suggest you name the groups like this 👆 with a number too.

Maybe all users you already have will be annoying that the rearranging is in the new version... maybe that's bad.

**Comment by daryllabar** [comment]
This will come out with #352
