### ISSUE TITLE
OptionSet file not generated

### ISSUE THREAD

**Issue by gvc55** [daryllabar/DLaB.Xrm.XrmToolBoxTools#326]
Hello there! I am not sure in what version this started happening but I do not refresh these classes very often (perhaps once every couple of months).  The issue is the last two or three times I refreshed my entity list, I noticed that the Option Sets are not been generated. I have a project that contains a file per entity selected and I specified a single file for all Option sets. As of lately, the entities continue to generate fine, but the OptionSet file shows as deleted in my Git Changes tree. If the entities do not change much, I have just reverted the deletion and life is good again, but this last time I added a few entities to the list and reverting the OptionSet does not cut it anymore; I have to add the options manually.  Anyway, any ideas on how to solve this issue will be greatly appreciated.  Here a little snippet of the tool's output.

_Begin Writing File
 Ensuring Context File is Accessible 
 Writing file OptionSets.cs to C:\Temp\1\tmpACEA.tmp 
Processing 154 OptionSets
Wrote 105 OptionSets
Processing 628 Entities
Completed Reading Metadata 00:00:41.3507178
Begin Writing File
 Ensuring Context File is Accessible 
 Writing file OBOServiceContext.cs to C:\Temp\1\tmpADC5.tmp 
Processing 154 OptionSets
Wrote 0 OptionSets_

On the one hand the tool writes 105 option sets, but then it says it wrote 0. I wonder if one step overrides the other.

Thanks in advance for any assistance.

---
- Deployment: Online
- DB Version: 9.2.22053.148
- Connection Controls Version: 1.2022.5.50
- XrmToolBox Version: 1.2021.12.53
- Tool Version: 1.2022.5.3

**Comment by daryllabar** [comment]
@gvc55 What are your settings for Option Sets?
![image](https://user-images.githubusercontent.com/9728423/176329968-4ca8cf74-997b-4c6d-899b-e8e7625292da.png)
as well as your Global settings?
![image](https://user-images.githubusercontent.com/9728423/176330034-be9a4558-b2b8-46a4-93ec-393a94f7e836.png)

**Comment by gvc55** [comment]
Thanks you for replying so fast. I wish I could've answered you right away but I've putting out a few fires for the past 3 days. Anyway, answering your request, here are the settings I am using.

![Capture](https://user-images.githubusercontent.com/64438054/176751176-ff4625e9-7cf0-4599-b06e-ee544fa6ad0e.PNG)

![image](https://user-images.githubusercontent.com/64438054/176751371-ac5874e1-153f-432b-9642-bc005187772b.png)

**Comment by gvc55** [comment]
Hello Daryl,
Any resolution on this issue? I needed to refresh the Early Bound classes and, once again, the OptionSets are removed. Here is a snapshot of my Git Changes view in Visual Studio.
![OptionSets Capture](https://user-images.githubusercontent.com/64438054/179777285-1af61af1-d5da-4e05-b2a3-ca3510933644.PNG)

**Comment by gvc55** [comment]
Hello Daryl,
I started a new project a couple of weeks ago and the entire set of entities and Options set were generated as expected. That went on for 2 or 3 regenerations until yesterday that the Options Set file started to not be generated as noted earlier. Nothing in the settings changed, other than adding a new entity to the list, but this morning I tried to see if this was a matter of me having the Options Set file opened in Visual Studio, and voilà, the Options Set file generated perfectly. Could this be the issue all along? If this is the case, I am confused because all the other entity files get regenerated correctly even if I have them open in VS. Am I missing something? Thanks in advance for any input in this.

**Comment by daryllabar** [comment]
Wait, having the file open in VS caused is to get generated correctly?  If you didn't have it open, it would get deleted and not generate?

**Comment by gvc55** [comment]
I cannot say for sure but it looks that way. The file will appear as deleted from solution. I will to try a more times to verify and unfortunately I am swamped right now and cannot promise to look into it right away. But will keep you posted.Sent from my iPhoneOn Dec 15, 2022, at 6:21 AM, Daryl LaBar ***@***.***> wrote:﻿
Wait, having the file open in VS caused is to get generated correctly?  If you didn't have it open, it would get deleted and not generate?

**Comment by gvc55** [comment]
Correction, having it open does not generate the file. Sent from my iPhoneOn Dec 15, 2022, at 6:21 AM, Daryl LaBar ***@***.***> wrote:﻿
Wait, having the file open in VS caused is to get generated correctly?  If you didn't have it open, it would get deleted and not generate?

**Comment by daryllabar** [comment]
I have a feeling #352 will resolve this when it goes live.
