### ISSUE TITLE
Integrated login for EarlyBoundGenerator

### ISSUE THREAD

**Issue by Power-Maverick** [daryllabar/DLaB.Xrm.XrmToolBoxTools#339]
Would love to see an enhancement for EBG where I do not have to login every time; especially when I want to use the "generate all" button. It will make our life easier if you can find a way to integrate with XTB's connection to authenticate. 

---
- Deployment: Online
- DB Version: 9.2.22091.212
- Connection Controls Version: 1.2022.7.53
- XrmToolBox Version: 1.2022.5.56
- Tool Version: 1.2022.5.3

**Comment by daryllabar** [comment]
@Power-Maverick it is supposed to do that, as long as you save your password in the connection XML.  It only falls back to that if it fails.  I've also seen Application User Accounts be used to much success as well.

**Comment by Power-Maverick** [comment]
I was already connected to an environment using MSFT Login Control; so are you saying it doesn't work when we use that type of connection?

**Comment by daryllabar** [comment]
What do you mean, "already connected"?  The EBG shells out to the crmsvcutil via a command line under the covers since the crmsvcutil does not allow accepting an IOrganzationSevice

**Comment by skfd** [comment]
found this issue too. Don't quite understand how to persist login when our org uses 2fa.

Also, for some reason, terminal windows that can not be closed appear for me.

**Comment by daryllabar** [comment]
This will be resolved when #352  goes live.  If you want to start using an alpha version, let me know
