### ISSUE TITLE
IDEA: Ignore publisher prefix (Ex. `SchoolLevel.cs` instead of `mshied_SchoolLevel.cs`.)

### ISSUE THREAD

**Issue by skfd** [daryllabar/DLaB.Xrm.XrmToolBoxTools#348]
**Tool**
EarlyBoundGenerator 1.2022.9.22
 

**Is your feature request related to a problem? Please describe.**
Would love to have a cleaner class names. Ex. `SchoolLevel.cs` instead of `mshied_SchoolLevel.cs`.

**Describe the solution you'd like**
Another settings flag, I guess!

**Describe alternatives you've considered**
Difficult to do it just by text replace, so I see no alternative.

**Comment by daryllabar** [comment]
This would be a fairly simple change in the INamingService.  I may consider it in the future after #352 goes live.

**Comment by daryllabar** [comment]
Is this just for the class names, or for properties and enums as well?  How would you suggest to handle conflicting names?

**Comment by skfd** [comment]
I was thinking it should apply to everything. For conflicting names it can stay prefixed. On second thought it's a very feature-creepy feature. I wonder if other people would even use it...

**Comment by daryllabar** [comment]
I want to remove the possibilities of naming collisions as much as possible, so this won't be implemented
