### ISSUE TITLE
"member names cannot be the same as their enclosing type" with generated Actions

### ISSUE THREAD

**Issue by bwmodular** [daryllabar/DLaB.Xrm.XrmToolBoxTools#349]
**Tool and Version**
EarlyBoundGenerator V 1.2022.9.22

**Describe the bug**
Hi @daryllabar,
this is not a bug in the earlyBoundGenerator as such, but an issue that's started occuring with it recently and I wonder if you had any thoughts on what could be causing it or how to prevent it.
As of sometime over the last couple of months I've started getting a compilation error against my Actions class when generated against a D365 online instance.
msdyn_ActivateWorkflowResponse: member names cannot be the same as their enclosing type:
![image](https://user-images.githubusercontent.com/1889586/222712178-a1e166cf-b0c0-4564-8873-818d7e4e9f83.png)

I can resolve the issue by setting up a whitelist which only includes the actions I require (which I should obviously be doing anyway) but the msdyn_ActivateWorkflowResponse itself doesn't even show up in the list of available actions in the Whitelist selector.
![image](https://user-images.githubusercontent.com/1889586/222712353-8851dfb6-cfd3-4591-86fe-c598b88328ad.png)

As I said, this isn't an EBG bug - do you think it's a bug in svcUtil which should be reported to Microsoft?

**To Reproduce**
Generate Actions using EBG against a D365 Online instance without creating a Whitelist.

**Expected behavior**
The resulting class should compile without error

**Comment by daryllabar** [comment]
It's a API, not a Custom Action, and I have an outstanding issue to include APIs as well.  For now you can manually add it via the Workflowless Actions:
![image](https://user-images.githubusercontent.com/9728423/222734432-0393be5d-e162-4813-946d-15b3ffecc15b.png)

I'm looking to upgrade the EBG to the new Microsoft dll.  We'll see if that type of issue gets resolved, or if I have to write some additional code to handle that...
