### ISSUE TITLE
Early Bound Generation - url / domain / user info not provided for onprem connection

### ISSUE THREAD

**Issue by claym** [daryllabar/DLaB.Xrm.XrmToolBoxTools#35]
I'm using an on premises connection and trying to run the early bound connection against it.

The utility doesn't seem to be providing the /url, /domain, /user, or /password to the crmsrvutil, which is causing it to fail.

If I run the generated command manually and provide the missing options, it will run and generate my classes. This is a decent workaround, though I can't use some of the functionality such as specifying which classes to map.

Is there anything I might be missing?

**Comment by daryllabar** [comment]
It should be creating all those values.  Are you entering in a User name and password when connecting with the XTB (XrmToolBox), or are you just using AD?  If your connection to CRM using the XTB is just AD, then it attempts to utilize a ConnectionString parameter.

**Comment by claym** [comment]
Looks like that was it. If you manually specified the authentication info, it works.

**Comment by daryllabar** [comment]
I don't have access to your User Id and Password, so I say this is working as desired.
