### ISSUE TITLE
Related to "OptionSet Attributes Are Getting Generated as Objects Not OptionSetValues"?

### ISSUE THREAD

**Issue by ClintWoods** [daryllabar/DLaB.Xrm.XrmToolBoxTools#359]
Hey @daryllabar. This client is still on prem. EBG V1.2022.9.22. I guess crmsvcutil is the version installed with EBG as it's relative path is  DLaB.EarlyBoundGenerator\crmsvcutil.exe.  I am setting up an API for them and notice when I try to set OSV's the traditional way, with a 'new optionsetvoud(int)', it complains at compile time. Any ideas?

      if (int.TryParse(temp, out i))
      {
           er.bua_WOState = new OptionSetValue(i); // doesn't work       <---------------------
           er.bua_WOState = bua_wostate.Unassigned; //works but not desirable...
       }
thx,
clint

**Comment by daryllabar** [comment]
Try setting both of these to false:
![image](https://user-images.githubusercontent.com/9728423/226436678-90585050-30d1-42ff-8fd7-793ed27325af.png)

**Comment by ClintWoods** [comment]
That's it @daryllabar. Thanks! I was looking thru the settings under "OptionSets" for something like that instead of the right place. Appreciate the SUPER quick response!
