### ISSUE TITLE
Selecting Optionsets to skip

### ISSUE THREAD

**Issue by SigrunO** [daryllabar/DLaB.Xrm.XrmToolBoxTools#36]
Isn't there a way to cherry pick the option sets I want to generate opposed to the list of the ones I want to skip? It seems extremely tedious to generate the negative list, since I have to go through a dialog for every singele option set I want to skip and the list is long.

**Comment by daryllabar** [comment]
Two options I can think of... 

1. Hand edit the XML that gets created to add everything you don't want (yuck).

2. Select the option to split the OptionSets into one per file, then delete the ones you don't want.

Another option that isn't available currently, would be to allow using a solution as a way to define what you want to create.  So you can just add the entities, and option sets, and actions to a solution that you'd like to generate, then I'd add a way to select a solution from the tool, and only the things in the solution would be generated.  Would that be beneficial?

**Comment by SigrunO** [comment]
The solution version seems best and most beneficial. I'd prefer a positive list rather than a negative list for both entities and option sets. Everytime a new Entity/OptionSet is added that is not needed for the plugin forces the user to update the negative list, rather than adding necessary entities / option sets when they are really needed.

**Comment by daryllabar** [comment]
I'll look at adding the ability to select a Solution to determine what Entities / Option Sets are generated.

**Comment by daryllabar** [comment]
I've decided that using the Entities to determine if the OptionSet is needed is a better approach.  Let me know if this doesn't work for you.

**Comment by SigrunO** [comment]
That sounds good to me. Thanks!

**Comment by daryllabar** [comment]
This is now live in the latest version of the EBG
