### ISSUE TITLE
Early Bound Generator doesn't generate one of the Custom APIs anymore

### ISSUE THREAD

**Issue by Mihails-Simvulidi** [daryllabar/DLaB.Xrm.XrmToolBoxTools#363]
I have an issue with the Early Bound Generator. I have two Custom APIs which are bound to an entity, they are specified both in Workflowless Actions and in Actions Whitelist. The only differences between them are:
- one has an input parameter and other doesn't;
- one is bound to a standard entity and other - to a custom entity.

In August 2022 they both were generated but now only one which is bound to a standard entity and has an input parameter is generated. I don't have a permission to post the configuration, generated files and other necessary information in public but I can send them to the developer privately.

---
- Deployment: Online
- DB Version: 9.2.23023.184
- Connection Controls Version: 1.2022.10.54
- XrmToolBox Version: 1.2023.2.64
- Tool Version: 1.2022.9.22

**Comment by Mihails-Simvulidi** [comment]
As the current version is released in September 2022, probably the previous one - V1.2022.5.3 as I regularly update all the tools.

**Comment by daryllabar** [comment]
It's kind of a process.

Download the project and get it to build (you just need the DLaB.CrmSvcUtilExtensions project to build/debug)
Replace the DLaB.CrmSvcUtilExtensions in the CrmSvcUtil.exe folder
There is a flag in the "debug" section to wait for a debugger to be attached, so enable that.
Run the EBG for just the actions
Attach to the CrmSvcUtil.exe

**Comment by Mihails-Simvulidi** [comment]
Sorry, it seems to be a Microsoft issue - CrmSvcUtil and pac modelbuilder doesn't generate this as well.
