### ISSUE TITLE
Option set on model class specifies wrong enum name for global option sets

### ISSUE THREAD

**Issue by polshgiant** [daryllabar/DLaB.Xrm.XrmToolBoxTools#37]
I have an entity with a global option set on it.  Here's the property that gets generated for it:

```csharp
[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("xyz_addressescode")]
public virtual xyz_DynamicOptionSet? xyz_AddressesCodeEnum
{
    // ...snip...
}
```

Here's the enum for the global option set:
```csharp
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.0.1.7297")]
public enum xyz_DynamicOptionSetEnum
{
    // ...snip...
}
```

These don't link together correctly because the enum is called `xyz_DynamicOptionSetEnum` whereas the type of the property is `xyz_DynamicOptionSet?`.  Either the return type of the property should be `xyz_DynamicOptionSetEnum?` or the global option set shouldn't have the `Enum` suffix.

This seems to only be an issue for global option sets.  I'm using 1.2016.3.30, but this is not a new problem. 

Great tool, cheers.

**Comment by daryllabar** [comment]
The Enum itself shouldn't have "Enum" post-fixed to it.  What is the actual display name of the Global Option Set?

**Comment by polshgiant** [comment]
Hey Daryl, sorry for the delay.  The display name of the global option set it "Dynamic Option Set".

**Comment by polshgiant** [comment]
Hey Daryl, sorry for the delay.  The display name of the global option set is "Dynamic Option Set".

**Comment by daryllabar** [comment]
I believe I have a fix.  Can you download this file: https://drive.google.com/file/d/0B0By9PBv_3cDb1QtTU5SblZVaG8/view?usp=sharing
and use it to replace the file found in EarlyBoundGenerator\Plugins\CrmSvcUtil Ref, and then rerun your entities and make sure it resolves the issue?

Thanks.

**Comment by polshgiant** [comment]
Yeah I'll give it a whirl tomorrow or this weekend.

**Comment by polshgiant** [comment]
Great success!  For the first time my entire solution successfully built immediately after regenerating without having to make manual adjustments, thanks!
