### ISSUE TITLE
Select publisher prefix to skip

### ISSUE THREAD

**Issue by LeszekSzejka** [daryllabar/DLaB.Xrm.XrmToolBoxTools#38]
I think nice enhancement could be (additionaly to picking up optionSets/entities to skip while generating) will be add an option to pick publisher prefixes, eg. msdyn_ to ship. Adding manually all 3rd-party entities to excluded list is annoying.

**Comment by daryllabar** [comment]
So you want to be able to skip all entities with a certain prefix "msdyn" or maybe "new_"?

**Comment by LeszekSzejka** [comment]
Basically any available in the system prefix: new_, msdyn_, myprefix_, etc.: many managed solution adds plenty of entities which are not needed during earlybound generation process
