### ISSUE TITLE
Exception when adding Actions to skip (opening window "Specify Actions")

### ISSUE THREAD

**Issue by LeszekSzejka** [daryllabar/DLaB.Xrm.XrmToolBoxTools#39]
DLaB.Common.Exceptions.TypeArgumentException: 'Entity' is an invalid type for T.  Please use the LateBoundQuerySettings.
   at DLaB.Xrm.QuerySettings`1..ctor()
   at DLaB.Xrm.QueryExpressionFactory.Create[T](ColumnSet columnSet, Object[] columnNameAndValuePairs)
   at DLaB.XrmToolboxCommon.DialogBase.<RetrieveActions>b__13_0(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by daryllabar** [comment]
What dialog are you opening to generate this error?

**Comment by LeszekSzejka** [comment]
![image](https://cloud.githubusercontent.com/assets/13485243/14814897/9b8f95f8-0ba8-11e6-8eb8-5904b71c7397.png)

**Comment by daryllabar** [comment]
I'm guessing you haven't hand edited the EarlyBoundGenerator settings XML file?

**Comment by LeszekSzejka** [comment]
I did, but reverted to original one with the same exception unfortunatelly

**Comment by daryllabar** [comment]
This will be fixed with the next Release

**Comment by LeszekSzejka** [comment]
Thx Daryl for a quick reaction. Pro.

**Comment by daryllabar** [comment]
Don't start singing your praises, until you see how quick your other requests will take!

**Comment by LeszekSzejka** [comment]
If you need any help with the other ones let me know. Can implement them at some dedicated feature branch.

**Comment by daryllabar** [comment]
I've got the pre-fix skipping partially done.  I was going to use this: https://community.dynamics.com/crm/b/mscrmshop/archive/2012/04/28/extending-crmsvcutil-part-2 to help limit what entities/optionsets are created to those contained within a solution...  You're welcome to Fork my repository, and make the changes require, and do a pull request.

**Comment by LeszekSzejka** [comment]
What partially done means :) If so please push changes to github not to
double your work.
