### ISSUE TITLE
The Updated Settings Are Not Reflected Immediately Until the XrmToolBox is Closed And Reopened

### ISSUE THREAD

**Issue by LinnZawWin** [daryllabar/DLaB.Xrm.XrmToolBoxTools#390]
**Tool and Version**
EarlyBoundGenerator V 2.2023.4.4

**Describe the bug**
After updating the settings and clicking on Generate button will generate the files with the old settings at the point of opening the XrmToolBox.

**To Reproduce**
1. Open XrmToolBox
2. Open Early Bound Generator V2
3. Click on the "Generate" button with the Entities Whitelist default settings (which has x7 entities)
4. Check the Entities folder in the output folder and those x7 entities from the default settings will be found
5. Change the "Delete Files From Output Folders" setting under **Global** to **True**
6. Change the "Entities Whitelist" setting by removing all default x7 entities and adding "AAD User" and "Account" entities.
7. Click on the "Generate" button again
8. Check the Entities folder in the output folder and the same x7 entities from step 4 can be found.
9. Close and re-open the XrmToolBox
10. Open Early Bound Generator V2
11. Click on the "Generate"  button
12. This time, only the "AAD User" and "Account" entity classes are found in the Entities folder in the output folder

**Expected behavior**
At step 8, only the "AAD User" and "Account" entity classes should be in the Entities folder as in step 12 without reopening the XrmToolBox

**Screenshots**
![image](https://user-images.githubusercontent.com/14156926/230177573-0bcd05a5-f023-413f-a192-5c08805c1060.png)

**Additional context**
The workaround solution is to re-opening the XrmToolBox after updating the settings. Even duplicating the tool and opening a new tab does not work.

**Comment by daryllabar** [comment]
Oh joy.  MS is caching something in an internal non public static dictionary that I can't clear without reflection...
