### ISSUE TITLE
ProxyTypesAssemblyAttribute is generated multiple times on each entity class

### ISSUE THREAD

**Issue by jarvan-jiang** [daryllabar/DLaB.Xrm.XrmToolBoxTools#408]
**Tool and Version**
What tool/version is it that you're reporting a bug for? i.e.
EarlyBoundGenerator V 2.2023.4.17

**Describe the bug**
When use generator V2, and set 'Create one file per entity' to true, the class is generated correctly, but each class file contains 
`[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]`
And this lead to compiler error CS0579.

**To Reproduce**
1. open EarlyBoundGenerator V2
2. set  'Create one file per entity' 
3. generate 

**Expected behavior**
Entity class generated and able to compile success. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4934690/233823489-7e6df637-815b-4992-974e-4cd645c4e440.png)

**Additional context**

**Comment by jarvan-jiang** [comment]
After looking at code, seems the logic of `PacModelBuilderCodeGenHack` when generating code is fine, the `SplitFilesByObject` is set default as `true` so all the single class will not have proxy type attribute.
However, after that there are some paragraph seems processing merge or split, will call `WriteFileWithoutCustomizations`, it will re-add the proxy type attribute to all files.
If I understand correctly, we have added the proxy type attribute to service context, therefore there is no need to re-add it to any class except the service context is not provided(which you already have a section to handle that remind user to added it manually, also there seems have a small issue on that).

Based on above investigation, I think the default value of parameter `writeProxyAttrib` in `WriteFileWithoutCustomizations` should be false instead of true. I have created a PR, please kindly look at it if I misunderstand some stories.

**Comment by jarvan-jiang** [comment]
Sure, I removed some sensitive names and namespace, but the settings are same as I'm using.
[builderSettings - Copy.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/11315723/builderSettings.-.Copy.zip)

**Comment by daryllabar** [comment]
Thank you!  I was able to determine that the issue you're experience is due to you having separate files for entities, but not for OptionSets.  Fix has been pushed to nuget, will push to the XTB soon

**Comment by daryllabar** [comment]
2.2023.4.24 should be pushed

**Comment by jarvan-jiang** [comment]
Appreciate your quick action!

**Comment by daryllabar** [comment]
And I appreciate getting the JSON file and for spending the time to do a PR!

**Comment by JepperJay** [comment]
Hi
I have sort of the same issue using 2.2023.4.24.
When I generate a single file for entities and a single file for optionsets, both the service context and the file with the entities contains [assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

**Comment by daryllabar** [comment]
@JepperJay can you send me your builder settings Json file?

**Comment by JepperJay** [comment]
Here you go, and thanks a lot
[builderSettings.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/11451021/builderSettings.zip)

**Comment by daryllabar** [comment]
@jarvan-jiang You are setup to not create a service context, do you manually add your own Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()?  Or do you just not have one at all?

**Comment by jarvan-jiang** [comment]
> @jarvan-jiang You are setup to not create a service context, do you manually add your own Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()? Or do you just not have one at all?

I manually add it in other place, if setup to not create service context, there will no one at all.
At that time, the code logic looks like, if I'm not going to create a service context, then no attribute will be generated, instead an alert will appeared to user, says that you need add the attribute by yourself. However, the decompile code seems went wrong, the alert branch will never be hit.
That's why I try to modify it in my PR.
