### ISSUE TITLE
Difficulties with Connection to Online Sandbox + resolution

### ISSUE THREAD

**Issue by craigseymour** [daryllabar/DLaB.Xrm.XrmToolBoxTools#41]
I connected to my organization's O365 Online CRM sandbox today for the first time in months, and couldn't connect, with the SvcUtil throwing "System.Exception: Connection to CRM is not established. Aborting process."  This despite a successful connection for other plugins in the Toolbox.

After reading various posts on similar issues, I found the workaround is to switch the command line's /url parameter (or the `<OrganizationServiceUrl>` value in the mscrmtools2011.config file) for one using the org unique name instead of the friendly name:

- original: /url:"https://**friendlysandbox**.api.crm4.dynamics.com/XRMServices/2011/Organization.svc"
- new: /url:"https://**org1234abcd**.api.crm4.dynamics.com/XRMServices/2011/Organization.svc"

I'm not sure whether this is a problem with how the `<OrganizationServiceUrl>` is stored at the Toolbox level, or the plugin needs to deal with fudging the URL to allow the SvcUtil tool to work, but I hope the workaround is useful for someone in the meantime.

**Comment by daryllabar** [comment]
I believe this to be a either a bug in the  XrmSvcUtil.  I'm using it to actually do the query and connection to CRM.  I believe that the XrmToolBox has figured out a work around for it.  I'll see what I can do to determine the unique Org Url, and use that instead...

**Comment by craigseymour** [comment]
Sounds good.  Thank you.

**Comment by daryllabar** [comment]
Talked with Tanguy.  Apparently he is just doing a discovery query and using the unique org URL.  I should be able to do the same thing.  It may take me a week or two to find the time to fix this.

**Comment by daryllabar** [comment]
I have this working locally.  Have a few other bug fixes I want to get to before rolling out a new release.

**Comment by daryllabar** [comment]
Closed with version 2016.5.25
