### ISSUE TITLE
Cannot Set "Local  Option Set Format "

### ISSUE THREAD

**Issue by BrettBailey** [daryllabar/DLaB.Xrm.XrmToolBoxTools#410]
I'm regenerating entities on a long-established project using a fresh install of xrmtoolbox & EarlyBoundGenerator on a new laptop. I'm using EarlyBoundGenerator V 1.2023.2.64

To fit with previously generated code I need the options sets for  enum names to generate in pascal case without the underscore Seperator between The Entity and OptionSet name. This can be controlled by setting "Local Option Set Format" to "{0}{1}".

The bug is that the setting defaults to "{0}_{1}" and that "Local Option Set Format" is hidden from the settings pane unless and cannot be edited. 

Changing "Use Deprecated Option Set Naming" to True causes "Local Option Set Format" to appear in settings.  To get the format I need, I must then edit the setting to "{0}{1}" And Turn Deprecated Naming Back off again.

**Comment by daryllabar** [comment]
Does it work in the Early bound Generator V2?  It's a different tool entirely.  I'm trying to retire the older V1 tool

**Comment by BrettBailey** [comment]
Hi Thanks for getting back to me, much appreciated

I think I must have given you the xrm toolbox version number earlier!  this is in Early Bound version 1.2022.9.22.   I've just checked v2 and it does show the Local Option Set Format right away!  I've tried generating and it only got 7 of the 660 entities and none of the option sets.  This is likely user error as I've not read the docs for V2 at all, just opened it and ran it.

I can use the entities I generated yesterday with V1 for now and I will switch to V2 on the next regen. 

Thanks again for a great tool :-)

**Comment by daryllabar** [comment]
Are you loading the V1 settings file from V2?  It should update for you and should "work".  It is recommended that you don't generate everything, which is what it looks like you're doing.  White list it, and your generation time will be much more efficent.

**Comment by BrettBailey** [comment]
I didn't load the v1 settings, I will do that, thanks for the tip.  I also saw the note about adding the setting to source control!
I do generate almost everything (I use the blacklist & blacklist prefix) and build it into a nuget package which is shared by many small projects. It really helps with uptake and consistency, but I must be careful the names don't change when regenerating.

It does take a little while to generate, but it's getting faster all the time :-)
