### ISSUE TITLE
Output to designer.cs

### ISSUE THREAD

**Issue by VanHinthem** [daryllabar/DLaB.Xrm.XrmToolBoxTools#412]
**Tool**
What tool/version is it that you're making a feature request for? i.e.
EarlyBoundGenerator

**Describe the solution you'd like**
Would it be possible to create an option where the EarlyBoundGenerator would write the output to designer.cs files ?

**Comment by daryllabar** [comment]
What is outputting it to a designer.cs file do?  Is that just trying to output it to a single file with that name, or is there more to it?

**Comment by VanHinthem** [comment]
You get an output like:

File:

Account.designer.cs

namespace example
{
	
	public partial class Account : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
              etc...
	}
}

And the Account.cs

namespace HDS.Dynamics.DataMask
{
public partial class Account
{
}
}

When generating check if account.cs exists, if not create it. In this way you get a separation of code generation and custom extensions and methods ...

**Comment by daryllabar** [comment]
So this is a trick in the project file itself, where it describes the files as nested.  You can manually do this yourself, or, (what I do) just create another folder called "Partials" and put your custom code in there.  Just make sure the namespace is the same, and the partial classes will get combined at compile time.
