### ISSUE TITLE
Generated by comment

### ISSUE THREAD

**Issue by MatteoVeronesi22** [daryllabar/DLaB.Xrm.XrmToolBoxTools#414]
**Tool and Version**
EarlyBoundGenerator V 2.2023.4.24

**Describe the bug**
I'm looking for an option to remove the "Generated by" part presente in every file.
Different developers use the same tools to generate classes but sometime this part is generated in different languages. 
It seems based on the main language of the OS.

![Immagine 2023-05-25 114044](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/105710142/b9a9ef1c-1cb7-428c-8091-367e50359b11)

**To Reproduce**
Changing the "Generate the \"Generate by\" Header" option doesn't create changes

**Expected behavior**
Remove this comment

![Immagine 2023-05-25 114135](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/105710142/0aca23da-07f2-4fa0-ba3c-e14a9cb080f3)

**Comment by daryllabar** [comment]
Is the issue that it is creating noisy diffs?  And if so, would being able to specify a specific language for all users be just as good of a solution for you as removing it?  Or do you just hate the extra duplicated comments?

**Comment by MatteoVeronesi22** [comment]
yes, this generates noisy diffs and all file seem modified (git versioning relevate changes but it's only for the comment section)
Specific a language is a good workaround

**Comment by daryllabar** [comment]
hmm.. currently this is tied to the Suppress Generated Version Attribute for some reason which controls this:
<img width="527" alt="image" src="https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9728423/b2783301-8140-470b-b714-4d28ce782aac">

I'll see what can be done to suppress the comment header for you

**Comment by daryllabar** [comment]
Fix is in the latest version.
