### ISSUE TITLE
EBGv2: Add warning if V2 config is loaded into V1 & vice-versa

### ISSUE THREAD

**Issue by filcole** [daryllabar/DLaB.Xrm.XrmToolBoxTools#437]
**Tool**
EarlyBoundGenerator

**Is your feature request related to a problem? Please describe.**
To avoid confusion, especially when different versions of the EBG are being used on different projects it could be useful to add a warning/alert that the config file being loaded into the EBGv1 is from EBGv2, and similarly when a config file generated from EBGv2 is loaded into EBGv1.  As the new options/features are added the config files may diverge and config settings are lost unexpectedly.

**Describe the solution you'd like**
A warning when loading a V2 file into V1, and an upgrade alert when loading V1 into V2.

**Describe alternatives you've considered**
Train users (pesky humans!)

**Comment by daryllabar** [comment]
I think I'm in favor of not allowing V1 to read from V2.  I think it should already warn if the EBG version that previously was used is newer than the current one.  

So I think I need to update V1.  Also need to pester them to upgrade as well.
