### ISSUE TITLE
"Use Enum for State Codes" generates enum with lowercase first letter

### ISSUE THREAD

**Issue by altmank** [daryllabar/DLaB.Xrm.XrmToolBoxTools#439]
**Tool and Version**
EarlyBoundGenerator V2.2023.5.13

**Describe the bug**
With Camel Case settings disabled (no class/member case changes) & "Use Enum for State Codes" set to true. Entity state code enums are generated with lower case. I cannot use the camel case feature as it breaks other existing member names casing or cases them incorrectly due to the default dictionary and I do not wish to maintain a custom dictionary. 

**Expected behavior**
Enum names should start with a capitalized letter

**Screenshots**
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/22986384/ccc6c4b6-2d29-4f9d-9f8f-c2eae82fa60a)

**Comment by daryllabar** [comment]
I'm assuming the EBG V1 created it with a capital starting letter?

**Comment by daryllabar** [comment]
Mine are generated with the capital letter.  Can you send me the metadata and settings file so I can debug on my side?  You can update the white list to just contain the Account entity if that still generates it incorrectly. https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/EBG-%E2%80%90-Submitting-Metadata-For-Debugging
