### ISSUE TITLE
Error connecting to CRM (0365?)

### ISSUE THREAD

**Issue by jason-russell** [daryllabar/DLaB.Xrm.XrmToolBoxTools#44]
Hi Daryl,

I'm trying to use the Early Bound Generator plugin for the XrmToolBox and I'm getting a connection error.

I can select the **Entites to Skip** button and it loads all the correct entities and schema names, but whenever I click the **Create Entities** button I get an error similar to below (I've modified the Url, Username and Password to remove actual credentials

My CRM system is CRM Online (federated via Office365)

> CRM Authentication Type Detected: OnlineFederation
> Executing "C:\All Tools\CRM Tools\XrmToolBox2\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://dev-org.api.crm6.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"CrmEarlyBound" /out:"C:\All Tools\CRM Tools\XrmToolBox2\Plugins\CrmSvcUtil Ref\Entities.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"me@dev-org.com" /password:"myPassword" 
> CrmSvcUtil : CRM Service Utility [Version 8.0.1.7297]
> ¸ 2015 Microsoft Corporation. All rights reserved
> 
> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
> Unable to Login to Dynamics CRM
> CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Connection to CRM is not established. Aborting process.
>    at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
>    at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
>    at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
>    at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()
>    at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
>    at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
> CrmSvcUtil Error: 2 : ===== DETAIL ======
> CrmSvcUtil Error: 2 : Source	: mscorlib
> Method	: InvokeMethod
> Date	: 1:35:52 PM
> Time	: 23/05/2016
> Error	: Exception has been thrown by the target of an invocation.
> Stack Trace	: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
>    at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
>    at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()
>    at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
>    at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
> ======================================================================================================================
> Inner Exception Level 1	: 
> Source	: CrmSvcUtil
> Method	: Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata
> Date	: 1:35:52 PM
> Time	: 23/05/2016
> Error	: Connection to CRM is not established. Aborting process.
> Stack Trace	: at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
>    at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
> ======================================================================================================================
> 
> Output file was not updated or not found!  C:\All Tools\CRM Tools\XrmToolBox2\Plugins\CrmSvcUtil Ref\Entities.cs

**Comment by daryllabar** [comment]
Is the Dev-Org portion of your URL ("https://dev-org.api.crm6.dynamics.com/XRMServices/2011/Organization.svc" ) the OrgUniqueName :"org9123a34" or friendly name "MyDevEnvName"?  I have a bug that will be fixed in the next release that handles this, but for now, using the OrgUnique in the XTB will resolve the issue.  Unfortunetly, that usually involves editing the Connection XML Information.

**Comment by jason-russell** [comment]
It was the <kbd>Friendly</kbd> name.

Following your suggestions I modified my XrmToolbox credential file (`mscrmtools2011.config`) and updated all URLs with the <kbd>Unique</kbd> name and everything started working.

Looking forward to the next release, but at least this gets me moving in the meantime
