### ISSUE TITLE
IDEA: Charachter substitution list

### ISSUE THREAD

**Issue by Rasmus-Petersen-RLL-Sampension** [daryllabar/DLaB.Xrm.XrmToolBoxTools#441]
**Tool**
EarlyBoundGenerator

**Is your feature request related to a problem? Please describe.**
Being a Dane and therefore having a Dataverse system with Danish table and columns names, it's annoying seeing code translations like this:
Danish => Lørdag
Code => Lrdag

Danish => Åben
Code => _ben

**Describe the solution you'd like**
It would be nice to be able to define a list of character substitutions.
Following the above example, something like this:
ø;oe
Å;Aa

So every time the "ø" character occurs, then replace with "oe" and every time "Å" occurs replace with "Aa".

**Describe alternatives you've considered**
I don't see any alternatives.

**Additional context**
A dialog like the "Unmapped Properties" where there is a "From" and a "To" column, keep the delete button.
Also with a couple of reorder buttons, to move replace items up or down the list.
The application should then process replace items in the order they occur in the list.

**Comment by daryllabar** [comment]
I believe this is what the transliteratation files are for.  If you can build be a file for Danish, I'll add it to the tool 

https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/tree/master/DLaB.ModelBuilderExtensions/OptionSet/Transliteration/Alphabets

**Comment by daryllabar** [comment]
Fix is in the latest version.
