### ISSUE TITLE
Filter generated fields by publisher

### ISSUE THREAD

**Issue by MatteoVeronesi22** [daryllabar/DLaB.Xrm.XrmToolBoxTools#449]
**Tool**
EarlyBoundGenerator V2

**Is your feature request related to a problem? Please describe.**
I usually generated entities that are consumed by my code logics and I set up a white list of entities.
For each entity in the list all fields are added to the generated class

**Describe the solution you'd like**
I would like to generate only a subset of fields

**Describe alternatives you've considered**
My proposal is to add the availability to filter fields (components) by publisher (by list of prefix / whitelist of publisher).
Select a list of solution is an alternative but my preferd option is by publisher

**Additional context**
As a development environment that hosts different solutions that add custom fields to the same table.
I want to generate a class with standard fields + some extension microsoft + my custom fields

**Comment by daryllabar** [comment]
What is the benefit of not having all the fields?

I started done this path once upon a time, but the biggest issue I ran into was creating an efficient UI to allow the user to be able to select the fields desired.  Would you have any suggestions on what the UI should look like?

**Comment by MatteoVeronesi22** [comment]
In my case there are solutions from other vendors and I don’t want to create "dependencies" from other vendor solutions. 
I know I can include fields from other solution and simply don’t use it but I would also like to keep the code lighter and make it a bit more complicated for other team developers (junior) to use these fields.

In my intention we can also exclude Microsoft extension (e.g. Microsoft ADX Portal or Dynamics 365 Marketing)

I like the plugin and also the interface is good.

My suggestion is to add in the "1 General" configuration section a new entry called "Publisher Blacklist".
Here you can select publishers and exclude all attributes where the prefix matches

**Comment by daryllabar** [comment]
I'm considering #494 as the implementation for this.  Black list only, but it supports having entity specific, or global black lists.

**Comment by MatteoVeronesi22** [comment]
Fantastic!

Thanks and Regards,
Matteo
________________________________
Da: Daryl LaBar ***@***.***>
Inviato: giovedì 16 maggio 2024 19:18
A: daryllabar/DLaB.Xrm.XrmToolBoxTools ***@***.***>
Cc: MatteoVeronesi22 ***@***.***>; Author ***@***.***>
Oggetto: Re: [daryllabar/DLaB.Xrm.XrmToolBoxTools] Filter generated fields by publisher (Issue #449)


I'm considering #494<https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues/494> as the implementation for this. Black list only, but it supports having entity specific, or global black lists.
