### ISSUE TITLE
Either add ability to output ServiceConnection.cs and EntityOptionSetEnum.cs to different folder or change output folder location

### ISSUE THREAD

**Issue by RobMontague** [daryllabar/DLaB.Xrm.XrmToolBoxTools#451]
**Tool**
What tool/version is it that you're making a feature request for? EarlyBoundGenerator v2

**Is your feature request related to a problem? Please describe.**
Whenever I generate, I use a settings file located in /Model/Settings/EarlyBoundSettings.xml .  When the tool runs, I'm able to change the output location of the Entity and OptionSet generated files to ../ which allows all the files to be output to /Model/ .  Unfortunately this doens't work for ServiceConnection.cs and EntityOptionSetEnum.cs and I always have to manually move them.

**Describe the solution you'd like**
Either set the output folder in EarlyBoundGenerator/EarlyboundGeneratorV2 settings or allow us to specify the location of the ServiceConnection and EntityOptionSetEnum files.

**Describe alternatives you've considered**
Manually moving them or creating a script that would do it afterwords, but I'd like to keep it as a one button click to make it easy for other developers to use this tool

**Comment by daryllabar** [comment]
Fix is in the latest version.
