### ISSUE TITLE
IEnumerable Activity Party Typing Bug (again)

### ISSUE THREAD

**Issue by jensvoigtwysa** [daryllabar/DLaB.Xrm.XrmToolBoxTools#464]
**Tool and Version**
EarlyBoundGenerator V 2.2023.12.4

**Describe the bug**
When trying to access any activityparty attribute (i.e. "from" of "email") I get an error:
"Unable to cast object of type 'Microsoft.Xrm.Sdk.Entity' to type 'MyNamespace.Generated.ActivityParty'"

**To Reproduce**
1. Include "Email" and "ActivityParty" into the entities to be generated
2. Create a plugin on "Email"
3. Convert the InputParameter "Target" to Entity using "ToEntity<Email>()"
4. Access the "From" attribute on the that object -> Exception

**Expected behavior**
ActivityParty attributes are usable.

**Additional context**
There has been the same issue for the V1 version of EarlyBoundGenerator: #231
If I manually change the generated code like described there it works.

**Comment by daryllabar** [comment]
This is a bug in the ModelBuilder that I thought MS fixed, but didn't. 
[DLaB.ModelBuilderExtensions (2).zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/13635455/DLaB.ModelBuilderExtensions.2.zip)
Can you download, unblock, and unzip this zip file to the XrmToolBox\Plugins\DLaB.EarlyBoundGeneratorV2 folder, replacing the dll that is already there, and verify that it works?

**Comment by jensvoigtwysa** [comment]
Thanks, that fixes the issue.

However it references System.Text.Json 7.0.0.3 whereas XrmToolBox ships with System.Text.Json 7.0.0.1, so I had to redirect the binding to actually make it work.

**Comment by daryllabar** [comment]
Where did you edit the binding redirect?  In the XTB.exe binding file?

**Comment by jensvoigtwysa** [comment]
yes
