### ISSUE TITLE
EBG V2 Generation Error: Microsoft.Xrm.Sdk.PreferredSolutionDetails is not available

### ISSUE THREAD

**Issue by bwmodular** [daryllabar/DLaB.Xrm.XrmToolBoxTools#465]
**Tool and Version**
EBG V2 2.2023.12.4

XTB Version  1.2023.12.68

Power Platform 2023 Wave 2 9.2.23111.00228

**Describe the bug**
EBG V2 Generation fails with the following error:

Wrote 96 Entities - 00:00:01.7652637
Processing 1758 Messages
 0: Error       - Source	: Microsoft.PowerPlatform.Dataverse.ModelBuilderLib
Method	: BuildResponseField
Date	: 11:33:25
Time	: 11/12/2023
_**Error	: Type Microsoft.Xrm.Sdk.PreferredSolutionDetails is not available
Stack Trace	: at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildResponseField(SdkMessageResponse response, SdkMessageResponseField field, ServiceProvider serviceProvider)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildMessageResponse(SdkMessagePair messagePair, SdkMessageResponse sdkMessageResponse, ServiceProvider serviceProvider)**_
 0: Warning      - Skipping PreferredSolutionUsedBy.Message Pair from being generated. - Supporting Types Missing
 0: Information  - Wrote 737 Message(s). Skipped 1021 Message(s) - 00:00:00.7912404

**Additional context**
Generating same entities as succesfully generated using V1.
Settings file has been migrated from v1 to v2.

Do let me know if I can provide any additional information to help diagnose. I think you said this was going to be fixed with next version of XTB & EBG v2, but maybe you mean a _next_ next version of EBG2?

**Comment by daryllabar** [comment]
I assumed this was an ILMerge issue.  but the fix may be easy.  If you download, unblock, and extract this dll to the XrmToolBox\Plugins\DLaB.EarlyBoundGeneratorV2\ folder, does that fix the issue?
[Microsoft.Xrm.Sdk.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/13635180/Microsoft.Xrm.Sdk.zip)

**Comment by daryllabar** [comment]
Did you restart the XTB?

**Comment by daryllabar** [comment]
You're getting the same error, that the _Type Microsoft.Xrm.Sdk.PreferredSolutionDetails is not available_?  That is strange.  I've pushed an updated version today, maybe try placing everything in your Plugins folder (C:\Users\<UserName>\AppData\Roaming\MscrmTools\XrmToolBox\Plugins) into a zip back up, deleting it, and then just installing the EBGV2 and see if that resolves the issue?

**Comment by bwmodular** [comment]
Yes, it's the same error.

On a clean laptop I've installed latest version XTB from scratch. I've then only installed EBG V2 (2.2023.12.10) and no other plugins.

I've connected to two different Power Platform instances, for different clients and run the generator using the default settings. In both cases I get the PreferredSolutionDetails is not available error.

Both clients are in crm11, so I then connected to another in crm4, with the same error. :-(

**Comment by daryllabar** [comment]
The issue is with the PreferredSolutionUsedBy generation.  Do you need it?  Why don't you only include the messages you need, or black list it?

**Comment by daryllabar** [comment]
OK, so the issue is that the XTB specifies and loads an older version of the Microsoft.Xrm.SDK.  I'll need to make sure in the future to not specify a version of the ModelBuilder that references a newer Xrm.Sdk dll.  For now as a work around, you can replace the Microsoft.Xrm.Sdk.dll in the XTB folder with this dll, or not generate all messages:

[Microsoft.Xrm.Sdk.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/13651167/Microsoft.Xrm.Sdk.zip)

**Comment by bwmodular** [comment]
Thanks Daryl, I can confirm that both of your suggested solutions fix the problem - I'm going to go with the Message whitelist as I certainly don't need 739 early bound message classes :-)
I wonder whether it would be worth having a default Message whitelist in the same way that you have a default Entity whitelist so that noobs like me don't get that error the very first time they run Generate with the default values.
