### ISSUE TITLE
Using Current Credentials is missing UserName

### ISSUE THREAD

**Issue by daryllabar** [daryllabar/DLaB.Xrm.XrmToolBoxTools#47]
Message from @JurgenPostelmans in Issue: Difficulties with Early Bound Generator #43

@daryllabar I just tried the new version and it could successfully generate the entities, option sets and actions in C#.

One strange thing however was that in my connection settings in XrmToolbox I have "Use your current credentials" checked and your plugin asked me for the password when I pressed the "Create All" button.
In the output below you can see that Username is empty in the connection string but password is there. Cloud be that this is the expected behavior?

CRM Authentication Type Detected: ActiveDirectory
Executing "C:\Users\Administrator\Downloads\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /generateActions /out:"C:\Users\Administrator\Downloads\XrmToolBox\Plugins\CrmSvcUtil Ref\Actions.cs" /namespace:"CrmEarlyBound" /codecustomization:"DLaB.CrmSvcUtilExtensions.Action.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Action.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /connectionstring:"Url=http://springfield:5555/U2U;UserName=;Password=**_" 
Executing "C:\Users\Administrator\Downloads\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /namespace:"CrmEarlyBound" /out:"C:\Users\Administrator\Downloads\XrmToolBox\Plugins\CrmSvcUtil Ref\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CreateOptionSetEnums,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /connectionstring:"Url=http://springfield:5555/U2U;UserName=;Password=**_"

**Comment by daryllabar** [comment]
So @JurgenPosteImans, It worked correctly without a UserName for you?  Interesting...  I think that was one thing I forgot was to populate the UserName...  But if it's working fine, I guess I won't bother...  

Will it work without the Password value?

You can test by opening a command line and attempting to run
```
"C:\Users\Administrator\Downloads\XrmToolBox\Plugins\CrmSvcUtil` Ref\crmsvcutil.exe" /namespace:"CrmEarlyBound" /out:"C:\Users\Administrator\Downloads\XrmToolBox\Plugins\CrmSvcUtil Ref\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CreateOptionSetEnums,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /connectionstring:"Url=http://springfield:5555/U2U"
```

**Comment by MarcusNaylor** [comment]
Same issue here username is blank (using AD connection).  Is there a fix for this?
Using [Version 8.1.0.7711]

**Comment by daryllabar** [comment]
This will get updated in the next published version of the Tool
