### ISSUE TITLE
'Upgraded' v1settings files are missing some options in v2

### ISSUE THREAD

**Issue by bwmodular** [daryllabar/DLaB.Xrm.XrmToolBoxTools#470]
**Tool and Version**
What tool/version is it that you're reporting a bug for? i.e.
EarlyBoundGenerator V 1.2020.4.24

**Describe the bug**
If you open a v2 settings file in v2, not all of the v2 options are available.
Are there any reccomendations from 'ugrading' from v1 to v2.

**To Reproduce**
Open a settings file in v2 which was used in EBG v1 - some of the settings which are in a default v2 settings file are not there in the 'upgraded' file. And there is one setting in the upgraded file which is not there in the default v2 file.

Here are screenshots of a v1 file opened in v2, next to a default v1 file.
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/1889586/054e013d-f47a-43ae-aaf8-c3698339e083)

![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/1889586/dbed9447-db1c-43dc-9b29-dbe49a276f64)

I'm wondering if there's a reccomended upgrade path from v1 to v2 - I'm having all sorts of compilation issues with code that's been developed against v1 EBG files, so started comparing settings and this is when I noticed the differences. I can raise seperate issues describing the compilation errors, but wondered if there was a reccomended way to get from v1 to v2...?

**Comment by bwmodular** [comment]
Great, thanks Daryl - I'll concentrate on the specific compilation errors I'm getting then. Thanks for the clear explanation!

**Comment by daryllabar** [comment]
There are soo many options to choose from, so I didn't have a chance to test everything, so yes, if the newly generated code post upgrade from V1 to V2 causes breaking changes, I want to be able to identify and fix those
