### ISSUE TITLE
"_" underscore is removed from OptionSet Names?

### ISSUE THREAD

**Issue by SumanthKKusuma** [daryllabar/DLaB.Xrm.XrmToolBoxTools#479]
**Tool and Version**
What tool/version is it that you're reporting a bug for? i.e.
EarlyBoundGenerator V 2.2023.12.22

**Describe the bug**
With this EarlyBoundGenerator V2 - Version 2.2023.12.22, when we generate early bound the optionset name which had "_" underscore is removed, for example OldValue-> "nothing_ieCeo" is updated to NewValue->"nothingieCeo".

**To Reproduce**
After Generation with new version when we build the solution we see errors in build for the optionset which had "_" is removed now which are used in plugin code.

**Screenshots**
![Screenshot 2023-12-27 173303](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/154983670/938630c2-ecfa-4f07-8811-b6dfd7989d74)

**Additional context**
Do we need to manually updated/remove all the reference where optionset enum with value "_" is used in plugin?

**Comment by daryllabar** [comment]
Here is the issue with this.  In the latest version of the Dataverse Builder, MS added this code:
<img width="426" alt="image" src="https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9728423/d006fac7-d957-4928-889a-31d9a831a861">
Which is really kind of a weird thing to do IMHO, and broke some of my older code.  So I created #475 which reverted to how it worked before.  So my suggestion is, yes, update the references to it if it isn't too big of an issue.  It's usually really simple to do, just manually insert the underscore back into your enum definition, and then use a the rename command in Visual studio to rename it, and it will update all of your references.

Your other option is to manually add a labelTextReplacement property to the JSON file that is used to generate the early bound files, that defines you would like the "(" to be replaced with a "_", but then you'd have to manually keep adding this value to the json every time you want to re-generate.

**Comment by SumanthKKusuma** [comment]
Thank you @daryllabar 👍
