### ISSUE TITLE
Generated Account.cs Entity cannot find AccountState (StateCodeEnum)

### ISSUE THREAD

**Issue by sgwatgit** [daryllabar/DLaB.Xrm.XrmToolBoxTools#48]
The following lines are giving me errors in my `Account.cs`

``` csharp
[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
public virtual AccountState? StateCodeEnum
{
    [System.Diagnostics.DebuggerNonUserCode()]
    get
    {
        return ((AccountState?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
    }
    [System.Diagnostics.DebuggerNonUserCode()]
    set
    {
        StateCode = (int?)value;
    }
}
```

The error is 

```
The type or namespace name 'AccountState' could not be found (are you missing a using directive or an assembly reference?)
```

I generated all the OptionSets and there is no `AccountState.cs` file in the OptionsSets directory.

This same error appears for all state properties of any Entity I create using the plugin.

Do I need to manually create all these StateCode enums? I don't think I really need them for my application so I could remove them, but I would need to remove them each time I regenerate the files.

**Comment by daryllabar** [comment]
You shouldn't have to manually create them.  What version of the Early Bound Generator are you using, and what CRM version are you connecting to?

**Comment by daryllabar** [comment]
Any chance you changed the configuration to be a file per class, and haven't added the optionset classes to your project, or they're a different namespace?

**Comment by sgwatgit** [comment]
Here is a screenshot of my config

![xrm-entity-generation-config](https://cloud.githubusercontent.com/assets/1382768/16705382/4cd1d84e-4556-11e6-8e8e-70b599f0333f.jpg)

Here are my versions
XrmToolBox: 1.2016.6.29
DlaB Tools: 1.2016.6.1

I'm connecting to crm.dynamics.com (Update 2016) v8.0.1.116.

So I am using 1 file per class and I have the generated option sets and I added them to my project. I'm using the same namespace for both entities and enums. I don't have errors with any of the other option sets/enums. What would the files be named for those missing enums?

Here is my option set configuration

![xrm-option-set-generation-config](https://cloud.githubusercontent.com/assets/1382768/16705403/ef599a02-4556-11e6-9260-438215589d01.jpg)

**Comment by daryllabar** [comment]
You should have close to 500 files in your `Plugins\CrmSvcUtil Ref\OptionSets` folder.  Is anything listed there?

**Comment by sgwatgit** [comment]
Yup, I have 526. I have added the ones I needed to my project.

The interesting thing is I wasn't getting errors until I checked the box to use the Xrm Client so that I could get access to the `CrmOrganizationServiceContext` and regenerated the entities and crm context. After that the errors for the above mentioned fields showed up (and only for those fields).

**Comment by daryllabar** [comment]
Hmm... wonder if the XRM Client changes the output to put those option sets in the optionset files, rather than including them in the class itself?

**Comment by sgwatgit** [comment]
Nope,

I just included every single generated OptionSet file and I still get the errors with the enums for entity state for every single entity.

This isn't an issue with the option sets being in the wrong place, as far as I can tell. It's an issue with them not being generated at all once you select to use the `Xrm Client`.

**Comment by larsvliet** [comment]
I am currently experiencing the same issue as @sgwatgit when the "Use Xrm Client" option is selected. The enum is generated inline (in Account.cs) when the "Use Xrm Client" option is **deselected**

**Comment by vladimirkarukes** [comment]
Great work on the tool, Daryl. I just started to use it yesterday and ran into the same issue as described above, the account state (and other entities' states) are not generated when "Use Xrm Client" option is selected.

**Comment by JonathanWacks** [comment]
Hi,  great tool but I'm also experiencing this issue.  Worked fine when I wasn't using Xrm.Client.  However, I'd like to take advantage of the implicitly loaded relationships, so I need Xrm.Client, but then I'm getting errors for all the entity state enums.

**Comment by JonathanWacks** [comment]
I have just tried removing the line #define SKIP_STATE_OPTIONSETS from DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService, then rebuilding.  This does the job but obviously is a bit of hack - better would be to have a check for whether XrmClient is being used or not.

**Comment by daryllabar** [comment]
@JonathanWacks Sorry it took so long, but this fix has been implemented.
