### ISSUE TITLE
Connection_Record1ObjectTypeCode is missing in optionsets.cs since version V2.2023.12.22

### ISSUE THREAD

**Issue by Dayonel** [daryllabar/DLaB.Xrm.XrmToolBoxTools#483]
**Tool and Version**
EarlyBoundGenerator V2.2024.1.23

**Describe the bug**
When generating entities that have Connection & ConnectionRole involved, this part of code is missing: Connection_Record1ObjectTypeCode in optionsets.cs so it does not compile.

**To Reproduce**
1. Use version V2.2023.12.22 or superior
2. Click on 'Generate'
3. This part of code is missing

![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/10290812/61ce769c-356b-4bc7-a5af-b3fd92e26873)

Downgrade to version V2.2023.12.21 or lower.

**Expected behavior**
The optionset is generated

**Screenshots**
This change has broken it
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/10290812/eba44296-57a8-477e-9da3-a30fccdfdf11)

**Comment by daryllabar** [comment]
Is it not compiling because you are referencing it in you code, or is it not compiling because the EBG is still creating the typed record1objecttypecode property?

The intention was to remove it because it was causing lots of noisy diffs, and it is bad practice to use it, since you can't easily control the value in the environment, allowing production to be different than a dev environment, which would cause errors at run time.

**Comment by Dayonel** [comment]
Is not compiling because the entity **Connection** is referencing it automatically.

```
public partial class Connection {
   ...
   public virtual Connection_Record1ObjectTypeCode? Record1ObjectTypeCode {...}
}
```

**Comment by daryllabar** [comment]
Can you submit your metadata for me to use to debug?
https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/EBG-%E2%80%90-Submitting-Metadata-For-Debugging

**Comment by schwoi** [comment]
@daryllabar is there a secure way to share the metadata with you?
We are still recieving this issue

**Comment by daryllabar** [comment]
There shouldn't be anything secretive in the settings, but you can feel free to send a link to me vial my email Daryl at Gap Integrity dot com

**Comment by daryllabar** [comment]
I don't believe I ever got your code base.  Please send it and I'll re-open this.

**Comment by mattritchie** [comment]
@daryllabar I am encountering this issue! happy to send you some logs!
[XRM EBG Bug.zip](https://github.com/user-attachments/files/17288970/XRM.EBG.Bug.zip)
