### ISSUE TITLE
Getting error in Visual Studio Solution Accelerator while adding libraries to solution

### ISSUE THREAD

**Issue by UrvishMandaliya** [daryllabar/DLaB.Xrm.XrmToolBoxTools#486]
**Tool**
Visual Studio Solution Accelerator

It is giving an error for missing assembly of NuGet.Core while clicking on Execute button to install accelerator isolation libraries.

**To Reproduce**
1. Go to XrmToolBox.
2. Click on tool Visual Studio Solution Accelerator.
3. Select Add Accelerator Isolation Libraries to my Solution and click on Execute.
4. See error below

**Screenshots**
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/49593616/0ddf8a39-4cd3-40d5-9de6-f48f4920dbf7)

**Error Log**

System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Core, Version=2.14.0.832, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'NuGet.Core, Version=2.14.0.832, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at DLaB.VSSolutionAccelerator.PackageLister.GetPackagesbyId(String packageId)
   at DLaB.VSSolutionAccelerator.Wizard.NuGetVersionSelectorPage.Create(String question, String packageId, String description, Boolean onlyDisplayLatestMajorVersion)
   at DLaB.VSSolutionAccelerator.InitializeSolutionInfo.AddXrmNuGetVersionQuestion(List`1 pages)
   at DLaB.VSSolutionAccelerator.InitializeSolutionInfo.InitializePages()
   at DLaB.VSSolutionAccelerator.VsSolutionAcceleratorPlugin.ShowAddAcceleratorsWizard()
   at DLaB.VSSolutionAccelerator.VsSolutionAcceleratorPlugin.ExecuteBttn_Click(Object sender, EventArgs e)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by daryllabar** [comment]
Ah, this has been removed from the XTB.  I will need to rebuild, just downloading the nuget files themselves via web requests.

**Comment by UrvishMandaliya** [comment]
@daryllabar For a potential workaround I have included NuGet.Core assembly in the XTB folder and that got the reference for the process in Vistual Studio Solution Accelerator.

**Comment by UrvishMandaliya** [comment]
@daryllabar  When we use Visual studio accelerator tool to generate code, it uses DLaB.XRM.Source.3.1.0.0 in the app_package it generates. But from Visual studio NuGet package if we install than it uses DLaB.XRM.Source.4.1.0.4.
Problem with these two version is that some of the Abstract methods are missing in new version on DLaBGenericPluginBase.

**Comment by daryllabar** [comment]
Can you create a separate issue for this. I need to track them separately.

**Comment by UrvishMandaliya** [comment]
sure let me create another issue for it.
