### ISSUE TITLE
DLaB.XRM.Source missing some abstract methods in 3.1.X and 4.1.X

### ISSUE THREAD

**Issue by UrvishMandaliya** [daryllabar/DLaB.Xrm.XrmToolBoxTools#489]
**Describe the bug**
 When we use Visual studio accelerator tool to generate code, it uses DLaB.XRM.Source.3.1.0.0 in the app_package it generates. But from Visual studio NuGet package if we install than it uses DLaB.XRM.Source.4.1.0.4.
Problem with these two version is that some of the Abstract methods are missing in new version on DLaBGenericPluginBase.

**Screenshots**
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/49593616/4fb89e54-ba48-448d-9845-43d62b15b476)

**Comment by daryllabar** [comment]
Yes, the newest version of the Plugin logic utilizes an IOC container for Dependency injection, and the the abstract method is no longer needed.  You can either reference the older nuget package, or just remove the override method.
