### ISSUE TITLE
Unable to compile source code or use precompiled release

### ISSUE THREAD

**Issue by benArrayx** [daryllabar/DLaB.Xrm.XrmToolBoxTools#49]
Hi Darryl, I'm really struggling to get this working!!

Firstly, I cloned the git repo and opened in Visual Studio 2015 (14.0.25123.00 Update 2), and did a build. I get many warning about unresolved references, here are the first 4, there are many more. Note that NuGet did download many packages, here's a screenshot of my packages folder: http://screencast.com/t/OENePRpF

Warning		Could not resolve this reference. Could not locate the assembly "Microsoft.WindowsAzure.Configuration". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	DLaB.CrmSvcUtilExtensions			
Warning		Could not resolve this reference. Could not locate the assembly "Microsoft.TeamFoundation.Test.WebApi". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	DLaB.CrmSvcUtilExtensions			
Warning		The referenced component 'Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms' could not be found.	DLaB.CrmSvcUtilExtensions			
Warning		Could not resolve this reference. Could not locate the assembly "Microsoft.TeamFoundation.Build2.WebApi". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	DLaB.CrmSvcUtilExtensions			

Secondly, I went to your releases section and downloaded https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/releases/download/2016.6.1.1/DLaB.Xrm.XrmToolBoxTools.1.2016.6.1.nupkg - I wasn't sure how to deal with a nupkg file on it's own but 7zip seemed to extract it without problems. In the lib\net452\plugins folder there seem to be your compiled plugins, but this folder contains another sub-folder "CrmSvcUtil%20Ref" - the %20 looks odd in a folder name. So I left this alone.

Thirdly, I downloaded https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/releases/download/2016.3.30.1/DLaB.XrmToolBoxTools.Full.zip and extracted it. I ran the XrmToolBox.exe file I found there. I tried to create a new connection entering the organization url I see when connecting in the browser as it says on the dialog box (ie. https://{orgname}.crm4.dynamics.com), I entered a username and password and got this error: http://screencast.com/t/sfdwLrRglsf

So I went back and entered the org unique name instead of the org friendly name in the URL but got exactly the same error.

I clicked on the link to try and connect using a connection string, using the connection string https://{orgname}.crm4.dynamics.com;{org unique Id}, but got this error: http://screencast.com/t/w6H7zqhX

Fourthly I tried to copy your dll's into the plugin folder of the version of XrmToolbox which I have which does work (v1.2015.11.5) but get the error "System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'" when opening XrmToolBox.exe. Clearly there will be version conflicts here, I'm guessing this will never work.

Ideally I'd like to sort out the source code references and work with that. I don't see anybody else here having similar issues which seems strange, I don't understand why I would be having these issues when nobody else does! Any ideas?

Regards, Ben

**Comment by benArrayx** [comment]
UPDATE: I downloaded the latest version of XrmToolbox and downloaded DLaB Tools from the Plugin Store, everything worked OK from there!

**Comment by daryllabar** [comment]
Glad it's working now!

**Comment by benArrayx** [comment]
Hi Daryll, I would like to be able to compile the code in order that I can get into it and possibly adapt for my own uses. Can you offer any help on getting the solution to compile?

**Comment by benArrayx** [comment]
Actually don't worry, I've had a good look through the code now and I don't think it will help me directly in what I need to do. But, thanks anyway for doing awesome work and providing it to the community!

**Comment by daryllabar** [comment]
Hey Ben, I use the same exact extensibility model that the SDK gives you OOB.   If you ever wanted to create your own Interfaces to extend it, you could, and then just call my interfaces.  

As far as your code compliation issue, I believe it is all nuget related.  I have more projects listed in my Projects folder than you do.  For example, I noticed that I have "Microsoft.WindowsAzure.ConfigurationManager.3.2.1", and you do not, which is probably why you're getting the error that you're getting.

What are you wanting it to do that it isn't doing?  Maybe it should be a feature request?

Also, if you ever what to change someone's code on GitHub, Fork it, don't Clone it.  You won't be able to check it in if you clone it.
