### ISSUE TITLE
Support for German Labels

### ISSUE THREAD

**Issue by klemenskanal** [daryllabar/DLaB.Xrm.XrmToolBoxTools#50]
I have added a file called 1031.json in the alphabet subfolder containing the following text:
{
     "code": 1031,
     "language": "German",
     "alphabet": [
          [ "Ä", "Ae" ],
          [ "Ö", "Oe" ],
          [ "Ü", "Ue" ],
          [ "ä", "ae" ],
          [ "ö", "oe" ],
          [ "ü", "ue" ],
          [ "ß", "ss" ]
     ]
}

This led to CRM systems with only German labels being supported.
It would be great to include this file in further versions.

Regards
Klemens

**Comment by daryllabar** [comment]
This will be added to the next release.
