### ISSUE TITLE
"Make reference types nullable" should generate a nullable opt-in directive

### ISSUE THREAD

**Issue by randombyte-developer** [daryllabar/DLaB.Xrm.XrmToolBoxTools#500]
**Tool and Version**
EarlyBoundGenerator V 2.2024.5.16

**Describe the bug**
I wanted to try out https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues/311. It generates nullable types. When compiling the generated code there is a compile error:

```
The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.
```

See the "Important" section in the docs regarding auto-generated code: https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts

A `#nullable enable` at the top of the file fixes the error.

**To Reproduce**
1. Generate the code for an Account with nullable types enabled.
2. Compile it.

**Expected behavior**
No errors.

**Additional context**
My C# project file looks like this:

```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>........snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
	<PropertyGroup>
		<LangVersion>11.0</LangVersion>
		<TargetFramework>net462</TargetFramework>
		<Nullable>enable</Nullable>
		<Version>1.0.0.0</Version>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.52" />
	</ItemGroup>
</Project>
```

**Comment by daryllabar** [comment]
I'm guessing the nullable annotation pragmas should be something that the user can configure and opt into correct?  Because if they set it at the project level, they don't want them to be created at the file level.

**Comment by randombyte-developer** [comment]
@daryllabar No, they have to be generated at the file level as the docs say (for auto-generated code): 
![grafik](https://github.com/user-attachments/assets/89ee1d0e-46d3-4e9a-9dce-3b9a6c537a34)
