### ISSUE TITLE
Struggling with inital setup of EBGV2

### ISSUE THREAD

**Issue by blundern** [daryllabar/DLaB.Xrm.XrmToolBoxTools#505]
I'm struggling with the initial setup of EBGV2. I have read below two wiki pages that covers kind of what I'm trying to achive. 

My goal is to implement EBGV2 so I am able to run the PAC CLI modelbuilder from a PowerShell script (which works great already without any extending..) 

In my PS-script I'm installing PAC CLI as documented from Microsoft here: 
https://learn.microsoft.com/en-us/power-platform/developer/howto/install-cli-net-tool?tabs=windows

With the ps command:  dotnet tool install --global Microsoft.PowerApps.CLI.Tool

When installning like this PAC CLI not seams not to be installed in the same folder structure as described in the wikis below.  

It seams to me PAC CLI is installed here for me: 
C:\Users\MyUserName\.dotnet\tools\.store\microsoft.powerapps.cli.tool\1.32.8\microsoft.powerapps.cli.tool\1.32.8\tools

the pac.exe is located in the first tools directory. 

**What am I missing? Were to put all the extensions.dlls?**

[Wiki - Integration the early bound genereator into your pipeline](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/EBG-%E2%80%90-Integrating-The-Early-Bound-Generator-Into-Your-Build-Pipeline)

_"Running Via the Command Line PAC
1 - Copy the contents of the DLaB.EarlyBoundGeneratorV2 in the XrmToolBox Plugins directory (Default: C:\Users{UserName}\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGeneratorV2)
2 - Paste the entire directory into the latest version of PAC Tools directory (C:\Users{UserName}\AppData\Local\Microsoft\PowerAppsCli\Microsoft.PowerApps.CLI.X.X.X\tools). This will end up with a \tools\DLaB.EarlyBoundGeneratorV2 directory in the PAC directory.
3 - Move the DLaB.ModelBuilderExtensions.dll up a directory from the \tools\DLaB.EarlyBoundGeneratorV2 directory to the tools directory
4 - Create an AUTH in the PAC if it doesn't already exist (Example using App/Secret: PAC auth create --name {NAME} --tenant {TENENT_ID} --applicationId {APP_ID} --clientSecret {APP_SECRET} --url https://{ORG_URL_NAME}.crm.dynamics.com/)
5 - Run the command line of the tool the Early Bound Generator spits out (PAC modelbuilder build --outdirectory {OUTPUT_DIRECTORY} --settingsTemplateFile {PATH_TO_builderSettings.json})"_

[Wiki - Upgrade to PAC modelbuilder](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/EBG-%E2%80%90-Version-2.2023.4.3-Upgrade-To-PAC-ModelBuilder)

_"EBGv2 follows the same pattern, only using the [PAC CLI](https://learn.microsoft.com/en-us/power-platform/developer/cli/introduction). This involves a much simpler command line (PAC modelbuilder build --outdirectory {DirectoryPath} --settingsTemplateFile {builderSettings.json path}) and all the EBGv2 settings are written to the same builderSettings.json file. Users will need to first Auth to their org before running the command. Users will also need to include the DLaB.ModelBuilderExtensions.dll, DLaB.Dictionary.txt and alphabets folder in their latest PAC directory (C:\Users%UserName%\AppData\Local\Microsoft\PowerAppsCli\Microsoft.PowerApps.CLI.X.X.X\tools)"_

**Comment by daryllabar** [comment]
Apparently they have moved the install location for the PAC CLI.  At the end of the day, the DLaB.ModelBuilderExtensions.dll, DLaB.Dictionary.txt file and alphabets folder need to exist in your latest PAC directory.  Does that help?

**Comment by blundern** [comment]
It should help I guess :D but can't not get it to work. This is what I'm doing.

I'm adding the files here: 

![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/34213536/b589f2a6-2ec2-4cac-a224-27d019a0cc11)

runs this from PowerShell:
pac modelbuilder build -o . -stf .\builderSettings.json

with this builderSettings.json file: 
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/34213536/284c3600-3327-4c66-951e-363f4d8e5fba)


And recieve this error:
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/34213536/0d569b70-7a9e-41a7-8097-dcf7935ed0f9)

**Comment by daryllabar** [comment]
I don't understand how you're arriving at your path.  At the end of the day, you will need to move the following files into the same folder as your pac.exe:
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9728423/302b8169-de81-40f9-b1a0-2d3cab033a7e)

For me, I found it on my machine by opening a command prompt, and typing 
```
where pac
```
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9728423/e6a60a61-426a-40d2-b60f-c83c9940e2ec)

which took me to the pac.cmd:
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9728423/6b5a2a7d-f57c-41d7-b7d4-aa6a1d7c6612)

where I then navigated to the most recent Pac CLI folder, and then tools to find the actual pac.exe
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9728423/8ac52036-0ab4-4a6e-af21-2474d42f5783)

So it would be in the folder of the pac.exe that you'd need to copy the DLaB.ModelBuilderExtensions.dll, DLaB.Dictionary.txt file and alphabets folder need to exist in your latest PAC directory.  If you're trying to script this, you could even get these files from the API nuget package (https://www.nuget.org/packages/DLaB.Xrm.EarlyBoundGeneratorV2.Api)

**Comment by daryllabar** [comment]
Ok, re-read your initial post.  I'd just search for the Pac.exe in the microsoft.powerapps.cli.tool folder.  That would be where you'd need to get my DLaB.ModelBuilderExtensions.dll, DLaB.Dictionary.txt file and alphabets folder copied to.

**Comment by blundern** [comment]
Hi sorry for late reply. Been out in the woods for a couple of days with no internet connection what so ever :) 

Thanks a lot Daryl for the clarification above. The problem for me seems to be how I'm installing PAC CLI. 

If I'm using this approach: https://learn.microsoft.com/en-us/power-platform/developer/howto/install-cli-net-tool?tabs=windows then its installed on my system but in a different way and witout any folder with dlls to be found. 

If I'm using this approach: https://learn.microsoft.com/en-us/power-platform/developer/howto/install-cli-msi
then its installed on my system exactly as you describes above. And then it works like a charm. So I think I will install PAC CLI using this approach 👍 Thanks a LOT for you taking the time to answer my questions. I'm very grateful!

**Comment by blundern** [comment]
Hi sorry for late reply. Been out in the woods for a couple of days with no internet connection what so ever :)

Thanks a lot Daryl for the clarification above. The problem for me seems to be how I'm installing PAC CLI.

If I'm using this approach: https://learn.microsoft.com/en-us/power-platform/developer/howto/install-cli-net-tool?tabs=windows then its installed on my system but in a different way and witout any folder with dlls to be found.

If I'm using this approach: https://learn.microsoft.com/en-us/power-platform/developer/howto/install-cli-msi
then its installed on my system exactly as you describes above. And then it works like a charm. So I think I will install PAC CLI using this approach 👍 Thanks a LOT for you taking the time to answer my questions. I'm very grateful!
