### ISSUE TITLE
Special characters not generating in V2 (ë)

### ISSUE THREAD

**Issue by IanSchillewaert** [daryllabar/DLaB.Xrm.XrmToolBoxTools#506]
**Tool and Version**
What tool/version is it that you're reporting a bug for? i.e.
EarlyBoundGenerator V 2.2024.5.16

**Describe the bug**
We have certain optionsets that contain the character ë at the end of aoptionset value, for example België (dutch for Belgium)
In the V1 this used to generate as "Belgie", but with the V2 it skips the special char and generates as "Belgi".

**Expected behavior**
We would like to be able to get special characters to generate as the usable version of the character. for example "ë, é, è" becomes "e"

**Additional context**
Could be that this is a setting somewhere that we've missed in the V2, but we played around a bit and where not able to get the desired result

**Comment by daryllabar** [comment]
Thanks for reaching out.  Yes, this is a problem by many non-US centric language sets.  The good thing, is that it has a solution, but I would need your help.  There is an "alphabets" folder in the EBG plugins folder, that contains JSON files by language code, that allow for the transliteration of these characters into more easily usable versions.  My ask is that you generate a JSON file for your language, (I'm assuming Dutch 1043,  looks like there is also a 2067 https://help.tradestation.com/10_00/eng/tsdevhelp/elobject/class_el/lcid_values.htm ?), and place it in your "alphabets" folder, and rerun the generation.  It should pick up the language code from your environment, but if not, there is a place to override it as well:
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9728423/265f678b-7193-433a-8923-32c40b47c5a1)

If you could then attach the file to this issue, I'll include it in the next release of the EBG!

**Comment by IanSchillewaert** [comment]
Hi Daryl, 

Thanks for the quick response, I made 2 files for both of the codes and they seem to do the trick.
I've included them here so they can be added to the tool.

[1043.json](https://github.com/user-attachments/files/16070011/1043.json)
[2067.json](https://github.com/user-attachments/files/16070012/2067.json)
