### ISSUE TITLE
Trying to convert local option set to global option set

### ISSUE THREAD

**Issue by PMMCRM** [daryllabar/DLaB.Xrm.XrmToolBoxTools#51]
and get the error ...

System.Exception: A validation error occurred.  The value of 'new_crmsystem_t_' on record of type 'account' is outside the valid range.

The original field has some data and an option set.
I have created a new Global option set to migrate to

Tried twice with different names for the global option set - same error.

**Comment by daryllabar** [comment]
Are you selecting to migrate the data?  If the optionset values do not match exactly (or do not match exactly with the prefix added to it), you'll get that error.

**Comment by PMMCRM** [comment]
Have I misunderstood what this can do?

I want to move all the options from the local option set to a new global option set - the new global option set is empty.

**Comment by daryllabar** [comment]
Slightly.  The tool doesn't create the option set values for the global option set.  You'll need to create those once, then run the tool, and it will create a temporary field on the entity  'new_crmsystem_t_' that is of the global type, and migrate all of the data over, and then delete the old field, then recreate the old field, with the same name, but as a global, and migrate everything back from the temporary field, and then delete the temporary field.  

Makes sense?

The global option set may already exist, so the tool doesn't create the actual global option set itself...

**Comment by PMMCRM** [comment]
Ah OK - its a very long list, I was expecting it to copy all the items over for me.   Thanks anyway.

**Comment by daryllabar** [comment]
Sounds like a feature request ;)  You might be able to do a solution export of the two OptionSets, and copy over the xml values into the empty global and import.

**Comment by PMMCRM** [comment]
Ok thanks for your help.

**Comment by PMMCRM** [comment]
Right - I did all this and thought it worked, but now the system crashes when I try to open an account record (it was an account entity field that was being changed) !!!  Unable to open any accounts.

**Comment by daryllabar** [comment]
Do you get a Javascript error of some sort?
Have you tried creating a new form, just to see if it is the form that has an issue?

**Comment by PMMCRM** [comment]
All forms are affected except the Quick Create which didn't have that field on it.
I have tried removing the field from the main form but that makes no difference.

**Comment by daryllabar** [comment]
Are you getting an error?

**Comment by PMMCRM** [comment]
Error
An error has occurred. 

Try this action again. If the problem continues, check the Microsoft Dynamics CRM Community for solutions or contact your organization's Microsoft Dynamics CRM Administrator. Finally, you can contact Microsoft Support.

**Comment by daryllabar** [comment]
Is there no Download or see more details?

**Comment by PMMCRM** [comment]
Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: System.Web.HttpUnhandledException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #390BB256Detail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ErrorCode>-2147220970</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
  <Message>System.Web.HttpUnhandledException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #390BB256</Message>
  <Timestamp>2016-07-14T14:38:48.0605446Z</Timestamp>
  <InnerFault>
    <ErrorCode>-2147220970</ErrorCode>
    <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
    <Message>System.NullReferenceException: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #83802DA7</Message>
    <Timestamp>2016-07-14T14:38:48.0605446Z</Timestamp>
    <InnerFault i:nil="true" />
    <TraceText i:nil="true" />
  </InnerFault>
  <TraceText i:nil="true" />
</OrganizationServiceFault>

**Comment by PMMCRM** [comment]
Any ideas - our entire system is unusable now :(

**Comment by daryllabar** [comment]
Answer some questions...

Looks like there is a potential plugin error.  Is there anything in the plugin trace logs?  What plugins/ workflows do you have that touch the account entity?

If you create a new empty form, does it work?

Did the tool actually complete entirely?  Did it say it was successful?

Have you verified that the Account entity fields look correct when you look at it via customizations?

**Comment by PMMCRM** [comment]
Hi

I don't know about any plugins or trace logs - doesn't mean anything to me.  We use ClickDimensions?

I'm sure the tool completed successfully

The data looks fine from a View, the Form looks fine via Customisations.  I have even removed the field from the form and it makes no difference.

I have tried creating a new form, but it simply opens a copy of the same one ?

**Comment by daryllabar** [comment]
I'm not sure why you're having the issue then.  If the field isn't on the form, it shouldn't be causing the issue.  (Assuming this is CRM Online, I'd contact MS support via your office 365 admin, and see what the issue is.

**Comment by daryllabar** [comment]
Did you get anywhere with this?

**Comment by PMMCRM** [comment]
No - still down :(  
We have completely deleted the field and the option set - Microsoft have no idea - waiting for them to come back to us again.

**Comment by daryllabar** [comment]
I've used this tool successfully multiple times in multiple environments.  I'm sorry that you're having issues...  Please let me know what the end result especially if there is something that I need to change, but if you've deleted the field, I can't imagine it being an issue that the tool caused...

**Comment by PMMCRM** [comment]
We have no ideas what else to do, nor do Microsoft.  We are now resorting to a full restore from last Wednesday.

**Comment by daryllabar** [comment]
How did this turn out?

**Comment by PMMCRM** [comment]
We eventually managed to create a completely new form for Accounts and that worked ok.

Pam

________________________________________________________________________________
Pam Mannell

CRM Dynamics Limited, 11 Shirwell Crescent,  Furzton,  Milton Keynes,  MK4 1GA

t:  01908 929555
m: 07985 999762
e: pam@CRM-Dynamics.co.uk<mailto:pam@CRM-Dynamics.co.uk>
w: www.CRM-Dynamics.co.uk<http://www.crm-dynamics.co.uk/>

 [cid:image001.jpg@01D1EBCE.3349CD00]

**Comment by LeszekSzejka** [comment]
Some time ago I have wrote a post about that issue:
http://bds-experts.com/local-to-global-option-set-conversion/

**Comment by daryllabar** [comment]
@LeszekSzejka, your link that you provided is for issues with exporting and importing into a new environment...  That doesn't seem to apply to this issue.
