### ISSUE TITLE
Connection_Record1ObjectTypeCode is missing in generated optionsets

### ISSUE THREAD

**Issue by mattritchie** [daryllabar/DLaB.Xrm.XrmToolBoxTools#520]
**Tool and Version**
What tool/version is it that you're reporting a bug for? i.e.
EarlyBoundGenerator V 2.2024.9.11

**Describe the bug**
Similar to https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues/483
Using Connection as part of the whitelisted entities failed to create enums  Connection_Record1ObjectTypeCode and Connection_Record2ObjectTypeCode
![{69BB3742-A5D8-4E8D-AB2D-10D17271747E}](https://github.com/user-attachments/assets/0cd36dd8-ef95-40c6-ae9d-64b536f6810b)

**To Reproduce**

Have included my metadata as mentioned in the previous ticket
https://github.com/user-attachments/files/17288970/XRM.EBG.Bug.zip

**Expected behavior**
Enum gets generated

**Screenshots**
![{69BB3742-A5D8-4E8D-AB2D-10D17271747E}](https://github.com/user-attachments/assets/cfd3a765-7efd-4ce8-b356-f12005e3f172)

**Additional context**
I was hoping that setting the log level to something different might tell me some more info, but it only crashed XRM toolbox.

**Comment by daryllabar** [comment]
This is due to #477.  Will Need to convert these to ints.

**Comment by daryllabar** [comment]
Thank you so much for the metadata.  Made trouble shooting this way easier!
