### ISSUE TITLE
Customizable CustomTextWriter.InvalidStringsForPropertiesNeedingNullableTypes

### ISSUE THREAD

**Issue by janis-veinbergs** [daryllabar/DLaB.Xrm.XrmToolBoxTools#523]
Please make `CustomTextWriter.InvalidStringsForPropertiesNeedingNullableTypes` amendable by custom settings to satisfy use case #492

**Comment by daryllabar** [comment]
Hey, I've just made the entire thing configurable, but did not add it to the UI.  Let me know if this works for you, and if it does, I'll just push it out:
[DLaB.EarlyBoundGeneratorV2.zip](https://github.com/user-attachments/files/17689251/DLaB.EarlyBoundGeneratorV2.zip)

**Comment by eb-delska** [comment]
Just tried it out and it works for us.
