### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by micz97** [daryllabar/DLaB.Xrm.XrmToolBoxTools#525]
What defines the language used in the tool? I am specifically asking about part in the generated files:

> // <auto-generated>
> //     This code was generated by a tool.
> //
> //     Changes to this file may cause incorrect behavior and will be lost if
> //     the code is regenerated.
> // </auto-generated>

Is it the system language in Windows? I've got hundreds of changes in repo, just because of that part.

**Comment by daryllabar** [comment]
_(I'm just a typical American that has only ever interacted with US English computers, so I haven't had to ever personally deal with this, so I apologize in advanced for my own ignorance)_

That part is generated by the PAC CLI itself, but I believe it utilizes the language of windows.  

Have you tried setting the Suppress Autogenerated File Header Comment flag to true?
![image](https://github.com/user-attachments/assets/c50e71a4-2e77-48da-b0f2-92b2bc041773)

**Comment by micz97** [comment]
Haha, I am using English version of Windows myself, but the project files were generated in Polish. I've changed Windows language and it's fine now. Guess I will stick with my native language for a while :) Thanks!
