### ISSUE TITLE
Could not load provider Error

### ISSUE THREAD

**Issue by giggler25** [daryllabar/DLaB.Xrm.XrmToolBoxTools#53]
Hello,

Having an issue where I can connect fine to the organization but when I try to generate code I get the following error, anyone can point me to a possible solution?

CRM Authentication Type Detected: OnlineFederation
Executing "C:\Users\####\CRM SDK Samples\SDK\Bin\crmsvcutil.exe" /url:"#####" /namespace:"####" /out:"C:\Dev\CPP\MAIN - (LIVE)\SOURCE\CRMCommon\CRMEntities\XrmContext.cs" /servicecontextname:"XrmContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"#####" /password:"***********" 
CrmSvcUtil : CRM Service Utility [Version 8.1.0.7711]
¸ 2015 Microsoft Corporation. All rights reserved

CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.NotSupportedException: Could not load provider of type 'DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions'
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: CrmSvcUtil
Method	: CreateInstance
Date	: 4:25:41 PM
Time	: 8/2/2016
Error	: Could not load provider of type 'DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions'
Stack Trace	: at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
======================================================================================================================

Output file was not updated or not found!  C:\Dev\CPP\MAIN - (LIVE)\SOURCE\CRMCommon\CRMEntities\XrmContext.cs

**Comment by daryllabar** [comment]
Is the DLaB.CrmSvcUtilExtensions DLL in the crmsrvutil folder?  Is it locked?  You can try uninstalling and reinstalling the plugin...

**Comment by giggler25** [comment]
Hi again, that dll was in the crmsrvutil folder and reinstalling did not help. I then reinstalled the SDK and copied crmsvcutil into my working folder (with the dll) and it worked. Must have been something on that file and not your plugin.
Thanks for the help at any rate! 
(oh and love this plugin!)
