### ISSUE TITLE
Save/Load configuration

### ISSUE THREAD

**Issue by rappen** [daryllabar/DLaB.Xrm.XrmToolBoxTools#55]
I don't have a lot of experience with the tool, but since there are som many options to specify, would it not be great to be able to save selected options to a file so you can load the same configuration when starting next project, or running an update from CRM?

**Comment by daryllabar** [comment]
Yes, I've thought of that before.  Also thought of being connection sensitive, so if I connect to A org, use these settings, and B org use these.

The settings are saved to a file, so you could copy and paste it manually.  And I'm assuming your talking about the Early bound generator?

**Comment by rappen** [comment]
Yes, Early Bound Generator.
Perhaps not automatically saved, but Save and Open buttons. You might even want to check in those files with the project files to TFS (or git or ...)
