### ISSUE TITLE
Error creating Entities.cs

### ISSUE THREAD

**Issue by RodGit** [daryllabar/DLaB.Xrm.XrmToolBoxTools#58]
Please see the error message I am receiving every time I create the Entities class. This has only started recently with the new update. I am connecting to a CRM Online instance. It happens on Win 7 and Win8.1 machines that I have XrmToolbox installed.

Thanks for your time,

![xrmtoolbox_2016-09-18_13-47-57](https://cloud.githubusercontent.com/assets/5624236/18615769/14a17a9a-7da7-11e6-8906-1120d8b41f8c.png)

**Comment by daryllabar** [comment]
Interesting... Did it generate the same file name each time?  Does the file exist?  Is it read-only?

**Comment by RodGit** [comment]
Hi Daryl, yeah, it's a strange one. The file doesn't exist. When I select the option to create separate files, then all files are created successfully. It's only when I set it to be one file. 
Thanks for looking into this. your tool has always been a great asset in my projects.
I'm also allocating my development time to contribute to the Toolset. I'll let you now once I have it completed.
Thanks again

**Comment by daryllabar** [comment]
Oh, are you looking to make a Pull request for this?  If so, just let me know if you have any questions.

**Comment by RodGit** [comment]
Hi Daryl, I won't need a pull request as yet, but I wondered if you were able to identify the issue with saving of the Entities.cs. I've reverted back to your initial CRM2013 full version for now.
Thanks, have a good weekend

**Comment by daryllabar** [comment]
[DLaB.Xrm.2016.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/493085/DLaB.Xrm.2016.zip)
I think I found the issue.  Can you give this a try?

**Comment by daryllabar** [comment]
Any luck @RodGit?

**Comment by RodGit** [comment]
Hi Daryl,
It's working like a charm. Thanks very much for your update! It is much appreciated.
I have quite a busy week, but I'd like to make time to discuss an improvement and another idea for an XrmToolBox plugin.
I'll keep in touch.

Thanks again!
Made my week. :+1:

**Comment by daryllabar** [comment]
Awesome!  Feel free to discuss on Gitter: https://gitter.im/daryllabar/DLaB.Xrm.XrmToolBoxTools, or to open another issue.
