### ISSUE TITLE
Opionsets enums

### ISSUE THREAD

**Issue by gashupl** [daryllabar/DLaB.Xrm.XrmToolBoxTools#59]
Hello. 
I've problem with generating OptionSet.cs file. 
In my case I'm getting UnknownLabelX (where X is number) instead of "real" OptionSet label.  It looks somehow like:

	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum account_address1_addresstypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel1 = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel2 = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel3 = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnknownLabel4 = 4,
	}

I've tested solution on 2 different organizations (on-premise and online). For both English was not the default language. Early bound Generator version I'm currently using is 1.2016.9.10

**Comment by gashupl** [comment]
Update: When I've installed English language pack - OptionSets has been generated correctly (but of course - in English :(). Is it possible to generate OptionSets enums for other languages? It was in the past :).

**Comment by gashupl** [comment]
Ok. I've added json file for my language in alphabets folder and OptionSet generation starts to work correctly. Issue may be closed however there should be some information regarding this requirement. 
Best regards.

**Comment by daryllabar** [comment]
What language did you add?  I'd be happy to add it to the Code Base, so any future individuals desiring your language will get it.

What's the best way to provide information regarding this requirement?  What would make the most sense for someone brand new to using the tool?

**Comment by gashupl** [comment]
Hi Daryl,

You will find alphabet file for Polish language (code: 1045) attached to this e-mail.

Regarding requirement of adding other individual language files - maybe popup window (with the possibility of disabling it with "Do not show this information anymore") after clicking "Geenrate OptionSet" button would be good option ?

Kind regards.

Piotr

________________________________
Od: Daryl LaBar <notifications@github.com>
Wysłane: 4 października 2016 13:41
Do: daryllabar/DLaB.Xrm.XrmToolBoxTools
DW: gashupl; State change
Temat: Re: [daryllabar/DLaB.Xrm.XrmToolBoxTools] Opionsets enums (#59)


What language did you add? I'd be happy to add it to the Code Base, so any future individuals desiring your language will get it.

What's the best way to provide information regarding this requirement? What would make the most sense for someone brand new to using the tool?

-

**Comment by daryllabar** [comment]
GitHub e-mail stripped the attachment,  Use the GitHub issue webpage to actually attach the file.

**Comment by gashupl** [comment]
Hi,
It looks like push request for DLaB.Xrm.XrmToolBoxTools is not publicly availalble ;).
So I've created GIST with Early Bound Generator polish language file. You can find it here: https://gist.github.com/gashupl/ffced49047efb99bb72db401db097e88.
Best regards.
Piotr



________________________________
Od: Daryl LaBar <notifications@github.com>
Wysłane: 5 października 2016 14:56
Do: daryllabar/DLaB.Xrm.XrmToolBoxTools
DW: gashupl; State change
Temat: Re: [daryllabar/DLaB.Xrm.XrmToolBoxTools] Opionsets enums (#59)


GitHub e-mail stripped the attachment, Use the GitHub issue webpage to actually attach the file.

-

**Comment by daryllabar** [comment]
@gashupl the normal way to commit, is to fork this repository, make your change in your fork, and then create a pull request.  I would then review and accept/reject the pull request.  For this simple change, I'll do it manually.

Thanks for supporting the community!

**Comment by gashupl** [comment]
Huh. It looks like I'm VS TFS child [😊] .

Best regards.

PG


________________________________
Od: Daryl LaBar <notifications@github.com>
Wysłane: 6 października 2016 15:23
Do: daryllabar/DLaB.Xrm.XrmToolBoxTools
DW: gashupl; Mention
Temat: Re: [daryllabar/DLaB.Xrm.XrmToolBoxTools] Opionsets enums (#59)


@gashupl<https://github.com/gashupl> the normal way to commit, is to fork this repository, make your change in your fork, and then create a pull request. I would then review and accept/reject the pull request. For this simple change, I'll do it manually.

Thanks for supporting the community!
