### ISSUE TITLE
Error with early bound generator version 1.2016.9.10 on CRM 2016 on-prem with IFD - Unable to Login to Dynamics CRM CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Exception: Connection to CRM is not established. Aborting process.

### ISSUE THREAD

**Issue by mariusso** [daryllabar/DLaB.Xrm.XrmToolBoxTools#61]
I get the following with version 1.2016.9.10 on CRM 2016 on-prem with IFD (I have edited _username_, _org_ and _domain_):

CRM Authentication Type Detected: Federation
Executing "C:\Users\username\Desktop\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://org.domain.no/XRMServices/2011/Organization.svc" /generateActions /out:"C:\Users\username\Desktop\XrmToolBox\Plugins\CrmSvcUtil Ref\Actions.cs" /namespace:"CrmEarlyBound" /codecustomization:"DLaB.CrmSvcUtilExtensions.Action.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Action.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /username:"username" /password:"**************" /domain:"domain" 
CrmSvcUtil : CRM Service Utility [Version 8.1.0.7711]
c 2015 Microsoft Corporation. All rights reserved

Unable to Login to Dynamics CRM
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Exception: Connection to CRM is not established. Aborting process.
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source    : CrmSvcUtil
Method  : Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata
Date    : 12:50:45
Time    : 27.10.2016
Error   : Connection to CRM is not established. Aborting process.
Stack Trace : at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
#    at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)

Output file was not updated or not found!  C:\Users\username\Desktop\XrmToolBox\Plugins\CrmSvcUtil Ref\Actions.cs

**Comment by mariusso** [comment]
It is an issue with the authentication in the crmsvcutil. It works if run the traced command line and exclude the username, password and domain, and use/interactivelogin:true

**Comment by daryllabar** [comment]
This is the same as issue #33.  Looks like there is a bug in the CrmSrvcUtil that doesn't work with IFD.

You methond that you're able to use the interactive login to circumvent this?  Can you give me the full command line you use in order to enable that (feel free to * out anything that is unique to you).  I can at least provide this as a work around for IFDS automatically...

**Comment by mariusso** [comment]
I run the command line from the output window, remove username, password, domain, and add /interactivelogin:true. Or even better, you can add this line to the crmsvcutil.exe.config within appSettings:

<add key="interactivelogin" value="true" />

It is important to remember when you do this, you circumvent XRMToolBox own authentication and can connect to another CRM depllyment/organization. 

I have a different question. When generating optionsets, i get UnknownLabel. Is this because i have Norwegian as a base language? I could have sworn i worked earlier.

**Comment by daryllabar** [comment]
Yes.  The EBG now supports Transliteration though, so if you define your LCID
Decimal code for your language, it will give you an easily typed value.  We already have German, Polish, Russian, and Ukrainian.  Give me the json file and I'll include it in the EBG.

**Comment by daryllabar** [comment]
Ping @skfd  if you have any questions with it.

**Comment by mariusso** [comment]
@skfd @daryllabar  What do I have to do to get the JSON file for my language? Which is Norwegian. (1044),
Are you sure this has never worked because i have earlier generated optionsets for another deployment with norwegian base language. And i just recently updated the XrmToolbox and got the EBG from the store. And i can see the namingservice has changed from 

"DLaB.CrmSvcUtilExtensions.Entity.OverridePropertyNames,DLaB.CrmSvcUtilExtensions"

to

"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions"

**Comment by daryllabar** [comment]
When it comes to other languages, I'm a fairly clueless American.  I know English, and everyone I communicate with has been nice enough to learn it as well.

Here is the main code for getting option set names:

```
public string GetNameForOption(OptionSetMetadataBase optionSetMetadata, OptionMetadata optionMetadata, IServiceProvider services)
{
    var defaultName = DefaultService.GetNameForOption(optionSetMetadata, optionMetadata, services);

    defaultName = Transliterate(optionMetadata, defaultName);

    var newName = GetValidCSharpName(defaultName);
    newName = AppendValueForDuplicateOptionSetValueNames(optionSetMetadata, newName, optionMetadata.Value.GetValueOrDefault(), services);

    if (newName == defaultName)
    {
        Trace.TraceInformation("The name of this option is {0}", defaultName);
    }
    else
    {
        Trace.TraceInformation("The name of this option was {0} but has been changed to {1}", defaultName, newName);
    }

    return newName;
}

private static string Transliterate(OptionMetadata optionMetadata, string defaultName)
{
    var defaultNameIsInEnglish = !string.IsNullOrEmpty(defaultName) && !defaultName.Contains("UnknownLabel");
    if (defaultNameIsInEnglish)
    {
        return defaultName;
    }

    var localizedLabel =
        optionMetadata.Label
            .LocalizedLabels
            .FirstOrDefault(x =>
                TransliterationService.AvailableCodes.Value.Contains(x.LanguageCode));

    return localizedLabel == null ? 
        defaultName.RemoveDiacritics() : 
        TransliterationService.Transliterate(localizedLabel.LanguageCode, localizedLabel.Label);
}
```

The Default service is the standard service from the CrmSvcUtil.  Apparently, if there is no English version for the OptionSet, it will return "UnknownLabel" or potentially empty/null.  Then the EBG will look for the first localized label with an available alphabet.  If found, it will transliterate the name.  If not found, it will apparently just Remove the Diacritics of the empty or null or "UnknownLabel" which looks wrong to me.

I'm going to change it to Remove the Diacritics of the very first Localized Label it finds...  I don't know if I was doing that before... Don't think so...  But it could resolve your issue.


As for the Language File, You'd need to make your own.

**Comment by daryllabar** [comment]
@mariusso  Can you see if this version of the CrmSvcUtilExtensions works better?
[DLaB.CrmSvcUtilExtensions.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/557314/DLaB.CrmSvcUtilExtensions.zip)

**Comment by mariusso** [comment]
@daryllabar Sounds right if this one will default to a localized label. An we have only one language. The base language. I'll check it out right now!

**Comment by mariusso** [comment]
@daryllabar New Error:


System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, String replacement)
   at DLaB.CrmSvcUtilExtensions.NamingService.GetValidCSharpName(String name)
   at DLaB.CrmSvcUtilExtensions.NamingService.GetDuplicateNameValues(OptionSetMetadataBase metadata, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.NamingService.AppendValueForDuplicateOptionSetValueNames(OptionSetMetadataBase optionSetMetadata, String name, Nullable`1 value, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.NamingService.GetNameForOption(OptionSetMetadataBase optionSetMetadata, OptionMetadata optionMetadata, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.NamingService.GetNameForOption(OptionSetMetadataBase optionSetMetadata, OptionMetadata optionMetadata, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService.GenerateOptionSet(OptionSetMetadataBase optionSetMetadata, IServiceProvider services)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildAttributeOptionSet(EntityMetadata entity, AttributeMetadata attribute, CodeTypeMember attributeMember, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildEntity(EntityMetadata entity, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildEntities(EntityMetadata[] entityMetadata, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildCodeDom(IOrganizationMetadata organizationMetadata, String outputNamespace, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.Microsoft.Crm.Services.Utility.ICodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
Output file was not updated or not found!  C:\Users\acandoadmin\Desktop\XrmToolBox\Plugins\CrmSvcUtil Ref\EconaOptionSets.cs

**Comment by daryllabar** [comment]
Take two...
[DLaB.CrmSvcUtilExtensions.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/558351/DLaB.CrmSvcUtilExtensions.zip)

**Comment by mariusso** [comment]
Thanks :) I'll give it a go as soon as i can. I spent my day refactoring because i could continue with the old optionset file. But that on is in lower case and the new generated servicecontext-files uses camelCase 😆

**Comment by mariusso** [comment]
@daryllabar That one worked like a charm. Thank you. I'll just use that one until the next release. Thank you. I'll close the issue.

**Comment by daryllabar** [comment]
Thanks for supporting the community @mariusso !
