### ISSUE TITLE
Ability to change the name/convert to a calculated or rollup field

### ISSUE THREAD

**Issue by SimplerSoftware** [daryllabar/DLaB.Xrm.XrmToolBoxTools#67]
When I use the attribute manager to change the name of an existing attribute that is a calculated/rollup field, the new field that gets created is of type 'Simple' instead of calculated and unfortunately you can't change the type after it's been created and so the new field is useless.  It would also be nice to be able to convert a simple field to a calculated field.

**Comment by daryllabar** [comment]
Agreed.  I haven't needed that functionality yet, and haven't implemented it.  I'll user this to prioritize.
