### ISSUE TITLE
Nuget is broken: XrmToolBox (dependency) is not available

### ISSUE THREAD

**Issue by Mafii** [daryllabar/DLaB.Xrm.XrmToolBoxTools#69]
https://www.nuget.org/packages/XrmToolBox/

https://www.nuget.org/packages/DLaB.Xrm.XrmToolBoxTools/

**Comment by daryllabar** [comment]
So is it the XrmtoolBox Nuget Package that is no longer available>

**Comment by daryllabar** [comment]
No Response received... Closing issue.
