### ISSUE TITLE
OptionSetLabel Generation gives UnknownLabelX

### ISSUE THREAD

**Issue by micheleietri** [daryllabar/DLaB.Xrm.XrmToolBoxTools#71]
As sain in title, i can't use properly thif function, for every entity it gives me something like that

`public enum bt_ricerca_primosguardo_StatusCode
{
[System.Runtime.Serialization.EnumMemberAttribute()]
UnknownLabel1 = 1,

[System.Runtime.Serialization.EnumMemberAttribute()]
UnknownLabel2 = 2,
}`

Im working on an On-Premise crm, using italian language

**Comment by skfd** [comment]
Earlybound Generator does not have definition for Italian symbols. You can help out. Please see [examples](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/tree/master/DLaB.CrmSvcUtilExtensions/OptionSet/Transliteration/Alphabets).

**Comment by daryllabar** [comment]
This is actually going to change in a future update to just "_" since MyOptions.UnknownLabel1 is harder to read than MyOptions._1.   The solution really is to provide the Italian Symbols so you'll be able to see your labels.
