### ISSUE TITLE
Improved configuration handling

### ISSUE THREAD

**Issue by rappen** [daryllabar/DLaB.Xrm.XrmToolBoxTools#74]
Loading configuration could be done like this to use generic file if connection specific does not exist, and create new instance if non exists: (code snippet from FXB)
```
var currentSettings = new FXBSettings();
SettingsManager.Instance.TryLoad<FXBSettings>(typeof(FetchXmlBuilder), out currentSettings, ConnectionDetail?.ConnectionName) ||
SettingsManager.Instance.TryLoad<FXBSettings>(typeof(FetchXmlBuilder), out currentSettings);
ApplySettings();
```

Saving configuration should be done before closing plugin by overriding ``ClosingPlugin``:
```
public override void ClosingPlugin(PluginCloseInfo info)
{
    SaveSettings();
}

private void SaveSettings()
{
    var currentSettings = GetCurrentSettings();
    SettingsManager.Instance.Save(typeof(FetchXmlBuilder), currentSettings, ConnectionDetail?.ConnectionName);
}

```

**Comment by daryllabar** [comment]
Ok, I think I've made the required changes.  I've also gone through attempted to ILMerge the Code so now it's a single dll.  Anywho, can you try the file below, and tell me if it works?

[DLaB.EarlyBoundGenerator.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/678388/DLaB.EarlyBoundGenerator.zip)

**Comment by daryllabar** [comment]
@rappen Let me know if the latest version doesn't work for you.

**Comment by rappen** [comment]
Whoa, that was long ago.... sorry for the lack of feedback. :-/

**Comment by daryllabar** [comment]
As you can tell, I was on "pins and needles" waiting for a response. ;)
