### ISSUE TITLE
Unable to create file

### ISSUE THREAD

**Issue by MarcusNaylor** [daryllabar/DLaB.Xrm.XrmToolBoxTools#85]
Since moving to Windows 10 and updating to the latest versions of XRMToolbox 1.2017.2.13 and EB (1.2017.1.31) I am unable to create files the error is "Output file not updated" 

and the log shows the CrmSvcUtil options as the output

my execute string is (connection string starred out)
 "C:\XrmToolbox\Storage\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /namespace:"CrmEarlyBound" /out:"V:\VS\entitiesTEST.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /connectionstring:"Url=https://***;UserName=***;Password=***"

**Comment by MarcusNaylor** [comment]
Sorry repeated on issue #84.
Using  
/url:organization_service_url /username:<domain\username> /password:_password 
as the connection string fixes it for me.

**Comment by daryllabar** [comment]
What version of the plugin are you running?  What is your CRM Authentication Type?  (First line of output)  OnlineFederation?

**Comment by daryllabar** [comment]
Closing due to this being dup of #84
