### ISSUE TITLE
Add option to only get the Entity attributes consts

### ISSUE THREAD

**Issue by zmulk** [daryllabar/DLaB.Xrm.XrmToolBoxTools#86]
Some projects like to only use the Entity attributes constants to use in late bound.
So all the code for early bound is not necessary.
Is it possible to have an option to only get the Entity Attributes Constants without all the other stuff in the classes?

**Comment by daryllabar** [comment]
That would take quite a bit of work to either figure out how to turn off all of the default generation, and only do the custom, or to figure out how to edit the file post creation.  Is it possible?  Yes.  Am I going to implement it?  Probably not unless I hear multiple people wanting the feature.  If you'd like to implement it, I'd accept a pull request for it.

**Comment by daryllabar** [comment]
This is Jonas' Late Bound Generator.  If that is all you want, use his tool
