### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by benArrayx** [daryllabar/DLaB.Xrm.XrmToolBoxTools#9]
Hi Darryl, I'm unable to compile this project, I'm not clear on why, I have the 4.5.2 targetting pack installed. Here is a screenshot of the failing lines: http://screencast.com/t/1X1k51I5u8

Clearly the compiler is not understanding the => in the variable declaration, but I don't know why. Can you help with this?

**Comment by daryllabar** [comment]
This is handled by the new compiler in VS 2015.  Are you using VS2013?

**Comment by daryllabar** [comment]
You can also download a release if you just want the dlls...

**Comment by benArrayx** [comment]
OK, I’m on VS2012 at the mo. Will either update to work with 2012, or download the dlls as you say, thanks for the response!

**Comment by daryllabar** [comment]
Must be using VS 2015 or greater...
