### ISSUE TITLE
Cannot install Early Bound Generator through NuGet in Visual Studio

### ISSUE THREAD

**Issue by bboldwen** [daryllabar/DLaB.Xrm.XrmToolBoxTools#90]
Hello,

I recently stumbled upon your tool and I was trying to install it in Visual Studio but it wouldn't install.

The error I get when installing through NuGet:
Unable to resolve dependency 'XrmToolBox'. Source(s) used: 'nuget.org', 'Microsoft and .NET', 'Microsoft Visual Studio Offline Packages'.

It appears the XrmToolBox package is no longer available on NuGet, which this tool depends on. As seen here: https://www.nuget.org/packages/XrmToolBox/

Is there anyway to get this installed? 

Thanks!

**Comment by daryllabar** [comment]
I'm not sure what you mean exactly by install through visual studio.  If you are trying to run the tool, go to www.xrmtoolbox.com, download, unblock, unzip, run, and then open the plugin store, and download the Early bound generator from there.  If you are wanting to make a plugin for the XrmToolBox, the nuget packages is at https://www.nuget.org/packages/XrmToolBoxPackage/

**Comment by bboldwen** [comment]
Are you not the author of the NuGet package here? https://www.nuget.org/packages/DLaB.Xrm.EarlyBoundGenerator/

I am trying to download your NuGet package for this tool here:
https://www.nuget.org/packages/DLaB.Xrm.EarlyBoundGenerator/

Which has a depedency on this NuGet package:
https://www.nuget.org/packages/XrmToolBox/

Therefore, I cannot download and install Early Bound Generator from NuGet in Visual Studio. I have attached a screenshot of it. This is what happens when I try to install it in Visual Studio:
![earlyboundgeneratornugeterror](https://cloud.githubusercontent.com/assets/26421858/23966746/4a0dbb5a-099b-11e7-8f51-00badaa75200.png)

I hope that is clear. Sorry for the confusion.

Thanks.

**Comment by daryllabar** [comment]
Ah... you're trying to install it into a project?  Why?

Is see the issue in my nuspec file, and have corrected the issue, but not yet published (waiting on an update from MS)
