### ISSUE TITLE
Request: Add primary name attribute to early bound entity class..

### ISSUE THREAD

**Issue by htimsm87** [daryllabar/DLaB.Xrm.XrmToolBoxTools#96]
Add the name of the primary attributes (PrimaryNameAttribute) from EntityMetadata to the early bound entity classes.

Use case: Can write generic code to update name or retrieve just the entity (name).  Currently either have to hard code this or make a service call to retrieve the EntityMetadata to determine.

For example _this_ would be added for contact.
		public const string EntityLogicalName = "contact";
		_public const string PrimaryNameAttribute = "fullname";_

**Comment by daryllabar** [comment]
Not sure how that helps...  You have to define the class you are going to use, so at that point, you might as well define grab it from the fields

``` C#
var name = Contact.PrimaryNameAttribute;
// vs...
var name = Contact.Fields.FullName;
```

**Comment by htimsm87** [comment]
If you are using reflection and "generic" code you can determine what the Primary Attribute is by getting the primary field for the class.
public void GetEntityName(Entity entity) {
    var nameProperty = entity.GetType().GetField("PrimaryNameAttribute");
    var name = entity.GetType().GetProperty(nameProperty).GetValue();
    return name;
}

**Comment by daryllabar** [comment]
Touche...  I'll think about this one.

**Comment by PierreVicente** [comment]
I confirm that feature would be useful, the PrimaryIdAttribute too.

**Comment by mivra** [comment]
+1 for PrimaryIdAttribute, we had to go with calls to retrieve EntityMetadata so far.

**Comment by daryllabar** [comment]
So...  I could implement this as an interface, a custom attribute, or a just put it in the fields static class.

Preferences?

**Comment by PierreVicente** [comment]
Just a field in the static class as it is for public const string EntityLogicalName = "Account" 
Please add 
public const string PrimaryIdAttribute = "accountid";
public const string PrimaryNameAttribute = "name";
Thanks
